### ISSUE TITLE
Use a machine-readable format to hold the list data

### ISSUE THREAD

**Issue by ghost** [awesome-selfhosted/awesome-selfhosted#1038]
An interesting idea would be to create an XML document containing all repository data. Then someone could create an XML viewer, and then there would be an easy way to offline view the raw data of the repo. Currently, the only way that this data could be viewed offline, is via downloading the README, and users would not be able to view it due to it being written in markdown. I could start creating the file. Thoughts?

**Comment by Kickball** [comment]
We have had similar ideas, but often with YAML in mind. We did have a project underway that transformed the list into many different formats (https://github.com/arylatt/awesome-selfhosted-com).

**Comment by cpdevelops** [comment]
Is that project still going, and if so would it be ok for me to start contributing to it?

**Comment by Kickball** [comment]
I don't believe the project has been worked on for a while, and I don't think @arylatt or myself will be able to help with it. You are welcome to start contributing to it, at the moment the documentation is not super complete.

The most up to date branches are data-parsing and data-parsing-2, I'd start by looking at them.

**Comment by cpdevelops** [comment]
Ok thanks for the info. I'll close the issue now and get to work on that.

**Comment by Kickball** [comment]
@cpdevelops happy to hear that you're interested in moving it forward, the best way to discuss it with @arylatt and I is via our rocket chat (https://chat.awesome-selfhosted.com).

**Comment by nodiscc** [comment]
https://github.com/kkismd/pandoc-ymltbl can generate HTML/Markdown tables from another format (YAML). I'll have a try soon with a basic subset of the list to see if it could work for us.

Another aspect is the viewer, it must support filtering/sorting the list/table. If we're talking about viewing the list in a web browser there is probably a javascript library that can do that.

Reopening and renaming issue for further discussion

**Comment by nodiscc** [comment]
I have started working on something at https://github.com/nodiscc/awesome-selfhosted-yaml (short yaml template), it think the schema will be able to cover pretty much all our needs. I will try converting it to multiple display formats sometime soon. Pull Requests welcome.

**Comment by nodiscc** [comment]
As discussed in https://github.com/Kickball/awesome-selfhosted/issues/1200, each list item may have `last_update` and `maintained` keys, to allow for easy filtering of old or unmaintained projects.

Unmaintained projects could be kept in the raw list, while being hidden by default in the render

**Comment by nodiscc** [comment]
From #1287

- [ ] List non-web clients in the yaml file

```yaml
name: 'Mpd'
homepage_url: 'https://www.musicpd.org/'
...
license: 'GPLv3'
clients:
  - [ 'android', 'M.A.L.P', 'https://github.com/gateship-one/malp']
  - [ 'desktop','sonata','https://github.com/multani/sonata']
  ...
```

**Comment by nodiscc** [comment]
- https://github.com/Kickball/awesome-selfhosted/issues/89#issuecomment-441409373
- https://n8225.github.io/Awesome-Selfhosted-Gen/
- https://github.com/n8225/Awesome-Selfhosted-Gen/blob/master/output.json

**Comment by nodiscc** [comment]
https://github.com/n8225/awesome-selfhosted-gen/issues/10

**Comment by nodiscc** [comment]
Blocks https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2482

**Comment by nodiscc** [comment]
Work in progress at
- https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/2
- https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/3
- https://github.com/nodiscc/hecat

**Comment by nodiscc** [comment]
Remaining work (incomplete list) at https://github.com/nodiscc/hecat/milestone/1

**Comment by nodiscc** [comment]
You can find a preview of the future static HTML site here: https://nodiscc.github.io/awesome-selfhosted-html-preview/.

It is generated from https://github.com/awesome-selfhosted/awesome-selfhosted-data using https://github.com/nodiscc/hecat/and https://www.sphinx-doc.org/. The existing markdown version will keep being maintained, but generated automatically.

This will allow adding long-wanted features, such as multiple categories/tags per software project, displaying more information (numer of stars, last update date, icons, screenshots...) in the HTML version.

Work on the generator is still ongoing at https://github.com/nodiscc/hecat/pull/66. You can try out generating a local copy by cloning the repository, checking out the `export-html-singlepage` branch, and running `make clone_awesome_selfhosted test_export_awesome_selfhosted_html`

Where the final version will be hosted is still undecided, but I'd like it to be self-hosted (hosting costs should be minimal as it's a static HTML site, I am willing to support the costs).

Constructive feedback is welcome.

**Comment by nodiscc** [comment]
Fixed in https://github/com/awesome-selfhosted-data, https://awesome-selfhosted.net

Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.
