### ISSUE TITLE
Update URLs based on HTTP redirects

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#1120]
https://github.com/dkhamsing/frankenstein could be used to correct links leading to redirected URLs.

@m1guelpf submitted a (large) Pull Request at #1114 but due to the size of the patch and concurrent changes to the list  there were merge conflicts that would have taken a while to resolve.

I suggest applying the fixes in separate patches:

 * HTTP URLs that redirect to HTTPS
 * Github projects that have changed owners
 * Other redirects

**Comment by evaryont** [comment]
I just ran `awesome_bot` and it reported following problems:

#### Links 
  001. [L0105] 302 http://goaccess.io/  → https://goaccess.io/ 
  002. [L0109] 302 https://serposcope.serphacker.com/  → https://serposcope.serphacker.com/en/ 
  003. [L0110] 301 http://snowplowanalytics.com/  → https://snowplowanalytics.com/ 
  004. [L0115] 301 http://www.metabase.com/  → https://www.metabase.com/ 
  005. [L0116] 301 http://redash.io  → https://redash.io/ 
  006. [L0116] 302 https://demo.redash.io  → https://demo.redash.io/login?next=https%3A%2F%2Fdemo.redash.io%2F 
  007. [L0124] 301 http://www.alltubedownload.net  → https://www.alltubedownload.net/ 
  008. [L0134] 301 https://github.com/cantino/huginn  → https://github.com/huginn/huginn 
  009. [L0137] 301 https://github.com/pymedusa/SickRage  → https://github.com/pymedusa/Medusa 
  010. [L0138] 301 http://nodered.org/  → https://nodered.org/ 
  011. [L0139] 301 https://github.com/openhab/openhab  → https://github.com/openhab/openhab1-addons 
  012. [L0140] 302 http://politepol.com  → http://politepol.com/en/ 
  013. [L0141] 301 http://poffer.gabinaureche.com  → https://poffer.gabinaureche.com/ 
  014. [L0144] 301 https://github.com/sebsauvage/rss-bridge  → https://github.com/RSS-Bridge/rss-bridge 
  015. [L0146] 301 http://sickrage.github.io/  → https://sickrage.github.io/ 
  016. [L0148] 301 http://trigger-happy.eu/  → https://trigger-happy.eu/ 
  017. [L0149] 301 http://ziahamza.github.io/webui-aria2/  → https://ziahamza.github.io/webui-aria2/ 
  018. [L0150] 301 https://www.wtfdyu.me/  → https://wtfdyu.me:443/ 
  019. [L0151]  https://zenbot.s8f.org/ Failed to open TCP connection to zenbot.s8f.org:443 (Connection timed out - connect(2) for "zenbot.s8f.org" port 443) 
  020. [L0151]  https://s8f.org/zenbot.html Failed to open TCP connection to s8f.org:443 (Connection timed out - connect(2) for "s8f.org" port 443) 
  021. [L0162] 302 http://lehollandaisvolant.net/blogotext/  → https://lehollandaisvolant.net/blogotext/ 
  022. [L0162] 301 https://github.com/timovn/blogotext  → https://github.com/BlogoText/blogotext 
  023. [L0163] 503 http://demo-bludit.rhcloud.com/  
  024. [L0165] 302 http://dotclear.org/  → https://dotclear.org/ 
  025. [L0169]  https://hotglue.me/ SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  026. [L0169]  https://hotglue.me/demo/ SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  027. [L0171] 301 https://github.com/idno/idno  → https://github.com/idno/Known 
  028. [L0176] 301 https://github.com/torchbox/wagtail  → https://github.com/wagtail/wagtail 
  029. [L0186] 307 https://docs.services.mozilla.com/howtos/run-fxa.html  → https://mozilla-services.readthedocs.io/howtos/run-fxa.html 
  030. [L0188] 307 https://docs.services.mozilla.com/howtos/run-sync-1.5.html  → https://mozilla-services.readthedocs.io/howtos/run-sync-1.5.html 
  031. [L0190] 301 https://github.com/jcs/lobsters  → https://github.com/lobsters/lobsters 
  032. [L0193] 503 https://save.duyet.net/  
  033. [L0196] 301 https://github.com/plainmade/unmark  → https://github.com/cdevroe/unmark 
  034. [L0196]  https://unmark.it/ Failed to open TCP connection to unmark.it:443 (Connection timed out - connect(2) for "unmark.it" port 443) 
  035. [L0204] 301 https://github.com/adobo/agendav  → https://github.com/agendav/agendav 
  036. [L0205] 301 http://baikal-server.com/  → http://sabre.io/baikal/ 
  037. [L0206] 301 http://trac.calendarserver.org/  → https://trac.calendarserver.org/ 
  038. [L0207] 302 http://keithp.com/cgi-bin/gitweb.cgi?p=calypso.git;a=tree  → https://keithp.com/cgi-bin/gitweb.cgi?p=calypso.git;a=tree 
  039. [L0207] 302 http://keithp.com/calypso/  → https://keithp.com/calypso/ 
  040. [L0208] 301 http://www.davical.org/  → https://www.davical.org/ 
  041. [L0208] 302 https://gitlab.com/  → https://about.gitlab.com/ 
  042. [L0220] 301 https://actor.im/  → http://actor.im/ 
  043. [L0220] 301 https://app.actor.im  → http://app.actor.im/ 
  044. [L0230] 301 https://jitsi.org/Projects/JitsiMeet  → https://jitsi.org/jitsi-meet/ 
  045. [L0231] 301 https://jitsi.org/Projects/JitsiVideobridge  → https://jitsi.org/jitsi-videobridge/ 
  046. [L0234] 301 http://livehelperchat.com/  → https://livehelperchat.com/ 
  047. [L0235] 301 http://www.mattermost.org/  → https://www.mattermost.org/ 
  048. [L0235] 301 https://github.com/mattermost/platform  → https://github.com/mattermost/mattermost-server 
  049. [L0238] 301 http://wiki.mumble.info/wiki/Main_Page  → https://wiki.mumble.info/wiki/Main_Page 
  050. [L0240] 301 http://niltalk.com/  → https://niltalk.com/ 
  051. [L0244] 302 http://retroshare.org  → http://retroshare.sourceforge.net 
  052. [L0247]  https://scrollback.io/ SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  053. [L0248] 301 https://github.com/hanzz/spectrum2  → https://github.com/SpectrumIM/spectrum2 
  054. [L0249] 302 https://www.spreed.me/  → https://www.spreed.me/?&nlr 
  055. [L0250] 302 http://matrix.org/docs/projects/server/synapse.html  → https://matrix.org/docs/projects/server/synapse.html 
  056. [L0251] 302 http://matrix.org/docs/projects/client/matrix-console.html  → https://matrix.org/docs/projects/client/matrix-console.html 
  057. [L0252] 302 http://riot.im  → https://about.riot.im 
  058. [L0258] 301 https://zulip.org  → https://zulipchat.com 
  059. [L0268] 302 http://www.citadel.org/  → http://www.citadel.orgdoku.php 
  060. [L0271] 302 https://bitbucket.org/zhb/iredmail/commits/  → https://bitbucket.org/zhb/iredmail/commits/all 
  061. [L0272] 301 https://github.com/andryyy/mailcow  → https://github.com/mailcow/mailcow 
  062. [L0275] 301 http://modoboa.org/en/  → https://modoboa.org/en/ 
  063. [L0275] 301 https://github.com/tonioo/modoboa  → https://github.com/modoboa/modoboa 
  064. [L0283] 302 http://git.exim.org/exim.git  → https://git.exim.org/exim.git 
  065. [L0285] 301 http://mailcatcher.me/  → https://mailcatcher.me/ 
  066. [L0291] 301 http://www.sendmail.com/sm/open_source/  → https://www.sendmail.com/sm/open_source/ 
  067. [L0292] 301 http://slimta.org  → https://slimta.org/ 
  068. [L0298] 301 http://cyrusimap.org/  → https://www.cyrusimap.org/ 
  069. [L0299] 302 http://www.dovecot.org/  → https://www.dovecot.org/ 
  070. [L0308] 301 https://github.com/andris9/mailtrain  → https://github.com/Mailtrain-org/mailtrain 
  071. [L0311] 301 https://phplist.org  → https://www.phplist.org/ 
  072. [L0318] 301 http://cypht.org/index.html  → https://cypht.org/index.html 
  073. [L0318] 301 https://github.com/jasonmunro/hm3  → https://github.com/jasonmunro/cypht 
  074. [L0320] 301 http://demo.rainloop.net/  → https://mail.rainloop.net/ 
  075. [L0323] 301 http://www.afterlogic.org/webmail-lite  → https://www.afterlogic.org/webmail-lite 
  076. [L0331] 301 http://github.com/nordaaker/convos  → https://github.com/nordaaker/convos 
  077. [L0335]  https://avatar.playat.ch:1000/ SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello 
  078. [L0347] 301 http://www.kamailio.org/w/  → https://www.kamailio.org/w/ 
  079. [L0356] 301 http://www.freepbx.org  → https://www.freepbx.org/ 
  080. [L0356] 301 http://git.freepbx.org/projects/FREEPBX  → https://git.freepbx.org/projects/FREEPBX 
  081. [L0358] 301 http://2600hz.org/  → https://2600hz.org/ 
  082. [L0370] 302 https://podupti.me/go.php  → https://framasphere.org 
  083. [L0371] 301 http://www.discourse.org/  → https://www.discourse.org/ 
  084. [L0376] 302 http://fluxbb.org/  → https://fluxbb.org/ 
  085. [L0377] 301 http://friendica.com/  → http://www.friendica.com/ 
  086. [L0378]  https://git.gnu.io/gnu/gnu-social Failed to open TCP connection to git.gnu.io:443 (Connection refused - connect(2) for "git.gnu.io" port 443) 
  087. [L0379] 301 https://hubzilla.org  → https://project.hubzilla.org/ 
  088. [L0380] 302 https://www.humhub.org/  → https://www.humhub.org/en 
  089. [L0381] 301 http://posativ.org/isso/  → https://posativ.org/isso/ 
  090. [L0382]  https://jappix.com/ SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  091. [L0384] 302 https://mastodon.social  → https://mastodon.social/about 
  092. [L0385] 301 http://www.mybb.com/  → https://www.mybb.com/ 
  093. [L0389] 301 http://www.oxwall.org/  → https://www.oxwall.com 
  094. [L0392] 301 https://github.com/e14n/pump.io  → https://github.com/pump-io/pump.io 
  095. [L0396] 301 https://github.com/TelescopeJS/Telescope  → https://github.com/VulcanJS/Vulcan 
  096. [L0399] 301 https://vanillaforums.org/  → https://vanillaforums.com/en/software 
  097. [L0421] 301 https://jsxc.org  → https://www.jsxc.org/ 
  098. [L0424] 301 http://www.salut-a-toi.org/  → https://salut-a-toi.org/ 
  099. [L0424] 301 http://repos.goffi.org/sat  → https://repos.goffi.org/sat 
  100. [L0425] 301 http://repos.goffi.org/libervia  → https://repos.goffi.org/libervia 
  101. [L0425] 301 http://wiki.goffi.org/wiki/Libervia/en  → https://wiki.goffi.org/wiki/Libervia/en 
  102. [L0447] 302 http://demo.apostrophecms.org/  → http://demo.apostrophecms.org/spinup 
  103. [L0453] 301 http://www.couchcms.com/  → https://www.couchcms.com/ 
  104. [L0454] 302 http://getdirectus.com/  → https://getdirectus.com/ 
  105. [L0456] 301 http://www.elabftw.net  → https://www.elabftw.net/ 
  106. [L0456] 302 https://demo.elabftw.net  → https://demo.elabftw.netexperiments.php 
  107. [L0458] 301 https://www.impresspages.org/demo  → http://74416.cloud.impresspages.org?pa=CloudService.autologin&key=KD6LOoCG3L0CbKQP5CWZlZrCd5AYYXtypqa5GCBzer1f3HUZaGNlw5Oz0emO 
  108. [L0461] 301 http://modx.com/  → https://modx.com/ 
  109. [L0468] 301 https://www.pimcore.org/  → https://pimcore.com/ 
  110. [L0472] 301 http://publify.co/  → https://github.com/publify/publify 
  111. [L0472] 301 http://demo.publify.co/  → https://demo.publify.co/ 
  112. [L0473] 302 https://www.redaxo.org  → https://redaxo.org/ 
  113. [L0477] 301 http://www.sphido.org/  → https://www.sphido.org/ 
  114. [L0478] 301 http://www.spip.net/fr  → https://www.spip.net/fr 
  115. [L0479] 301 http://www.subrion.org  → https://subrion.org/ 
  116. [L0479] 301 http://demos.subrion.com  → https://demos.subrion.org/ 
  117. [L0480] 301 http://textpattern.com/  → https://textpattern.com/ 
  118. [L0480] 301 http://textpattern.co/demo  → https://textpattern.co/demo 
  119. [L0483] 301 http://www.wondercms.com  → https://www.wondercms.com/ 
  120. [L0483] 301 https://www.wondercms.com/demo  → https://www.wondercms.com/demo/ 
  121. [L0496] 302 http://demo.microweber.org/  → http://members.microweber.com/go_demo_redir.php 
  122. [L0498] 301 https://github.com/open-classifieds/openclassifieds2  → https://github.com/yclas/yclas 
  123. [L0499] 301 https://github.com/open-classifieds/open-eshop  → https://github.com/belherdigital/open-eshop 
  124. [L0501] 301 http://oxidforge.org  → https://oxidforge.org/ 
  125. [L0503] 301 http://demo.prestashop.com/  → http://demo.prestashop.com/en/ 
  126. [L0503] 301 https://www.prestashop.com/  → https://www.prestashop.com/en 
  127. [L0504] 302 https://pretix.eu/  → https://pretix.eu/about/en/ 
  128. [L0505] 302 https://www.shuup.com/  → https://www.shuup.com/en/ 
  129. [L0507] 301 http://thelia.net/  → https://thelia.net/ 
  130. [L0508] 301 https://www.woothemes.com/woocommerce/  → https://woocommerce.com/woocommerce/ 
  131. [L0508] 301 https://github.com/woothemes/woocommerce  → https://github.com/woocommerce/woocommerce 
  132. [L0524] 301 https://www.cups.org/software.php  → https://www.cups.org/software.html 
  133. [L0525] 301 https://paper.edra.ovh  → https://paper.edra.ovh/ 
  134. [L0536] 301 http://odoo.com  → https://www.odoo.com/ 
  135. [L0536] 301 https://demo.odoo.com/  → https://master.odoo.com/saas_master/demo/ 
  136. [L0559] 301 http://freshrss.org/  → https://freshrss.org/ 
  137. [L0559] 301 http://demo.freshrss.org/i/  → https://demo.freshrss.org/i/ 
  138. [L0560] 301 http://1pxsolidblack.pl/jarr-en.html  → https://1pxsolidblack.pl/jarr-en.html 
  139. [L0562] 301 https://github.com/ldleman/Leed  → https://github.com/LeedRSS/Leed 
  140. [L0563] 301 https://github.com/socketubs/leselys  → https://github.com/toxinu/leselys 
  141. [L0565] 301 https://github.com/mauricesvay/moonmoon  → https://github.com/moonmoon/moonmoon 
  142. [L0569] 301 http://reader.nunux.org/  → https://reader.nunux.org/ 
  143. [L0570] 301 http://readerself.com/  → https://readerself.com/ 
  144. [L0574] 301 http://selfoss.aditu.de/  → https://selfoss.aditu.de/ 
  145. [L0578] 301 http://framanews.org/  → https://framanews.org/ 
  146. [L0578] 301 https://tt-rss.org/gitlab/fox/tt-rss  → https://tt-rss.org/ 
  147. [L0599] 301 https://kinto.readthedocs.org  → https://kinto.readthedocs.io/ 
  148. [L0601] 301 http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh  → http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/ 
  149. [L0605] 301 https://seacloud.cc/demo  → https://seacloud.cc/demo/ 
  150. [L0610] 302 https://stash.z-hub.io/projects/ZP/repos/z-push  → https://stash.z-hub.io/projects/ZP/repos/z-push/browse 
  151. [L0614] 301 https://github.com/feross/bittorrent-tracker  → https://github.com/webtorrent/bittorrent-tracker 
  152. [L0617] 301 http://file.pizza/  → https://file.pizza/ 
  153. [L0618] 301 https://github.com/feross/instant.io  → https://github.com/webtorrent/instant.io 
  154. [L0631] 301 http://droppy.silverwind.io/  → https://droppy.silverwind.io/ 
  155. [L0632] 302 http://fileshelter.suroot.com/  → http://fileshelter.suroot.comhome 
  156. [L0635] 301 https://github.com/ipfspics/server  → https://github.com/ipfspics/ipfspics-server 
  157. [L0635]  https://ipfs.pics/ Failed to open TCP connection to ipfs.pics:443 (Connection timed out - connect(2) for "ipfs.pics" port 443) 
  158. [L0636] 302 http://jirafeau.net/  → https://jirafeau.net/ 
  159. [L0646] 301 http://www.projectsend.org/  → https://www.projectsend.org/ 
  160. [L0651]  https://up1.ca/ Failed to open TCP connection to up1.ca:443 (getaddrinfo: Name or service not known) 
  161. [L0652] 301 https://u.pste.pw  → https://pste.pw/ 
  162. [L0653] 301 https://github.com/remie/YouTransfer  → https://github.com/YouTransfer/YouTransfer 
  163. [L0665] 302 http://www.monstaftp.com/  → https://www.monstaftp.com/ 
  164. [L0666] 307 http://www.resourcespace.org  → https://www.resourcespace.com/ 
  165. [L0666] 307 http://www.resourcespace.org/trial  → https://www.resourcespace.com/trial 
  166. [L0666] 307 http://www.resourcespace.org/svn  → https://www.resourcespace.com/svn 
  167. [L0667] 302 https://sprut.io  → https://sprut.io/en 
  168. [L0667] 302 https://demo.sprut.io:9443  → https://demo.sprut.io/login?next=%2F 
  169. [L0691] 301 http://guac-dev.org/  → http://guacamole.incubator.apache.org/ 
  170. [L0693] 301 https://os.js.org/  → https://www.os-js.org/ 
  171. [L0693]  https://osjsv2.0o.no/ Failed to open TCP connection to osjsv2.0o.no:443 (Connection timed out - connect(2) for "osjsv2.0o.no" port 443) 
  172. [L0701] 302 https://cozy.io  → https://cozy.io/en/ 
  173. [L0702] 302 http://www.egroupware.org/  → http://www.egroupware.org/en/ 
  174. [L0703] 301 http://www.horde.org/  → https://www.horde.org/ 
  175. [L0706] 301 http://demo.kopano.com  → https://demo.kopano.com/ 
  176. [L0706] 302 https://stash.kopano.io  → https://stash.kopano.io/repos?visibility=public 
  177. [L0707] 301 http://www.mayan-edms.com  → https://www.mayan-edms.com/ 
  178. [L0707]  http://demo.mayan-edms.com Failed to open TCP connection to demo.mayan-edms.com:80 (getaddrinfo: Name or service not known) 
  179. [L0709] 302 http://www.sogo.nu/  → https://sogo.nu/ 
  180. [L0710] 301 https://www.tine20.org  → http://www.tine20.com/willkommen-community/ 
  181. [L0718] 303 https://www.admidio.org/demo/  → https://www.admidio.org/demo/adm_program/modules/announcements/announcements.php 
  182. [L0731] 301 http://www.ilias.de  → https://www.ilias.de/ 
  183. [L0731] 301 http://demo.ilias.de  → https://demo.ilias.de/ 
  184. [L0732] 302 http://www.lxhive.com/  → https://www.lxhive.com/ 
  185. [L0745] 301 https://graphhopper.com/  → https://www.graphhopper.com/ 
  186. [L0765] 301 https://github.com/jkbrzt/cloudtunes  → https://github.com/jakubroztocil/cloudtunes 
  187. [L0770] 301 http://koel.phanan.net/  → https://koel.phanan.net/ 
  188. [L0771] 301 http://libresonic.org/  → https://libresonic.org/ 
  189. [L0772] 301 http://mopidy.readthedocs.org/  → http://mopidy.readthedocs.io/ 
  190. [L0776] 301 http://www.musicpd.org/  → https://www.musicpd.org/ 
  191. [L0778] 301 http://www.ympd.org/  → https://www.ympd.org/ 
  192. [L0779] 302 https://www.sonerezh.bzh/demo/  → https://www.sonerezh.bzh/demo/login 
  193. [L0783] 302 http://cytu.be  → https://cytu.be/ 
  194. [L0784] 301 http://emby.media/  → https://emby.media/ 
  195. [L0788] 301 http://mistserver.org/  → https://mistserver.org/ 
  196. [L0790] 301 http://oddnetworks.com  → https://oddnetworks.com/ 
  197. [L0791] 301 http://sourceforge.net/projects/minidlna/  → https://sourceforge.net/projects/minidlna/ 
  198. [L0806]  https://www.crushpaper.com/ SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  199. [L0814] 301 https://projects.miguelpiedrafita.com/LicAPI  → https://projects.miguelpiedrafita.com/LicAPI/ 
  200. [L0824] 301 http://www.vimbadmin.net/  → https://www.vimbadmin.net/ 
  201. [L0824] 301 http://www.vimbadmin.net/demo/auth/login  → https://www.vimbadmin.net/demo/auth/login 
  202. [L0825] 301 http://visualcaptcha.net/  → https://visualcaptcha.net/ 
  203. [L0825] 301 http://demo.visualcaptcha.net/  → https://demo.visualcaptcha.net/ 
  204. [L0826] 301 https://www.webtrees.net  → https://www.webtrees.net/index.php/en/ 
  205. [L0835] 503 https://www.budgetapp.io/  
  206. [L0839] 302 https://firefly-iii.nder.be/  → https://firefly-iii.nder.be/login 
  207. [L0840] 301 http://git.tuxfamily.org/galette/galette.git/  → https://git.tuxfamily.org/galette/galette.git/ 
  208. [L0844] 302 https://app.invoiceninja.com/invoices/create  → https://app.invoiceninja.com/login 
  209. [L0845] 500 https://invoiceplane.com/  
  210. [L0845] 302 https://demo.invoiceplane.com  → https://demo.invoiceplane.com/index.php/sessions/login 
  211. [L0846] 301 http://ihatemoney.org/  → https://ihatemoney.org/ 
  212. [L0865] 301 http://dillinger.io/  → https://dillinger.io/ 
  213. [L0866] 301 https://www.hackmd.io  → https://hackmd.io/ 
  214. [L0868] 302 https://leanote.com/note  → https://leanote.com/login 
  215. [L0869] 301 http://georgeosddev.github.com/markdown-edit/  → http://georgeosddev.github.io/markdown-edit/ 
  216. [L0876] 301 https://github.com/novavex/textpad  → https://github.com/fendatr/textpad 
  217. [L0877] 302 https://pad.malte-kiefer.de/  → https://pad.malte-kiefer.de/index.php?note=HV4wMjxyB4hqPZz2 
  218. [L0881] 301 https://turtl.it/  → https://turtlapp.com/ 
  219. [L0889]  http://draw.etherpad.org/ Failed to open TCP connection to draw.etherpad.org:80 (Connection refused - connect(2) for "draw.etherpad.org" port 80) 
  220. [L0890] 301 https://demo.sandstorm.io/appdemo/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60  → https://oasis.sandstorm.io/appdemo/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60 
  221. [L0890] 301 https://demo.sandstorm.io/  → https://oasis.sandstorm.io/demo 
  222. [L0904] 301 http://teampass.net/  → https://teampass.net/ 
  223. [L0915] 301 https://paste.edra.ovh/  → https://paste.edra.ovh 
  224. [L0917] 301 http://hastebin.com/about.md  → https://hastebin.com/about.md 
  225. [L0917] 301 http://hastebin.com/  → https://hastebin.com/ 
  226. [L0919] 301 https://www.modernpaste.com  → http://modernpaste.com/ 
  227. [L0920] 302 http://p.thorsen.pm/  → https://ssl.thorsen.pm/paste/ 
  228. [L0922] 301 http://phpaste.sourceforge.io/  → https://phpaste.sourceforge.io/ 
  229. [L0922] 301 http://phpaste.sourceforge.net/demo  → https://phpaste.sourceforge.io/demo 
  230. [L0924]  https://p.pantsu.cat Failed to open TCP connection to p.pantsu.cat:443 (getaddrinfo: Name or service not known) 
  231. [L0930] 301 https://snipt.net/  → https://github.com/nicksergeant/snipt 
  232. [L0942] 301 https://www.devicehive.com/  → https://devicehive.com/ 
  233. [L0944] 302 http://habitica.com/  → https://habitica.com/ 
  234. [L0944] 301 https://github.com/HabitRPG/habitrpg  → https://github.com/HabitRPG/habitica 
  235. [L0951] 301 http://allegro.tech/tipboard/  → https://allegro.tech/tipboard/ 
  236. [L0952] 301 https://github.com/rolandgeider/wger  → https://github.com/wger-project/wger 
  237. [L0952] 302 https://wger.de/  → https://wger.de/en/ 
  238. [L0952] 302 https://wger.de  → https://wger.de/en/ 
  239. [L0963] 301 http://lychee.electerious.com/  → https://lychee.electerious.com/ 
  240. [L0964] 301 http://mediadrop.net/  → https://mediadrop.video/ 
  241. [L0965] 301 http://mediagoblin.org  → https://mediagoblin.org/ 
  242. [L0968] 301 http://blog.zx2c4.com/567  → https://blog.zx2c4.com/567 
  243. [L0968] 301 http://photos.jasondonenfeld.com/  → https://photos.jasondonenfeld.com/ 
  244. [L0972] 301 http://blog.plumi.org/  → https://blog.plumi.org/ 
  245. [L0988] 404 http://kyela.net/55232734237c8/  
  246. [L0989] 302 https://demo.limesurvey.org  → http://demo.limesurvey.org/ 
  247. [L0991] 301 http://git.domainepublic.net/?p=nuages.git;a=tree  → https://git.domainepublic.net/?p=nuages.git;a=tree 
  248. [L0993] 301 https://github.com/whitef0x0/tellform  → https://github.com/tellform/tellform 
  249. [L1004] 302 http://lehollandaisvolant.net/tout/oranjeproxy/  → https://lehollandaisvolant.net/tout/oranjeproxy/ 
  250. [L1009]  http://proxy.donttrustrobots.nl/ Failed to open TCP connection to proxy.donttrustrobots.nl:80 (getaddrinfo: Name or service not known) 
  251. [L1010] 301 https://banu.com/tinyproxy/  → https://tinyproxy.github.io/ 
  252. [L1018] 301 http://keeper.nunux.org/  → https://keeper.nunux.org/ 
  253. [L1019] 301 https://www.wallabag.org  → https://www.wallabag.org/en 
  254. [L1029] 302 http://yacy.net/en/index.html  → https://yacy.net/en/index.html 
  255. [L1046] 301 https://gitea.io  → https://gitea.io/en-US/ 
  256. [L1047] 301 http://gitlab.org/  → https://about.gitlab.com/ 
  257. [L1053] 502 http://klausdemo.lophus.org/  
  258. [L1057] 301 http://phabricator.org/  → https://www.phacility.com/ 
  259. [L1058]  https://svn.redmine.org/redmine/ SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  260. [L1059] 301 https://try.rhodecode.com/  → https://code.rhodecode.com/ 
  261. [L1063] 302 http://trac.edgewall.org/  → https://trac.edgewall.org/ 
  262. [L1065] 301 http://demo.phproject.org/  → https://demo.phproject.org/ 
  263. [L1065] 301 http://www.phproject.org/  → https://www.phproject.org/ 
  264. [L1080] 301 http://www.koding.com/  → https://www.koding.com/ 
  265. [L1082] 301 http://regexr.com/  → https://regexr.com/ 
  266. [L1085] 301 http://wide.b3log.org/signup  → https://wide.b3log.org/signup 
  267. [L1096] 301 https://jenkins-ci.org/  → https://jenkins.io/index.html 
  268. [L1107] 301 http://www.paraio.org  → http://paraio.org/ 
  269. [L1117] 301 https://docs.readthedocs.org/en/latest/install.html  → https://docs.readthedocs.io/en/latest/install.html 
  270. [L1123] 302 https://weblate.org  → https://weblate.org/en/ 
  271. [L1140] 301 http://kanboard.net/  → https://kanboard.net/ 
  272. [L1141] 301 http://wheatbin.com/  → http://www.wheatbin.com/ 
  273. [L1145] 301 http://restya.com/board/demo.html  → http://restya.com/board/demo 
  274. [L1147] 301 http://taskboard.matthewross.me/  → https://taskboard.matthewross.me/ 
  275. [L1148]  http://demo.taskfreak.com/ Failed to open TCP connection to demo.taskfreak.com:80 (getaddrinfo: Name or service not known) 
  276. [L1149]  https://demo.miguelpiedrafita.com/tasks/ SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  277. [L1168] 302 http://bumpy-booby.derivoile.fr/  → http://bumpy-booby.derivoile.fr/default/dashboard 
  278. [L1169] 301 http://www.cerberusweb.com/  → http://cerb.ai/ 
  279. [L1172] 301 http://diamantedesk.com/demo/  → https://diamantedesk.com/demo/ 
  280. [L1172] 301 http://diamantedesk.com/  → https://diamantedesk.com/ 
  281. [L1177] 301 http://www.otrs.com/  → https://www.otrs.com/ 
  282. [L1178] 302 https://www.bestpractical.com/rt/  → https://bestpractical.com/rt/ 
  283. [L1191] 301 https://project.polr.me/  → http://polrproject.org 
  284. [L1219] 301 https://github.com/ssddanbrown/BookStack  → https://github.com/BookStackApp/BookStack 
  285. [L1226] 302 https://phabricator.wikimedia.org/diffusion/MW/  → https://phabricator.wikimedia.org/source/mediawiki/ 
  286. [L1232] 301 http://realms.io/  → https://realms.io/ 
  287. [L1234] 302 https://tiki.org  → http://tiki.org/tiki-index.php 
  288. [L1234] 301 https://tiki.org/Demo  → https://tiki.org/Demo 
  289. [L1236] 302 https://wiki.mills.io  → https://wiki.mills.io/view/FrontPage 
  290. [L1237]  https://www.wikifeat.org/app/wikis/wikifeat/pages/welcome Failed to open TCP connection to www.wikifeat.org:443 (Connection refused - connect(2) for "www.wikifeat.org" port 443) 
  291. [L1239] 302 http://www.xwiki.org  → http://www.xwiki.org/xwiki/bin/view/Main/WebHome 
  292. [L1239] 302 http://playground.xwiki.org  → http://playground.xwiki.org/xwiki/bin/view/Main/WebHome 
  293. [L1248] 301 https://github.com/j8r/DPlatform  → https://github.com/DFabric/DPlatform-ShellCore 
  294. [L1256] 302 http://syncloud.org/  → https://syncloud.org/ 
  295. [L1259] 302 http://WikiSuite.org  → http://WikiSuite.org/Software 
  296. [L1259] 301 http://wikisuite.org/Source  → http://wikisuite.org/Source-Code 
  297. [L1274] 301 http://opensource.org/licenses/Artistic-2.0  → https://opensource.org/licenses/Artistic-2.0 
  298. [L1279] 301 https://creativecommons.org/about/cc0/  → http://creativecommons.org/share-your-work/public-domain/cc0/ 
  299. [L1282] 301 http://opensource.org/licenses/CPAL-1.0  → https://opensource.org/licenses/CPAL-1.0 
  300. [L1283] 301 http://www.cerberusweb.com/license  → http://cerb.ai/license 
  301. [L1284] 301 http://opensource.org/licenses/ECL-2.0  → https://opensource.org/licenses/ECL-2.0 
  302. [L1292] 301 http://opensource.org/licenses/LGPL-2.1  → https://opensource.org/licenses/LGPL-2.1 
  303. [L1293] 301 http://opensource.org/licenses/LGPL-3.0  → https://opensource.org/licenses/LGPL-3.0 
  304. [L1294] 301 http://opensource.org/licenses/MIT  → https://opensource.org/licenses/MIT 
  305. [L1296] 301 https://www.mozilla.org/MPL/2.0/index.txt  → https://www.mozilla.org/media/MPL/2.0/index.txt 
  306. [L1298] 302 https://www.sendmail.com/pdfs/open_source/sendmail_license.pdf  → https://www.proofpoint.com/us/products/sendmail-sentrion/ 
  307. [L1302] 301 http://opensource.org/licenses/ZPL-2.0  → https://opensource.org/licenses/ZPL-2.0 
  308. [L1311]  https://chat.awesome-selfhosted.com Failed to open TCP connection to chat.awesome-selfhosted.com:443 (getaddrinfo: Name or service not known) 
  309. [L1316] 301 https://www.reddit.com/r/selfhosted  → https://www.reddit.com/r/selfhosted/ 

#### Dupes 
  01. [L0124] http://www.alltubedownload.net
  02. [L0150] https://github.com/jchampemont/WTFDYUM
  03. [L0177] https://wordpress.org/
  04. [L0177] https://github.com/WordPress/WordPress
  05. [L0186] https://docs.services.mozilla.com/howtos/run-fxa.html
  06. [L0276] https://github.com/atech/postal
  07. [L0393] https://www.reddit.com/
  08. [L0641] https://github.com/ethanal/nimbus
  09. [L0643] https://www.pictshare.net/
  10. [L0649] https://transfer.sh
  11. [L0660] https://github.com/soyuka/explorer
  12. [L0662] https://github.com/xataz/gobrowser
  13. [L0730] https://www.edx.org/
  14. [L0769] http://www.icecast.org/
  15. [L0769] https://git.xiph.org/?p=icecast-server.git;a=summary
  16. [L0856] https://github.com/n1trux/awesome-sysadmin#metric--metric-collection
  17. [L0921] https://notehub.org
  18. [L0924] https://p.pantsu.cat
  19. [L0983] http://calagator.org/
  20. [L0990] https://github.com/nearbycoder/materialpoll
  21. [L1002] https://github.com/thekvs/microproxy
  22. [L1003] https://github.com/joshdick/miniProxy/
  23. [L1006] http://www.apsis.ch/pound/
  24. [L1026] http://www.gigablast.com/
  25. [L1062] https://github.com/thebuggenie/thebuggenie
  26. [L1081] http://micro.glark.io
  27. [L1225] https://github.com/claudioc/jingo
  28. [L1253] http://puffin.rocks/
  29. [L1277] https://opensource.org/licenses/BSD-3-Clause

**Comment by nodiscc** [comment]
Mostly fixed by now.
