### ISSUE TITLE
Move IoT applications to separate section/subsection

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#1146]
Once #1144 is merged, move IoT (Internet of Things) programming/management applications to a separate section/subsection.

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted#internet-of-things-iot

**Comment by nodiscc** [comment]
- [ ] NodeRED still needs to be moved.

**Comment by marcelbrueckner** [comment]
If Domoticz is sorted under Internet Of Things (IoT), shouldn't there also be other home automation solutions like Home Assistant, FHEM or openHAB (currently below https://github.com/Kickball/awesome-selfhosted#automation)?

**Comment by nodiscc** [comment]
@marcelbrueckner you are right, I missed these

- [ ] Move Home Assistant
- [ ] Move FHEM
- [ ] openHAB
- [ ] Add a cross-section link link `See also [Internet of Things (IoT)](#internet-of-things-iot)` at the top of the automation section
