### ISSUE TITLE
Create Single-Click Image Sharing Section

### ISSUE THREAD

**Issue by Kickball** [awesome-selfhosted/awesome-selfhosted#1199]
We should probably also move the image hosts from https://github.com/awesome-selfhosted/awesome-selfhosted#single-clickdrag-n-drop-upload (lutim, img.bi...) to a Single-click/drag-and-drop image sharing subsection in https://github.com/awesome-selfhosted/awesome-selfhosted#photo-and-video-galleries - @nodiscc.

I agree with the above, we have a lot of entries in the single click/drag and drop upload section and some entries better fit into the photo/video sharing section.

**Comment by nodiscc** [comment]
Old issue, there are not may items affected, the Single-click/drag-and-drop section is as good as any - this will be solved with tag-based organization (https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038)
