### ISSUE TITLE
add socks proxy

### ISSUE THREAD

**Issue by WANG-lp** [awesome-selfhosted/awesome-selfhosted#1332]
[Shadowsocks](https://shadowsocks.org/en/index.html) and [v2ray](https://www.v2ray.com/en/) are both SOCKS-based proxy and been widely deployed to bypass the internet regulation.

Please consider to add them to the list.

Thanks.

**Comment by Kickball** [comment]
I'm not 100% sure these fit the list, if any of the collaborators or contributors are able to have a think about this it would be appreciated!

**Comment by evaryont** [comment]
https://github.com/Kickball/awesome-selfhosted#proxy list a number of HTTP based proxies, but that isn't the only technology to route traffic around.

What was the intention of the category? Specifically HTTP **only**? Or any and all proxies? If it's the latter, I think both are valid additions to the list.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
