### ISSUE TITLE
Keratin AuthN

### ISSUE THREAD

**Issue by denji** [awesome-selfhosted/awesome-selfhosted#1362]
* https://keratin.tech/
* https://github.com/keratin/authn-server

**Comment by n8225** [comment]
Shouldn't this be added to https://github.com/n1trux/awesome-sysadmin#identity-management

**Comment by nodiscc** [comment]
@denji Yes, those are good alternatives, you should submit a patch to awesome-sysadmin for them too.

https://github.com/n1trux/awesome-sysadmin/blob/master/.github/CONTRIBUTING.md

**Comment by nodiscc** [comment]
@denji Yes, those are good alternatives, you should submit a patch to awesome-sysadmin for them too.

https://github.com/n1trux/awesome-sysadmin/blob/master/.github/CONTRIBUTING.md

**Comment by mooreds** [comment]
FusionAuth isn't open source, but I added it to the non free list: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2065

**Comment by nodiscc** [comment]
Please send a PR to https://github.com/n1trux/awesome-sysadmin#identity-management for Keratin AuthN.
