### ISSUE TITLE
Discussion: Games?

### ISSUE THREAD

**Issue by Toucan-Sam** [awesome-selfhosted/awesome-selfhosted#1555]
Would anyone else be interested in a games section that includes dedicated servers? Thinks like Minecraft, TF2, etc etc. The code is not open source, but they are often free and entirely self hostable? I'm personally usually looking for new stuff to play and host for small communities I'm part of.

Maybe it fits into a separate category? Open source vs not?

Interested in anyone else's thoughts and if it's worth putting a merge request in.

**Comment by evaryont** [comment]
There is the [Games section](https://github.com/Kickball/awesome-selfhosted#games) already.

The game servers you've listed are all non-free, so they wouldn't go into the main README but [non-free.md](https://github.com/Kickball/awesome-selfhosted/blob/master/non-free.md). I'm not certain if we want to list every srcds-powered game, etc, though. Perhaps just the most popular ones?

It's unfortunate though that private/personal dedicated servers are a dying breed. Perhaps if there are any recent games that support dedicated servers in a simple fashion (Factorio and Minecraft are the first two that come to mind).

**Comment by nodiscc** [comment]
https://packages.debian.org/stretch/minetest-server FOSS

**Comment by nodiscc** [comment]
Game server management panels

- [ ] https://linuxgsm.com/
- [ ] https://pterodactyl.io/

**Comment by nodiscc** [comment]
The [Games](https://github.com/Kickball/awesome-selfhosted#games) section already lists a few game servers, and https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2857 will add a new section for game server management tools.

Closing, feel free to open separate issues or pull requests to add other game-related software.
