### ISSUE TITLE
Add Smashing

### ISSUE THREAD

**Issue by kimreyio** [awesome-selfhosted/awesome-selfhosted#1604]
Smashing is a Sinatra based framework that lets you build beautiful dashboards. 
https://smashing.github.io/

Language:Ruby
License: MIT ( https://github.com/Smashing/smashing/blob/master/MIT-LICENSE ) 
Category: Personal Dashboards

**Comment by worldworm** [comment]
If i understand it correctly, Smashing is a fork/successor of Dashing which is listed here: https://github.com/n1trux/awesome-sysadmin#metric--metric-collection
Isn't a change/addition at awesome-sysadmin better? What do you think?

https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1036
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1037

**Comment by jdorel** [comment]
Fixed by #2468
