### ISSUE TITLE
Add *boorus

### ISSUE THREAD

**Issue by DonaldTsang** [awesome-selfhosted/awesome-selfhosted#1605]
- [ ] https://github.com/r888888888/danbooru
- [ ] https://github.com/moebooru/moebooru
- [x] ~~https://github.com/zixaphir/gelbooru-fork~~ unmaintained
- [ ] https://github.com/shish/shimmie2
- [x] ~~https://code.acr.moe/kazari/myimouto-untouched~~ cert expired
- [ ] https://github.com/rr-/szurubooru
- [x] ~~https://github.com/mserajnik/hydrusrvue~~ deleted

**Comment by nodiscc** [comment]
- https://github.com/zixaphir/gelbooru-fork unmaintained (2017-02)
- https://code.acr.moe/kazari/myimouto-untouched unmaintained (2016-09)

This would probably warrant a new `Imageboards` subsection under the `Forums` section.

**Comment by DonaldTsang** [comment]
@nodiscc both Gelbooru and MyImouto are historic, so the codebase is untouched
