### ISSUE TITLE
Add Elephant

### ISSUE THREAD

**Issue by kimreyio** [awesome-selfhosted/awesome-selfhosted#1680]
Elephant is a FOSS note taking application with a very classic interface. 

Last release: May 1 2018
Website: http://elephant.mine.nu/
Github: https://github.com/jusu/Elephant
License: Apache 2.0  https://github.com/jusu/Elephant/blob/master/LICENSE.txt

**Comment by worldworm** [comment]
I'am not able to find any documentation. I looks like a desktop/client application for me, cannot find the selfhosted aspect.
Can you help me here? @kimreyio

**Comment by nodiscc** [comment]
Desktop notetaking application (portable/released as `.jar`), appears to store document as files so you can easily sync your data with existing [file synchronization](https://github.com/awesome-selfhosted/awesome-selfhosted#file-transfersynchronization) solutions.

Doesn't qualify for the list but looks good, you could submit it to https://github.com/luong-komorebi/Awesome-Linux-Software
