### ISSUE TITLE
Add decsync - File based calendar, contacts sync

### ISSUE THREAD

**Issue by charsi** [awesome-selfhosted/awesome-selfhosted#1691]
DecSync - https://github.com/39aldo39/DecSync

For file based Calender, Contacts syncing this is a great solution. Syncing is not included as it just saves everything to DecSync folder. The folder can be then synced with syncthing or Dropbox etc. 

Pros 
- Serverless,
- No account sign up required
- FOSS  (Client app available on F-droid) 
https://f-droid.org/packages/org.decsync.cc/

**Comment by evaryont** [comment]
Hm, this is an interesting one. There isn't a custom server, but instead a particular use case of Syncthing. Does it deserve a separate entry in the list, when there isn't anything additional to host? Or perhaps as a sub-bullet of Syncthing's entry?

**Comment by charsi** [comment]
I think this belongs under 'Calendaring and Contacts Management' since the use case is not specific to Syncthing. User is free to use any file syncing solution they want.
DecSyncCC is focused at syncing contacts and calendar.

**Comment by worldworm** [comment]
@charsi I think this issue can be closed.
decsync was added with https://github.com/awesome-selfhosted/awesome-selfhosted/commit/cffd3a627498ed6e65d4567adaa49047c64829c8

**Comment by nodiscc** [comment]
[](url)
