### ISSUE TITLE
Add Invidious

### ISSUE THREAD

**Issue by Perflyst** [awesome-selfhosted/awesome-selfhosted#1708]
Invidious is an alternative front-end to YouTube

https://github.com/omarroth/invidious/

**Comment by bugs181** [comment]
Came to create this exact request. I can't believe this one hasn't gotten ANY attention. This is a BEAUTIFUL self hosted alt to using YouTube.

**Comment by nodiscc** [comment]
>  I can't believe this one hasn't gotten ANY attention

patches welcome

**Comment by bugs181** [comment]
> > I can't believe this one hasn't gotten ANY attention
> 
> patches welcome

I meant the project/issue in general. Not that someone hasn't added it. Wanted to clarify so that it didn't sound rude.
