### ISSUE TITLE
Add distbin

### ISSUE THREAD

**Issue by ghost** [awesome-selfhosted/awesome-selfhosted#1712]
#pastebins
+  [distbin](https://github.com/gobengo/distbin)

**Comment by SuperSandro2000** [comment]
> distbin
Post bin with distributed social features.
A networked place to store posted web documents. This is meant to allow for distributed social commentary and reaction around these documents using best practices recommended or noted by the W3C Social Web Working Group.

**Comment by gobengo** [comment]
Author here. I follow awesome-selfhosted repo discussion via email. Let me know if there is anything I can answer or work on in the future to make this a good fit.

**Comment by worldworm** [comment]
https://github.com/gobengo/distbin/issues/37

**Comment by strypey** [comment]
I've used DistBin a fair bit over the last year or two, but I haven't yet figured out how it's supposed to interoperate with other ActivityPub services. distbin.com seems to have been down for almost 6 months, and may not be coming back. I'm not sure if the software is still in active development.

**Comment by nodiscc** [comment]
https://github.com/gobengo/distbin Unmaintained since 2019
