### ISSUE TITLE
Remove visualCaptcha

### ISSUE THREAD

**Issue by luxlogica** [awesome-selfhosted/awesome-selfhosted#1724]
Unfortunately, the **visualCaptcha** project seems to be abandoned. Although the [official website](https://visualcaptcha.net) is still up, and announces that the project has been acquired by a commercial company, the [project's official repository](https://github.com/desirepath41/visualCaptcha) has not seen any activity for well over a year, and clearly states that it is no longer maintained:

**"Please note visualCaptcha is no longer actively developed."**

**Comment by rodavelino** [comment]
Ping @nodiscc, you can close this one.
