### ISSUE TITLE
Add Flectra

### ISSUE THREAD

**Issue by aiveras** [awesome-selfhosted/awesome-selfhosted#1734]
Please add Flectra an Opensource ERP forked from Odoo
Website: https://flectrahq.com/
Repo: https://gitlab.com/flectra-hq/flectra

**Comment by nodiscc** [comment]
Better wait for this to be resolved https://www.odoo.com/page/flectra-vs-odoo-flectrahq-enterprise

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
