### ISSUE TITLE
Add Botpress

### ISSUE THREAD

**Issue by luxlogica** [awesome-selfhosted/awesome-selfhosted#1737]
**[Botpress](https://botpress.io)** is an open-source AI chat bot.

**Comment by worldworm** [comment]
@nodiscc 
Botpress has such a weird "[dual-license](https://github.com/botpress/botpress#license)". Whats the best way?

**Comment by nodiscc** [comment]
https://botpress.com/faq:

> Are there any restrictions to use of the Botpress modules?

> Yes, under the Botpress license you can only use the modules to build chatbots which is the primary purpose of the platform. You cannot use it to build other commercial applications such as your own chatbot development platform without getting consent from Botpress first.

It would need to go to https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md

**Comment by luxlogica** [comment]
@nodiscc you seem to have left out the _last sentence_ in that FAQ item you copied, which is: **"There are no restrictions under the AGPLlicense other than the copyleft obligations"**.

Botpress is indeed, _free to use as you wish_ under the AGPL.

**Comment by nodiscc** [comment]
> Freedom 0: The freedom to run the program for any purpose.

Maybe I missed something. Can I use Botpress to build other commercial applications such as my own chatbot development platform without getting consent from Botpress first?

**Comment by luxlogica** [comment]
@nodiscc yes, you can - if you use it under the *AGPL license*, and obey its copyleft obligations.

**Comment by nodiscc** [comment]
> https://botpress.com/
>> The building blocks for building chatbots

It's a framework to develop chat bots, not an end-user application. If you can find applications built using chatbot they would probably fit in this list, but chatbot itself does not.
