### ISSUE TITLE
Add ScreenCloud

### ISSUE THREAD

**Issue by Rid** [awesome-selfhosted/awesome-selfhosted#1747]
ScreenCloud allows you to take and upload screenshots to multiple backends https://github.com/olav-st/screencloud

**Comment by worldworm** [comment]
@Rid ScreenCloud looks like a great tool, but it doesn't really seem to fit into the self-hosted topic. If I understand it correctly it is just a client tool.
What do you think?

**Comment by nodiscc** [comment]
It looks like it is a desktop client yes. The good news is you can apparently [host your screencloud server](https://screencloud.net/) on SFTP. Closing nevertheless, not a network service.
