### ISSUE TITLE
Ranking / reviews / additional description for projects

### ISSUE THREAD

**Issue by jtagcat** [awesome-selfhosted/awesome-selfhosted#1766]
Hi, I'm already attempting to go through everything to interest for me in awesome-*. I could share my opinions, analysis from comparing in each category.
This would definitely need to have a 'best before', so people wouldn't take an old opinion for granted. Additionally it may be concerning, that it will not be neutral. While I'd be not ranking, I'd definitely give my opinion.
If agreed to add, it would probably be a link for every category.

**Comment by nodiscc** [comment]
Review threads were mentioned multiple times and would be good resources.

I think we should wait for https://github.com/Kickball/awesome-selfhosted/issues/89 to become something actionable. What should _not_ be done:

- Use github issues for reviews.
- Maintain reviews as text files in the repo (cumbersome)

What shoud probably be done
- Find someone willing to host (easy) and moderate (hard) a public discussion system for reviews ([discourse](https://www.discourse.org/), RSS aggregator/planet, git repo, wiki, any other...)
- Link to each app's review thread from the list

**Comment by jtagcat** [comment]
I have no idea how much moderation would be needed. Any ideas?

**Comment by RashadBrowne** [comment]
Could we use a separate sub-reddit with a table of contents pinned to the top? People would already have accounts so it would lower the barrier to give feedback. Moderation would be the main issue.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this issue worked on, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
