### ISSUE TITLE
Remove dead links, unmaintained projects, syntax/formatting issues

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#1767]
[![](https://img.shields.io/travis/awesome-selfhosted/awesome-selfhosted/master?label=link%20checks)](https://travis-ci.org/awesome-selfhosted/awesome-selfhosted/branches)

Click on the badge above, then follow the link to `master` to see a list of current syntax errors, dead links, and unmaintained software projects in awesome-selfhosted.

Feel free to help fixing these issues by following the usual [contribution](CONTRIBUTING.md) process (edit the README.md file, propose your change through a Pull Request).

> Software with no development activity for 6-12 months may be removed from the list.

Remember that some projects are feature-complete/mature/simple enough that they don't need much maintenance. Check if they still have active users/work as advertised before removing them.

**Comment by worldworm** [comment]
I checked every link error and wrote to the corresponding maintainers. With some repos I could find the problem directly. For this I opened a pull request.

**Comment by worldworm** [comment]
I contacted Tokumei via Mail, but the mailserver doesn't exist anymore. I see no other way in contacting them

**Comment by worldworm** [comment]
Email from a Tokumei  maintainer:

> We're not exactly actively developing or maintaining Tokumei right now though.
You can find Tokumei's source code in Gitlab at https://gitlab.com/tokumei
I don't think Kyle is self-hosting our code anymore.
The demo site hasn't worked for ages, maybe Kyle can bring it back up?
I have ambitions for a re-write, but unfortunately no time.

I've changed the repo link. 
Should we give it a few weeks till removing the demo link?

**Comment by nodiscc** [comment]
@worldworm yes, you can safely remove the tokumei demo link as it doesn't work for quite some time. Someone could re-add it if the demo comes back up again. It is better to show no information, than wrong information.

**Comment by worldworm** [comment]
These are a bit difficult:
### Qmail
http://www.qmail.org/top.html
I can not find another site or contact.

### Sphido
http://www.sphido.org/ will not work
but this will work http://www.sphido.org/

Also the repo has changed https://github.com/sphido/cms
https://github.com/sphido/sphido

The awesome-selfhosted discription says "PHP CMS", but when i visit the repo the words "npm static site generator" jumps into my face

**Comment by marcelbrueckner** [comment]
> ### Qmail
> http://www.qmail.org/top.html
> I can not find another site or contact.

https://cr.yp.to/qmail.html

**Comment by worldworm** [comment]
> > ### Qmail
> > http://www.qmail.org/top.html
> > I can not find another site or contact.
> 
> https://cr.yp.to/qmail.html

I stumbled across this site too, but it isn't referencing anywhere to the repo https://sources.debian.net/src/netqmail/1.06-5/
Or is the repo also outdated?
But it is referencing to the dead site http://www.qmail.org

**Comment by marcelbrueckner** [comment]
According to the official-looking website [back in May 2019](https://web.archive.org/web/20190508173254/http://www.qmail.org/top.html) version 1.06 is the latest, so the repo seems to be up-to-date.

Cross check Wikipedia: https://en.wikipedia.org/wiki/Qmail

**Comment by worldworm** [comment]
Thanks @marcelbrueckner

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/Kickball/awesome-selfhosted/builds/576912482

**Comment by worldworm** [comment]
An idea from my side: The monthly check could additionally check at github repos if it was archived.

**Comment by nodiscc** [comment]
> check at github repos if it was archived

https://github.com/Kickball/awesome-selfhosted/issues/1794

:+1:

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/Kickball/awesome-selfhosted/builds/584973909

**Comment by worldworm** [comment]
Is Archived
https://github.com/jchampemont/WTFDYUM

https://gitlab.com/oddnetworks/oddworks/core/issues/285
http://oddnetworks.com 

Contacted via Mail
https://cecill.info/

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/Kickball/awesome-selfhosted/builds/591605573

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/Kickball/awesome-selfhosted/builds/597745652

**Comment by worldworm** [comment]
noosfero contacted via telegram
https://gitlab.com/newspipe/newspipe/issues/47
https://community.invoiceplane.com/t/topic/8393/2

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/awesome-selfhosted/awesome-selfhosted/builds/603506966

**Comment by nodiscc** [comment]
- Dante Stories - https://github.com/michelson/dante-stories/issues/20
- Mailinabox - https://github.com/mail-in-a-box/mailinabox/issues/1665
- Noosfero - https://gitlab.com/noosfero/noosfero/issues/414

**Comment by nodiscc** [comment]
URL checks updated: https://travis-ci.org/awesome-selfhosted/awesome-selfhosted/builds/612868092

**Comment by worldworm** [comment]
Mailed cecill.info again...

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/awesome-selfhosted/awesome-selfhosted/builds/621238480

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/awesome-selfhosted/awesome-selfhosted/builds/630319384

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/awesome-selfhosted/awesome-selfhosted/builds/643075297

**Comment by nodiscc** [comment]
URL checks updated  https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds/672198950

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds/685338938

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds/685347120

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds/690340998

**Comment by worldworm** [comment]
Wrote a mail to the Webmaster https://git.xiph.org/ regarding Icecast 2.

All other links are up again

**Comment by SuperSandro2000** [comment]
Xiph gitlab writes:
``OSUOSL/Nero are experiencing Internet connectivity problems. This affects us as we're hosted with OSUOSL. We apologize for the inconvenience.
``

Also I think the link should be updated to https://gitlab.xiph.org/xiph/icecast-server

**Comment by worldworm** [comment]
@SuperSandro2000 Thanks for the hint. PR is created.

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds/696113686

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds/709663749

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds/713428552

**Comment by nodiscc** [comment]
URL checks updated https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds/719111695

**Comment by nodiscc** [comment]
URL checks will now run automatically, weekly, as well as a check on last commit dates in github.com repositories.

Cleanup, moving this issue to https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2266
