### ISSUE TITLE
Check Firefox Auth/Content Server

### ISSUE THREAD

**Issue by worldworm** [awesome-selfhosted/awesome-selfhosted#1792]
The following entries need a check:
- [Firefox Auth Server](https://github.com/mozilla/fxa-auth-server)
- [Firefox Content Server](https://github.com/mozilla/fxa-content-server)

Both repos are archived and moved to a new (merged?) one.
Whats with Firefox Sync Server? This project seems to be active.

The Sitelink needs a check too. Both entrys share the same link (duplicate found https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1767)
https://docs.services.mozilla.com/howtos/run-fxa.html

**Comment by stingalleman** [comment]
#2042 fixed this
