### ISSUE TITLE
check-github-commit-dates.py: report "archived" projects

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#1794]
We should let the script check whether a project was archived, and if true, emit a warning.

https://developer.github.com/v3/repos/#response
>     "archived": false,

Ref. https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1767

**Comment by n8225** [comment]
I'm tempted to rewrite the script in Go, pulling most of the code from the static site generator which already access the GitHub API. If I do that this should be a fairly easy addition.

**Comment by nodiscc** [comment]
Hmmmm I think an interpreted language like python is a better fit for a CI toolchain. It's easily extensible, can be run/edited by anyone with a Python interpreter (basically everyone), CPU architecture-independent, etc. It has well-established libraries for everything we would need.

The script is still quite simple/clean (for how long? :) ) so I'm tempted to leave it as is.

But I am all for reducing overlap (there is some) between the different tools (https://github.com/Kickball/awesome-selfhosted/blob/master/Makefile, https://github.com/Kickball/awesome-selfhosted/blob/master/tests/test.js, https://github.com/Kickball/awesome-selfhosted/blob/master/tests/check-github-commit-dates.py, https://github.com/n8225/awesome-selfhosted-gen ...).

On the other hand if we soon™ switch to a [yaml](https://github.com/Kickball/awesome-selfhosted/issues/1038)-based list most of the script would be obsolete, and yes, you would have to implement these checks in go at https://github.com/n8225/awesome-selfhosted-gen
