### ISSUE TITLE
Add RStudio

### ISSUE THREAD

**Issue by amazzoccone** [awesome-selfhosted/awesome-selfhosted#1847]
RStudio is a popular software for data science.

Website: https://rstudio.com/
Github: https://github.com/rstudio
License: GPL-3

**Comment by worldworm** [comment]
Hi, i think RStudio is already here.
Please have a look. Thanks!
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/286/commits/b38707be9007808261fc139a19ab675375a1ae3b

**Comment by amazzoccone** [comment]
Sorry! I didn't see it :confounded: . Thanks.
