### ISSUE TITLE
Add a list of free security testing tools

### ISSUE THREAD

**Issue by WebOrganics** [awesome-selfhosted/awesome-selfhosted#1862]
The list contains a huge amount of free software tools, which inherently include vulnerabilities when un-patched or not updated to latest secure versions. 

Please also add a list of free security tools such as scanners, firewalls and WAFs.

**Comment by nodiscc** [comment]
This would be more suited to https://github.com/n1trux/awesome-sysadmin

> Please also add a list of free security tools such as scanners, firewalls and WAFs.

Please do :)

I use and can recommend [fireHOL](https://firehol.org/), [lynis](https://cisofy.com/lynis/), [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades), [modsecurity](https://modsecurity.org/), [logwatch](https://wiki.archlinux.org/index.php/Logwatch) and/or [graylog](https://www.graylog.org/), [debsecan](https://packages.debian.org/buster/debsecan), [debsums](https://packages.debian.org/stable/debsums) good practices/configuration hardening like https://github.com/dev-sec/ansible-ssh-hardening, https://github.com/dev-sec/ansible-os-hardening/, https://github.com/RedHatOfficial/ansible-role-rhel7-stig...

But these are just tools and security is a process. I recommend starting with one of the many [hardening guides](https://www.linuxtrainingacademy.com/hardening/) available online, and _understanding_ how your systems work.
