### ISSUE TITLE
Add Stretto under Audio Streaming

### ISSUE THREAD

**Issue by benkaiser** [awesome-selfhosted/awesome-selfhosted#1902]
I write a open-source web based music player called Stretto that users can self-host. It easily allows adding music from Youtube and Soundcloud, and provides cool features such as:
- automatic lyric fetching
- search and discovery functions for finding new music
- mix creation (using youtube automatic mixes for songs) to find music similar to other music you have
- Android app with offline support

Source: https://github.com/benkaiser/stretto
Android companion app source: https://github.com/benkaiser/stretto-mobile-next
My hosted version publicly available: https://next.kaiserapps.com/
The version of the app in the app store that links to my instance: https://play.google.com/store/apps/details?id=com.strettomobilenext.release

**Comment by worldworm** [comment]
@benkaiser greate Project.
But I cannot find any License for this project.

**Comment by benkaiser** [comment]
Apologies, it's listen in the package.json (MIT). I should add a LICENCE file and at the bottom of the README

**Comment by worldworm** [comment]
I totally missed the package.json. My mistake :)

**Comment by benkaiser** [comment]
@worldworm I've gone ahead and updated the license in the README and added a LICENSE file :+1:
