### ISSUE TITLE
Add Airsonic-advanced project

### ISSUE THREAD

**Issue by eharris** [awesome-selfhosted/awesome-selfhosted#1908]
The Airsonic project is already listed, but it would be nice to also include the Airsonic-advanced project which is an alternative fork with a faster development pace and some very nice enhancements that aren't yet available in the main project.

https://github.com/airsonic-advanced/airsonic-advanced
Free and Open Source community driven media server (fork of Airsonic which is itself of Subsonic and Libresonic)
Java/GPLv3

**Comment by 4oo4** [comment]
Nice, didn't know that existed. What enhancements does it have?

**Comment by watson387** [comment]
I'm curious too. I didn't see a list of differences. I host an Airsonic server at home and it's great. I'd consider switching if it has additional features.

**Comment by eharris** [comment]
Yeah the docs haven't really been updated to include differences yet.  The main big feature that most people would be interested in are:

https://github.com/airsonic-advanced/airsonic-advanced/pull/20

It also has been updated to Spring Boot 2 which comes with security and other improvements, and has had lots of other internal cleanups that improve the code quality, and more features are in the works.

**Comment by Rabenherz112** [comment]
As far as I can see, while there is some work going on, the last release was quite some time with no updates(2020), for example, the docker version of the software (and therefore quite some vulnerability https://github.com/airsonic-advanced/airsonic-advanced/issues/929). However, I found an actively maintained fork of this fork. https://github.com/kagemomiji/airsonic-advanced . However, in this fork, I couldn't find any install Instructions.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
