### ISSUE TITLE
Add Solr/Elasticsearch

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#1911]
From https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1866

```
 - [Apache Solr](https://lucene.apache.org/solr/) - Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene. ([Source Code](https://lucene.apache.org/solr/downloads.html)) `Apache-2.0` `Java` 
- ...
```

Add them under a new subsection of Search Engines (eg. Enterprise search engines or something similar)

**Comment by nodiscc** [comment]
Related to https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1910

**Comment by ImprovedTube** [comment]
hi

**Comment by nodiscc** [comment]
Solr was added in https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3003

Elasticsearch is under the SSPL license which is non-free (see https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2689), so if it is ever added, it should go to `non-free.md`. The [OpenSearch](https://en.wikipedia.org/wiki/OpenSearch_(software)) fork is still unde `Apache-2.0` license so it could be added instead.

Closing
