### ISSUE TITLE
Add errbit, the Airbrake API-compatible error catcher

### ISSUE THREAD

**Issue by steakknife** [awesome-selfhosted/awesome-selfhosted#1936]
Website: https://errbit.com

Source: https://github.com/errbit/errbit

License: MIT

**Comment by worldworm** [comment]
What do you think about:
- [Errbit](https://errbit.com) - Collecting and managing errors from other applications. Errbit is Airbrake API compliant. ([Source Code](https://github.com/errbit/errbit)) `MIT` `Ruby`

But I'am not sure about the category. Does "Analytics" fit the best?
I think "Bug Trackers" (which transfers to "Ticketing") does not fit.

**Comment by abdansyakuuro** [comment]
> What do you think about:
> - [Errbit](https://errbit.com) - Collecting and managing errors from other applications. Errbit is Airbrake API compliant. ([Source Code](https://github.com/errbit/errbit)) `MIT` `Ruby`
> 
> But I'am not sure about the category. Does "Analytics" fit the best?
> I think "Bug Trackers" (which transfers to "Ticketing") does not fit.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
