### ISSUE TITLE
Add Yazz Pilot, a self hosted web IDE

### ISSUE THREAD

**Issue by yazz** [awesome-selfhosted/awesome-selfhosted#1939]
https://github.com/zubairq/pilot

**Comment by KieranRobson** [comment]
Yazz seems to be a decentralised app store now

**Comment by KieranRobson** [comment]
The above source code links to https://github.com/yazz/yazz, a decentralised appstore rather than IDE

**Comment by fbartels** [comment]
The self description says "Yazz is a decentralised app store, which allows you to build Web apps visually." so maybe rather than a general tool, it's only an ide for this specific product.

**Comment by yazz** [comment]
Yes true, it is not a general purpose IDE. The IDE is only used for building Yazz applications

**Comment by KieranRobson** [comment]
What is a 'Yazz App'

**Comment by yazz** [comment]
Yazz Apps is a company behind the project

**Comment by abdansyakuuro** [comment]
> The self description says "Yazz is a decentralised app store, which allows you to build Web apps visually." so maybe rather than a general tool, it's only an ide for this specific product.

**Comment by yazz** [comment]
Yazz is the tool that lets you build apps, but most apps are compiled to a HTML file, with no dependency on the Yazz IDE at all

**Comment by yazz** [comment]
But yes, Yazz only lets you edit Yazz app :)

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
