### ISSUE TITLE
add sharetribe e-com

### ISSUE THREAD

**Issue by agilealpha1** [awesome-selfhosted/awesome-selfhosted#1942]
https://github.com/sharetribe/sharetribe

**Comment by KieranRobson** [comment]
Present in Non-free:

[Sharetribe](https://www.sharetribe.com) - Open-source platform to create your own peer-to-peer marketplace, also available with SaaS model. ([Source Code](https://github.com/sharetribe/sharetribe)) `⊘ Proprietary` `Ruby`

This issue can be closed
