### ISSUE TITLE
Move analytics category to onurakpolat/awesome-analytics

### ISSUE THREAD

**Issue by jtagcat** [awesome-selfhosted/awesome-selfhosted#2024]
https://github.com/onurakpolat/awesome-analytics

Should we move analytics there and link to it? Should we not? Other discussion?

**Comment by nodiscc** [comment]
@jtagcat I think it is a good idea but we would have to coordinate with @koconder who maintains the repository

- [ ] link to https://github.com/onurakpolat/awesome-analytics from our analytics section
- [ ] submit every item from https://github.com/awesome-selfhosted/awesome-selfhosted#analytics there in separate pull requests for review
- [ ] Remove items that have been merged, from awesome-selfhosted

It can be done, has been done before with https://github.com/n1trux/awesome-sysadmin and (https://github.com/awesome-selfhosted/awesome-selfhosted/issues/127, https://github.com/awesome-selfhosted/awesome-selfhosted/issues/216...)

If you are willing to start sending Pull Requests to https://github.com/onurakpolat/awesome-analytics (and if @koconder agrees), we can start tracking this work here. I have pasted the task list in your original report so we can both edit it

**Comment by jtagcat** [comment]
Since @koconder got mentioned, they got a notification. I'll wait and see if they show up here. Otherwise, I think I'll probably do it.

**Comment by koconder** [comment]
@jtagcat  @nodiscc im happy to approve the PR's for these changes. Just let me know when its ready 👍

**Comment by nodiscc** [comment]
@jtagcat @koconder if you want to start migrating https://github.com/awesome-selfhosted/awesome-selfhosted#analytics to https://github.com/onurakpolat/awesome-analytics, fire away

The todo list is above, proceed as you like

**Comment by jtagcat** [comment]
I'll try to get everything done by next week, though can't guarantee anything, fires, technical emergencies don't warn you ahead.

Here's stats on around ¼ to ⅓ of my backlog:

![image](https://user-images.githubusercontent.com/38327267/95022666-2f9b3b80-0668-11eb-960c-0ae035963039.png)

**Comment by jtagcat** [comment]
Ok, PRs done. Interesting, that GH doesn't say 'this issue was linked from x' in this issue.

If it was GL, I'd done all in one commit.. I'd suggest merging the pulls in order.

I have a general idea around the analytics sections, I'd organize it better (half of it is 'general') after everything is merged.

**Comment by nodiscc** [comment]
> I'd suggest merging the pulls in order.

Yes I should have :) I merged the last commit first, then had to resolve merge conflicts for the next 6 patches. Easy, but then

![image](https://user-images.githubusercontent.com/3950390/95489472-75b50f80-0986-11eb-9094-02508d323fa7.png)

Many thanks for working on this. I added awesome-analytics to https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/PULL_REQUEST_TEMPLATE.md

While merging https://github.com/onurakpolat/awesome-analytics/pulls, can you preserve information that these tools are [Free/libre](https://en.wikipedia.org/wiki/Free_software#Definition_and_the_Four_Essential_Freedoms_of_Free_Software)? I (and others) would be primarily looking for software that I have control on (especially important in the context of analytics which process sensitive/personal data).

Not necessarily keep the exact language/license tags, but add a symbol like `⓿` next to them(for example look at [awesome-linuxaudio](https://gitlab.com/nodiscc/awesome-linuxaudio) which contains both free/non-free tools)

Thanks again

**Comment by nodiscc** [comment]
https://github.com/onurakpolat/awesome-analytics/pull/84#issuecomment-719590482

**Comment by koconder** [comment]
@nodiscc @jtagcat i merged the first PR, second shows a merge conflict

**Comment by jtagcat** [comment]
Stuff is merged!
I'll try to organize the stuff over at awesome-analytics at some time, but am out of time at this time. See jtagcat/jtagcat.

**Comment by razvanilin** [comment]
Is there a reason why this section was moved to another repo? 🤔 From what I can see, all the sections have products in them except Analytics which looks a bit strange

**Comment by jtagcat** [comment]
> Is there a reason why this section was moved to another repo? thinking From what I can see, all the sections have products in them except Analytics which looks a bit strange

As that repo is more in scope. Search for 'see' in the readme. For example VPNs and webservers.

**Comment by nodiscc** [comment]
@razvanilin several sections had already been delegated to https://github.com/n1trux/awesome-sysadmin, we extended this to the `Analytics` section (to https://github.com/onurakpolat/awesome-analytics). If a well-maintained, specialized list already exists for a given topic, there is no point in duplicating efforts.

I reported https://github.com/onurakpolat/awesome-analytics/issues/93 and https://github.com/onurakpolat/awesome-analytics/issues/94 which would greatly improve awesome-analytics.

**Comment by luckydonald** [comment]
I just checked out the link to awesome analytics, and it took me a while to figure out that those are no longer self hosted.

So basically it's "hey have fun looking through a list which isn't self hosted for the most, good luck finding the 3 self hosted ones".
For now, linking to https://github.com/nodiscc/awesome-analytics/tree/saas-nonfree-indicator makes more sense, or at least a warning.

**Comment by nodiscc** [comment]
> it doesn't seem to be any keyword like selfhosted to reliable search for.

I added a comment  on https://github.com/0xnr/awesome-analytics/issues/111#issuecomment-1113186205 (searching for self-hosted entries should be possible now)

Once https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038 lands (soon...) it should be possible to re-import the items that were moved to awesome-analytics (https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/7)

**Comment by nodiscc** [comment]
The move to awesome-analytics has been reverted https://github.com/awesome-selfhosted/awesome-selfhosted#analytics (https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3575)
