### ISSUE TITLE
Another awesome sublist would be browser ie: "client side hosted" web applications

### ISSUE THREAD

**Issue by bacloud14** [awesome-selfhosted/awesome-selfhosted#2029]
All in title..
Some JS applications like games, visualization tools, or tool exploration (JS library experimenting), does not initiate any connection to the internet, even if hosted in the web, it is totally independent when loaded in client side.
I would like to see a list of these. Let me know please if this is interesting ?

**Comment by fbartels** [comment]
Do you know such applications?

**Comment by bacloud14** [comment]
I do not have a list of applications now. But I came across many.
Something like this: https://everytimezone.com/?t=5e77fc00,591
HTML5 or HTML empowered with JS.

**Comment by drawkula** [comment]
https://tiddlywiki.com/

**Comment by bacloud14** [comment]
> https://tiddlywiki.com/

very nice example!

**Comment by drawkula** [comment]
WebREPL client for MicroPython - https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2029

Maybe a bit too special. But then it can help to define the line between which "apps" should be in tha list or no and why...

**Comment by nodiscc** [comment]
If the application runs client side (static HTML/CSS/JS), but can be hosted on a simple web server/accessed through the network, it is fine to add it here (basic building blocks such as JS libraries that don't provide a  ready to use, user-facing application don't qualify, rather check https://github.com/sorrycc/awesome-javascript).

Tiddlywiki is pure client-side JS, but it's a full application, you can drop it on a basic web server and use it through a standard Web browser, so it is ok - it's already listed in [wikis](https://github.com/awesome-selfhosted/awesome-selfhosted#wikis)

> https://github.com/micropython/webrepl
> accessing a MicroPython REPL (interactive prompt) over WebSockets

If you can find the server-side software that runs the prompt/shell this connects to, it would probably qualify. Couldn't find it at https://github.com/micropython/.

**Comment by drawkula** [comment]
I think I have run both even from a file: URL. But it is long ago.

The server side of the micropython/webrepl is part of micropython and runs on the micropyton-ised microcontroller. Think of it like telnet: to the MCU over a websocket.

**Comment by nodiscc** [comment]
maybe micropython would fit in the IoT section? I don't know

As said before, https://github.com/sorrycc/awesome-javascript for js frameworks, libraries, ... is the place to go. JS/client side applications that can be hosted on a web server are welcome here.

Please open an issue if you are uncertain about a particular application :+1:
