### ISSUE TITLE
Add "Pretend you're XYZZY"

### ISSUE THREAD

**Issue by TheConanRider** [awesome-selfhosted/awesome-selfhosted#2034]
Pretend you're XYZZY is a web based Cards against humanities clone. Recently (possibly due to COVID-19) their severs have been hit by a huge wave of traffic so I for a self hosted option and they're open source and they have a docker image.

(if you're using the docker image use "dev" I couldn't get "run" to work)
https://github.com/ajanata/PretendYoureXyzzy

**Comment by 4oo4** [comment]
That looks fun, but it also looks like it's unmaintained? The last commit was a couple years ago, however at least it's using a version of Tomcat that's still maintained.

**Comment by TheConanRider** [comment]
The dev is still adding servers to the official site so I assume development for the game has become stagnent but the life of the game hasn't. If support was completely lost I could imagine someone quickly picking it back up.

**Comment by KieranRobson** [comment]
Last commit of 2020 and no issues since then either 

This issue could be closed
