### ISSUE TITLE
Suggestion to remove Tracks from Task management/To-do lists

### ISSUE THREAD

**Issue by coridonhenshaw** [awesome-selfhosted/awesome-selfhosted#2054]
The Tracks tool, listed under Task management/To-do lists, is currently unusable because the installation process does not work. I suggest the entry should be removed from the listing until/unless upstream fixes things.

**Comment by nodiscc** [comment]
You reported the documentation problem 8 days ago.... https://github.com/TracksApp/tracks/issues/2372 ... give them some time.

**Comment by ericmoon** [comment]
Install does work fine.  I've done it both the 'traditional' way and via docker.  No reason to remove from the list.

**Comment by phlummox** [comment]
It does not even remotely "work fine", unless you're looking at a very different set of install instructions to the ones I'm seeing [here](https://github.com/TracksApp/tracks/blob/master/doc/installation.md). 

I ran into the same problems as @coridonhenshaw, and it's obvious the problem with out-of-date documentation still has not been addressed. I'd say Tracks is certainly not usable by a non-Ruby developer as it stands.

However, I've suggested a working Docker instance might help, and have made a start on the steps needed in it, so we'll see if anyone takes up that suggestion.

**Comment by phlummox** [comment]
Ugh. And even if you install extra packages in response to build errors, and trawl through various Github Issues to find fixes for runtime errors, when you *do* get it running, it [looks like utter ass](https://raw.githubusercontent.com/gist/phlummox/10e3129d2a47c60c81409f2540b80939/raw/e01277f323f64cb2dd7be45ad34c662f102d7c97/tracks-screenshot.svg) :(

Oh well, that's three hours of my life I'll never get back. C'est la vie.

**Comment by mattr-** [comment]
Just remove it from the list. The project isn't being maintained any longer.

**Comment by fbartels** [comment]
Indeed the repo has been officially archived: 

https://github.com/TracksApp/tracks

**Comment by ZeiP** [comment]
I took over the project and de-archived the repository. I'll try to take a look at the installation documentation and update the instructions – I haven't done a fresh install for a while now and haven't used the Docker side of the project so far, but it should be doable.

**Comment by ZeiP** [comment]
There are now better installation instructions for the master branch in https://github.com/TracksApp/tracks/blob/master/doc/installation.md. I'm planning on releasing a new version after getting at least the library updates in, but it'd be awesome to have some feedback before the release. I will also be adding a ready-to-use Docker image to Docker Hub once I get access to the organisation.

I suggest closing this issue down, as the software should in the current state of the master branch be usable with the instructions provided. Let me know if you encounter any problems by posting a new issue in the project issue queue. Thanks!

**Comment by nodiscc** [comment]
Got it, thanks for maintaining this project. You could change the language/platform to `Ruby/Docker` if you want, since a docker-based installation is apparently supported.
