### ISSUE TITLE
xandikos doesn't support WebDAV

### ISSUE THREAD

**Issue by clach04** [awesome-selfhosted/awesome-selfhosted#2062]
https://www.xandikos.org/ does not mention WebDAV and https://www.xandikos.org/standards.html explicitly lists core WebDAV compliance as not implemented

**Comment by nodiscc** [comment]
Please send a patch removing mention of WebDAV from the Xandikos entry

**Comment by nodiscc** [comment]
I just saw it, https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2063, than you, merged.
