### ISSUE TITLE
New health/medicine section [discussion]

### ISSUE THREAD

**Issue by klmhsb42** [awesome-selfhosted/awesome-selfhosted#2073]
Thanks for the nice project. There are some projects in the health segment https://en.wikipedia.org/wiki/List_of_open-source_health_software which might be missing. Like OpenMRS, OpenEMR, etc. would be nice if you could add this...

**Comment by virtadpt** [comment]
That would be very helpful, especially now.

**Comment by rosenvik** [comment]
Thank's 🙂

**Comment by Miaosur** [comment]
- [x] 嗯

**Comment by nodiscc** [comment]
I think `Baby Buddy` and `Mere Medical` are good candidates for a new `Health & Medicine` section. But the [contribution guidelines](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/PULL_REQUEST_TEMPLATE.md) state:

>  Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into Misc/Other.

So 1 more item is needed to warrant creating a new section. Feel free to review and add web applications listed at https://en.wikipedia.org/wiki/List_of_open-source_health_software, and create the new section.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this issue worked on, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
