### ISSUE TITLE
Update Cozy : delete mail mention

### ISSUE THREAD

**Issue by Deeoon** [awesome-selfhosted/awesome-selfhosted#2077]
Cozy no longer offers a mail system
But it now offers a system for retrieving banking information and budget management.

**Comment by nodiscc** [comment]
@Deeoon can you send a pull request to fix the Cozy entry? The process is described [here](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md). Let me know if you need more guidance

**Comment by nodiscc** [comment]
Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2079
