### ISSUE TITLE
Cerb should be listed in non-free section

### ISSUE THREAD

**Issue by acuteaura** [awesome-selfhosted/awesome-selfhosted#2081]
The license for wgm/cerb seems to not fit any description of a free or open source license, as it explicitly prevents you from removing the DRM (license server / commercial for more than one seat)

>* **Modification and Redistribution of Derivative Works** - You are permitted to produce and distribute modifications to this software provided that the following conditions are met:
>      [...]
> 	* You are not permitted to produce or disseminate any technology or modifications to this software or source code which circumvent its digital copyright protection or interfere with the enforcement of per-seat licensing.
>	* This software must remain compatible with digital software licenses authorized and issued exclusively by Licensor.

https://github.com/cerb/cerb-release/blob/master/LICENSE

It should therefore be moved to the non-free section.

**Comment by nodiscc** [comment]
@schittler thank you for noticing and letting us know. Can you send a pull request to move cerb to non-free.md?
