### ISSUE TITLE
Add Eventyay/OpenEvent to Conference Management

### ISSUE THREAD

**Issue by Forger125** [awesome-selfhosted/awesome-selfhosted#2094]
OpenEvent (the backend behind Eventyay) is a project out of FOSSASIA designed to fill the role of things like Eventbrite, specifically designed at the conference/event planning market. Seems like it would be a good addition!

- [Site](https://eventyay.com/)
- [Blog](https://blog.fossasia.org/tag/open-event/)
- [Source](https://github.com/fossasia/open-event-server)

**Comment by KieranRobson** [comment]
This issue can be closed, already present within https://github.com/awesome-selfhosted/awesome-selfhosted#polls-and-events
