### ISSUE TITLE
Update/Change GNU Social Repo

### ISSUE THREAD

**Issue by BeaverTek** [awesome-selfhosted/awesome-selfhosted#2106]
The current GNU Social repo is at: https://notabug.org/diogo/gnu-social
It's under active development. V2 will be out soon and v3 is being worked on.

**Comment by SuperSandro2000** [comment]
https://gnu.io/social/ points to https://git.gnu.io/gnu/gnu-social/-/issues which throws a 500. You know what is correct?

**Comment by BeaverTek** [comment]
The original creator / lead dev of GS, mattl, abandoned the project long ago. The new Project Lead is Diogo. He, along with a few others, are mentoring students currently as part of the G. Summer of Code. Diogo's in touch with the folks at GNU.
Current Stable is v1.20.9

Official IRC
server: freenode 
room: #social 

Official unofficial XMPP MUC
server: conference.bka.li
room: gnusocial


Oh, I see what you mean SuperSandro. 
https://git.gnu.io/gnu/gnu-social/
that's the correct link. Follow the first link on the gnu.io/social or simply take the hyphen out.

**Comment by BeaverTek** [comment]
Sorry, I seem to have failed to mention that the main / currently actively maintained homepage for the site is: https://gnusocial.network
