### ISSUE TITLE
Remove Polar Bookshelf

### ISSUE THREAD

**Issue by lyz-code** [awesome-selfhosted/awesome-selfhosted#2135]
I think that Polar bookshelf, belonging to the E-books and Integrated Library Systems (ILS) category, should be removed from this repository or at least flagged with a big warning.

The project has deviated quite fast from the self hosted, privacy and free software principles throughout these years.

It all started when the project shifted their approach from the desktop client to a web application that [couldn't be self hosted](https://github.com/burtonator/polar-bookshelf/issues/1155) by the users themselves. Then it got worse with the progressive drop of Anki support. Yesterday the main developer stated in the [2.0 release](https://www.reddit.com/r/PolarBookshelf/comments/ha7jy1/polar_20_beta_release_and_general_update/) the following:

> The local 'disk' datastore, (the .polar directory) where we keep local data will be going away in favor of keeping all data in the cloud.
> When you login to 2.0 for the first time, we will detect that you have a .polar directory and import your data for you so that you can keep using 2.0.
>
> CONS:
> * Cloud is required. There will be no way to use Polar without cloud.
> * Users who were using the on disk data as an API won't be able to access it for that use case anymore.

So now to use polar you need to use their web paid service and there is no way to prevent your documents to be uploaded to their cloud. Despicable...

We can still use the 1.X versions of the software, but no development should be expected.

I don't mind doing a PR with the outcome of this issue discussion.

**Comment by nodiscc** [comment]
> The local 'disk' datastore, (the .polar directory) where we keep local data will be going away in favor of keeping all data in the cloud

Can the "cloud" (whatever that means...) part of the software be self-hosted? If yes, is it Free Software?

If not, Polar Bookshelf can be removed.

**Comment by lyz-code** [comment]
> Can the "cloud" (whatever that means...) part of the software be self-hosted?

As of today no it can't. The developer doesn't give the opportunity to self-host your own application with the argument that it's heavily focused in Google Firebase (though people that want to self host it could use that service).

Nevertheless, he is open to PR to add other storage backends. But he hasn't received many external collaborations as of today. 

I'm keeping an eye on the program development, and if I see that this requirement is met, I'll do another PR to add it back again.
