### ISSUE TITLE
HyperKitty, Postorius

### ISSUE THREAD

**Issue by darkdragon-001** [awesome-selfhosted/awesome-selfhosted#2145]
Please add [HyperKitty](https://wiki.list.org/HyperKitty) ([docs](https://hyperkitty.readthedocs.io/en/latest/), [source](https://gitlab.com/mailman/hyperkitty)) as _Mailman archiver_ and Postorius ([docs](https://docs.mailman3.org/projects/postorius/en/latest/), [source](https://gitlab.com/mailman/postorius/)) as _Mailman Web UI_. Should it go into _mailing lists_ section? As a sub-list of _Mailman_?

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2274
