### ISSUE TITLE
Add YiNote browser extension

### ISSUE THREAD

**Issue by shuowu** [awesome-selfhosted/awesome-selfhosted#2146]
YiNote is a browser extension to help users to take timestamped notes while watching videos. 

GitHub link: https://github.com/shuowu/yi-note
Website: https://www.yinote.co
Chrome web store: https://chrome.google.com/webstore/detail/yinote/fhpgggnmdlmekfdpkdgeiccfkignhkdf

Category: 
* Bookmarks and Link Sharing
* Note-taking and Editors

**Comment by nodiscc** [comment]
> a browser extension

> This is a list of Free Software network services and web applications which can be hosted locally.
