### ISSUE TITLE
Section of (Game-)Hostingpanel

### ISSUE THREAD

**Issue by smilebasti** [awesome-selfhosted/awesome-selfhosted#2152]
Hi,
i would like to see a section in this list of selfhosted Controllpanels for example: 
ISPConfig3 or for Games Pterodactyl.

I think this would be a great addition because it helps in Hosting multiple instances of websites or Games.
Maybe call it Hosting and Controll Panels. This would also be a place for YunoHost or HomelabOS. 

Cloudron could maybe also be added as it offers a great managed Docker Controll (2 Container are free).

**Comment by KieranRobson** [comment]
This issue could be closed due to PR #3048
