### ISSUE TITLE
Inquiry About the Microservice Architecture Employed by `awesome-selfhosted`

### ISSUE THREAD

**Issue by research-sudo** [awesome-selfhosted/awesome-selfhosted#2167]
I am a researcher investigating the open source projects that are designed by the microservice architectural style (https://martinfowler.com/microservices/). My preliminary investigation shows that the **_awesome-selfhosted_** project (https://github.com/awesome-selfhosted/awesome-selfhosted) is designed by the microservice architectural style.

Can you please **_confirm_** if my interpretation that this project is designed by following the microservice architectural style is correct? Note that if the projects (e.g., frameworks or tools) support the development of microservices-based systems but themselves are not designed by following the microservice architectural style, please also clarify it?
If my interpretation is correct, what **_features_** or **_characteristics_** of the architecture of this open source project show that the microservice architectural style has been used?
**Optional Question:** Do you know any other open-source projects that are designed by following the microservice architectural style?
I would be greatly appreciative if you can kindly answer the three questions above.

**Comment by nodiscc** [comment]
reported as spam
