### ISSUE TITLE
Add papercups

### ISSUE THREAD

**Issue by cheeseblubber** [awesome-selfhosted/awesome-selfhosted#2176]
https://github.com/papercups-io/papercups
papercups.io

Papercups is a self hosted chat-based customer engagement app. Papercups is an open sourced Intercom alternative.

**Comment by Pe46dro** [comment]
@nodiscc this issue can be closed

**Comment by nodiscc** [comment]
Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2176

Thanks
