### ISSUE TITLE
Add Isotope Mail client

### ISSUE THREAD

**Issue by ArunJRK** [awesome-selfhosted/awesome-selfhosted#2177]
Found this Iotope mail client on Github based on Node JS and there is a Docker Version also. This is a stateless needing no storage. 

[Github Repo](https://github.com/manusa/isotope-mail)
[Docker Image](https://hub.docker.com/r/marcnuri/isotope/)

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2274
