### ISSUE TITLE
Please add implemented language in side brackets

### ISSUE THREAD

**Issue by kaushalyap** [awesome-selfhosted/awesome-selfhosted#2179]
It is better implemented language shown beside the name, so people can pick software which are written in their preferred language.
May be build simple website including following info would be very useful

- implemented language
- tech stack
- No. stars
- No. contributors
- Last commit date with active or abandoned.

**Comment by worldworm** [comment]
Take a look at this great project:
https://github.com/n8225/awesome-selfhosted-gen
https://n8225.github.io/awesome-selfhosted-gen/

**Comment by kaushalyap** [comment]
I'll close this in favor of @worldworm 's suggestion.
