### ISSUE TITLE
Add Servediter for connecting to Code Server instances

### ISSUE THREAD

**Issue by ntindle** [awesome-selfhosted/awesome-selfhosted#2186]
Not sure if this is allowed. Servediter is an app I found that allows you to hook into Code Server Instances. It is not self hosted nor open source itself but is a very useful tool that should be mentioned alongside Code Server

**Comment by nodiscc** [comment]
> Not sure if this is allowed  
> It is not self hosted nor open source

I think you have your answer :) Thanks for mentioning it nevertheless
