### ISSUE TITLE
Suggestion: Would it be good to integrate the live-stars to every repo. 

### ISSUE THREAD

**Issue by MaheshB0ngani** [awesome-selfhosted/awesome-selfhosted#2219]
Something like this. https://github.com/anuraghazra/github-readme-stats#demo

**Comment by nodiscc** [comment]
This works in https://n8225.github.io/awesome-selfhosted-gen/, we hav no way to do ti directly in the markdown document. See https://github.com/n8225/awesome-selfhosted-gen/issues and https://github.com/n8225/awesome-selfhosted-gen/issues for the remaining work on the website

**Comment by MaheshB0ngani** [comment]
That's awesome. Thank you.
