### ISSUE TITLE
Hastebin has been abandoned. Please direct people to the updated fork

### ISSUE THREAD

**Issue by twiclo** [awesome-selfhosted/awesome-selfhosted#2225]
seejohnrun/haste-server has been abandoned and it looks to me like https://github.com/zneix/haste-server is the best fork out there. Could we maybe update the list to direct people to this updated repo?

**Comment by nodiscc** [comment]
The forks looks to have some recent maintenance yes, however the original has some long-standing issues (https://github.com/seejohnrun/haste-server/issues) and some (apparently) security-related ones. So the original has the advantage of making them visible to the prospective user...

seejohnrun/haste-server should definitely be removed in the current state. However I don't know about the fork... @twiclo @zneix what do you think about these solutions? Either:
 - Ask @seejohnrun to transfer ownership of the original repo to you, if you intend to maintain it
 - If not possible then copy the original repo's issues to yours, ... but the first solution would be preferable. Don't let a good project go to waste

**Comment by zneix** [comment]
Hey @nodiscc, I started modifying haste just to resolve numerous dependency issues but I noticed I can upgrade its very old code and I still have some ideas in my mind to expand original repo by adding, for example deletion support or rewriting frontend to get rid of old jquery.
I don't have all the time in the world, but I intend to keep providing support to my fork and adding features I have in my mind.

I will try contacting seejohnrun, but I have a feeling I can't just take someone's repo and pin it under my name.
About copying issues, I can make one megathread of most/all relevant issues that might be useful to implement and start working on them.

**Comment by twiclo** [comment]
https://twitter.com/ALazyMeme/status/1298257725143437320

**Comment by alazymeme** [comment]
More than happy to help out moving all the issues over. Don't see why a deprecated repo should be promoted that has security vulnerabilities and people waiting to contribute to contribute that are being ignored.

Poor form imo - even if I don't hold a github employee to a higher standard.

**Comment by twiclo** [comment]
I believe @zneix fixed the security flaws already

**Comment by zneix** [comment]
Yes I did, I believe alazymeme meant upstream repo, not my fork 😄

**Comment by nodiscc** [comment]
No response from @seejohnrun? If so, you may send a PR to replace the original hastebin with your fork

**Comment by Space-Walrus** [comment]
pajaS 🐍  Sneix
