### ISSUE TITLE
Add Yacht to Self-hosting Solutions sections.

### ISSUE THREAD

**Issue by SelfhostedPro** [awesome-selfhosted/awesome-selfhosted#2226]
Yacht is a container management interface with a focus on templating to enable a kind of distributed "App Store" for servers. I'd be happy to submit a PR but wanted to make sure it fits in with what you want to have here especially since it's still in pre-alpha.

https://github.com/SelfhostedPro/Yacht

**Comment by SelfhostedPro** [comment]
Yacht has entered alpha status if that changes anything.

**Comment by kokomo123** [comment]
This should be closed as it's already been put in awesome-foss/awesome-sysadmin list.
