### ISSUE TITLE
Change License for Sharetribe

### ISSUE THREAD

**Issue by razorinc** [awesome-selfhosted/awesome-selfhosted#2283]
Howdy, 

Sharetribe license got changed in 2019, https://github.com/sharetribe/sharetribe/commit/4ec8bf0cb4a55ce2bfe7daaa6fa2bfb0227dc5a7 not sure which kind of license is that and if is OSI compatible.
I'm willing to change it, but I am not sure how to tag it. Ideas?

**Comment by nodiscc** [comment]
https://github.com/sharetribe/sharetribe/blob/master/LICENSE

Everything looks OSI-compatible (including reasonable trademark/attribution clauses), except this restriction:

> The licensed rights exclude the right to make the Software available as a software-as-a-service or platform-as-a-service where You host the Software for multiple clients or other similar online services that compete with Sharetribe products or services that provide the Software (“Excluded Purpose”).

So it is not respecting Freedom 0: The freedom to run the program for any purpose.

I think it should be moved to non-free.md.

@razorinc thanks, can you send a patch to move Sharetribe to the non-free list?

**Comment by razorinc** [comment]
@nodiscc Sure thing! With much pleasure!

**Comment by razorinc** [comment]
@nodiscc it is missing something my commit?
