### ISSUE TITLE
Remove 2 apps?

### ISSUE THREAD

**Issue by mzch** [awesome-selfhosted/awesome-selfhosted#2287]
1. [Kandan](https://github.com/kandanapp/kandan) has been inactive since 2015. All issues have been also left since 2015.
1. [droppy](https://github.com/silverwind/droppy) has not been developed. The repository has been already archived.

I think these should be removed.

**Comment by nodiscc** [comment]
@mzch thanks, can you send a patch to remove these?

**Comment by kokomo123** [comment]
Fixed! 👍🏻
