### ISSUE TITLE
Remove BoostNote

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#2303]
Followup to https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2265

It's a desktop application, it saves to files (which can be synchronized between machines using a self-hosted file sync solution) but does not involve self-hosting.

**Comment by mzch** [comment]
I agree. BoostNote becomes a desktop app now. I also think it's not self-hosted.

**Comment by adan89lion** [comment]
What about Joplin? It is also a standalone software (operates locally) with optional sync to self-hosted solutions.

**Comment by nodiscc** [comment]
I just checked Joplin again, yes it is a desktop application with optional sync features, it should be removed

**Comment by gorgobacka** [comment]
> I just checked Joplin again, yes it is a desktop application with optional sync features, it should be removed

Since a few weeks, Joplin has it's own server implementation. See here:
- https://discourse.joplinapp.org/t/joplin-web-api-for-nextcloud/4491/72?u=laurent
- https://github.com/laurent22/joplin/pull/1872

I think, it is not well documented yet.

**Comment by mzch** [comment]
Until today new Boost Note hasn't been self-hosted. Some users request a self-hosted option (https://github.com/BoostIO/BoostNote-App/discussions/1232). But the developer told that cloud space isn't mature enough to provide the self-hosted codes. (https://github.com/BoostIO/BoostNote-App/issues/863).

I think BoostNode should be removed from ths list temporally until it's self-hostable. If no one has no objection, I'd like to create PR for it.

**Comment by mzch** [comment]
Just created PR #2700.
