### ISSUE TITLE
Remove Confluence from non-free List

### ISSUE THREAD

**Issue by benvei** [awesome-selfhosted/awesome-selfhosted#2309]
Hi,

please remove Confluence from the non-free list. Unfortunatly Atlassian decided to stop selling licenses in 02/2021 and drop support a few years later. Source: https://www.atlassian.com/licensing/purchase-licensing

Thanks!

**Comment by nodiscc** [comment]
@benvei can you send a patch to remove confluence from non-free.md?

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2419
