### ISSUE TITLE
Add SyncMarks

### ISSUE THREAD

**Issue by Offerel** [awesome-selfhosted/awesome-selfhosted#2360]
I have created a crossbrowser bookmark sync tool for Firefox and Chromium based browsers, including Kiwi on Android. There is an AddOn for the browser (not in Chrome store, must installed there via Sideload) and 2 variants for the backend. There you can use either a simple WebDAV share or a PHP backend. I recommend the later.

AddOn is available from [SyncMarks-Extension](https://github.com/Offerel/SyncMarks-Extension) and the backend at [SyncMarks-Backend](https://github.com/Offerel/SyncMarks-Webapp).

**Comment by Rabenherz112** [comment]
It looks unmaintained, with [SyncMarks-Backend](https://github.com/Offerel/SyncMarks-Webapp) not existing anymore, the Extension itself not anymore available in the [Firefox AMO](https://addons.mozilla.org/en-US/firefox/addon/davmarks/), and no commit since 8 Months.

**Comment by Offerel** [comment]
Thats not true. Its maintained. I have moved all repos to Codeberg. The Extension is at https://codeberg.org/Offerel/SyncMarks-Extension and the backend at https://codeberg.org/Offerel/SyncMarks-Webapp. The Extension is also live in AMO https://addons.mozilla.org/firefox/addon/syncmarks/ and for Edge https://microsoftedge.microsoft.com/addons/detail/syncmarks/ffobakhdlfhmnnkmimkbnbmnplihhphg
