### ISSUE TITLE
New section for software with self-hosted storage sync

### ISSUE THREAD

**Issue by adan89lion** [awesome-selfhosted/awesome-selfhosted#2375]
An idea following #2302 .

Note-taking softwares like Boost Note, DNote and Joplin are standalone applications so they should be removed from this list. But they can still involve self-hosted services (like syncing), and is valuable to the self-hosting community.

A more complicated example is Standard Notes. It consists of two servers : Standard Notes Syncing Server and its web frontend. But you can host nothing and use only the Standard Notes app from your Android / iOS phone without syncing features.

So I've been thinking about adding a section in `File Sharing and Synchronization` or a brand new `Companion Tools` section. And we can include productivity software mentioned above and software / apps like password managers or photo backup apps so people with self-hosted storage (like SFTP, WebDAV server or NextCloud instance) can have more options and hosting ideas.

I'm looking forward to other ideas, thanks.

**Comment by jarrettv** [comment]
It would be nice to explain these types of things up front. I'd like some sort of indicator how easy it is to docker-compose up and then nginx proxy manager each one. I've wasted so much time trying out some of the options that are not friendly to this setup. 

Self-hosted packages that have wasted my time: Pydio, BookStack, NextCloud. It seems like solutions that try to include their own reverse proxy make things more difficult. Anytime you must supply `APP_URL` or `HOST_URL` or `EXTERNAL_URL` it is a red flag that it will be harder than it should be to self host.

**Comment by josephhernandezphd** [comment]
I haven’t had any problems with running bookstack and nextcloud using a reverse proxy and docker-compose.  The issue is what implementation, how to generate the configuration file and when to mount a cert. I can share if you are still interested in running them.

**Comment by nodiscc** [comment]
It would have to be a separate project/list, and we can link to it from here. But I don't really see the point:
- all software that uses file storage can obviously have its data synchronized through file sync
- there are already `Clients` links for software that comes explicitely with a companion app
