### ISSUE TITLE
Check https://apps.sandstorm.io/ for more software

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#238]
https://apps.sandstorm.io/

**Comment by evaryont** [comment]
This should be done soon, if it hasn't already been finished. Sandstorm the company is shutting down. It's unlikely to affect the community, and the purpose is specifically avoid interrupting the non-commercial users, but I get the feeling that sandstorm's model wasn't sustainable.

**Comment by nodiscc** [comment]
- [ ] wekan
 - [ ] etherpad
 - [ ] rocket.chat
 - [ ] davros
 - [ ] ethercalc
 - [ ] draw.io
 - [ ] filedrop
 - [ ] hacker slides
 - [ ] sandforms
 - [ ] quick survey
 - [ ] texteditor
 - [ ] permanote
 - [ ] brainstorm
 - [ ] idea otter
 - [ ] contact otter
 - [ ] giftr
 - [ ] go
 - [ ] gogs
 - [ ] dillinger
 - [ ] nodebb
 - [ ] etherdraw
 - [ ] meteor blocks
 - [ ] scrumblr
 - [ ] dokuwiki
 - [ ] hledgerweb
 - [ ] radicale
 - [ ] swaggereditor
 - [ ] hummingbird
 - [ ] mercurial
 - [ ] legends browser
 - [ ] cryptagsimple rich text editor
 - [ ] sandchat
 - [ ] hacker resume
 - [ ] sandpass
 - [ ] collections
 - [ ] neuron catalog
 - [ ] linksholder
 - [ ] simple chat
 - [ ] hakyll CMS
 - [ ] paperwork
 - [ ] gitweb
 - [ ] piwik
 - [ ] laverna
 - [ ] let's chat
 - [ ] browserquest
 - [ ] groove basin
 - [ ] sharelatex
 - [ ] framadate
 - [ ] ghost
 - [ ] ipython notebook
 - [ ] mediawiki
 - [ ] telescope nova
 - [ ] mediagoblin
 - [ ] game of Y
 - [ ] simple todos
 - [ ] lychee
 - [ ] acronymy
 - [ ] duoludo
 - [ ] hackerCMS
 - [ ] wordpress
 - [ ] tiny tiny RSS

**Comment by nodiscc** [comment]
Stale issue, feel free to open new issues for software listed here.
