### ISSUE TITLE
No-code / Low-code should be a category

### ISSUE THREAD

**Issue by joebudi** [awesome-selfhosted/awesome-selfhosted#2385]
I am the co-founder of [Budibase](https://github.com/Budibase/budibase) , and I feel with the emergence of no-code/low-code we need to promote the open-source projects within this category.

**Comment by nodiscc** [comment]
It should be a subseciton fo https://github.com/awesome-selfhosted/awesome-selfhosted#software-development

If you can find 3 items or more that fit this category, please create it
