### ISSUE TITLE
Gazelle is Free Software

### ISSUE THREAD

**Issue by markasoftware** [awesome-selfhosted/awesome-selfhosted#2400]
https://github.com/WhatCD/Gazelle/blob/63b337026d49b5cf63ce4be20fdabdc880112fa3/docs/COPYING.txt

I think it's GPLv2?

**Comment by nodiscc** [comment]
> - THE USE, DISTRIBUTION AND/OR MODIFICATION OF THIS SOFTWARE FOR
COMMERCIAL PURPOSES IS EXPRESSLY PROHIBITED
> - https://en.wikipedia.org/wiki/Free_software#Definition_and_the_Four_Essential_Freedoms_of_Free_Software
> - Freedom 0: The freedom to run the program for any purpose.
