### ISSUE TITLE
Add svelte-feed

### ISSUE THREAD

**Issue by ganochenkodg** [awesome-selfhosted/awesome-selfhosted#2410]
Please add [svelte-feed](https://github.com/ganochenkodg/svelte-feed) to [Blogging Platforms](https://github.com/awesome-selfhosted/awesome-selfhosted#blogging-platforms). It's a simple app for posting important information and links for home.

**Comment by Rabenherz112** [comment]
Hello there! From what I can see, it appears that this software is no longer being actively maintained. There haven't been any commits made since February 14, 2021.
