### ISSUE TITLE
Update Kimai

### ISSUE THREAD

**Issue by Wonno** [awesome-selfhosted/awesome-selfhosted#2428]
Kimai1 is not developed any more.
Also licence has changed to MIT with Kimai2

URL:  [https://www.kimai.org/](https://www.kimai.org/)
License: [MIT](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)
Language:  PHP

**Comment by Wonno** [comment]
PR: #2429

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2429 merged
