### ISSUE TITLE
Remove "Tipboard" and add "Smashing"

### ISSUE THREAD

**Issue by jeremymeyers** [awesome-selfhosted/awesome-selfhosted#2451]
Tipboard Hasn't been updated in several years and the website is a spammer now.

Tipboard was replaced by Dashing, which has since been retired, with a new fork that is being regularly updated called Smashing https://github.com/Smashing/smashing

**Comment by nodiscc** [comment]
Thanks, https://github.com/allegro/tipboard last commit  on Jul 22, 2019

@jeremymeyers do you want to send a Pull Request to replace Tipboard with Smashing? https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md

**Comment by nodiscc** [comment]
Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2468
