### ISSUE TITLE
Remove games that aren't self-hostable

### ISSUE THREAD

**Issue by bmanturner** [awesome-selfhosted/awesome-selfhosted#2453]
There are games in the games category that are free and open-source but don't include any component that is self-hosted.

The Battle for Wesnoth and Mindustry are two such examples.

**Comment by nodiscc** [comment]
> The Battle for Wesnoth

I was under the same impression when I reviewed the Pull Request that added it, but BfW comes with a self-hostable multiplayer server. In Debian it is packaged in the https://packages.debian.org/sid/wesnoth-1.14-server package

> Mindustry

indeed it's purely a local, non-multiplayer/networked game. @bmanturner do you want to send a Pull Request to remove Mindustry? https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md

**Comment by kokomo123** [comment]
Seems Mindustry has a server component, https://mindustrygame.github.io/wiki/servers/
