### ISSUE TITLE
Add Penpot (UX/UI design & prototype)

### ISSUE THREAD

**Issue by diacritica** [awesome-selfhosted/awesome-selfhosted#2475]
It seems there should be a new category? Like Design or something?
Penpot (penpot.app) is a recently published MPL2.0 design & prototype tool. You can use penpot.app or self.hosted yourself

See https://help.penpot.app/faqs/ and most importantly https://help.penpot.app/technical-guide/getting-started/

Penpot is being considered as a potential open source Figma/Sketch/Invision killer and it's actively developed and maintained.

**Comment by Rabenherz112** [comment]
The issue can be closed since the software has been added.
