### ISSUE TITLE
Remove / Fix CumulusClips demo link

### ISSUE THREAD

**Issue by simuuh** [awesome-selfhosted/awesome-selfhosted#2495]
The Site and Demo link is not longer available: cumulusclips.org and demo.cumulusclips.org. Project looks dead?

**Comment by kokomo123** [comment]
Last commit was in October 2017 according to Github, their website is only in http and not https ssl errors unfortunately, but their forum still seems somewhat-active or now dead. So, I'll put in a PR but i'm sure we can add it back if it comes to it. Just making sure .
