### ISSUE TITLE
/e/OS (e.foundation) self-hosted cloud

### ISSUE THREAD

**Issue by KevinFanch** [awesome-selfhosted/awesome-selfhosted#2499]
Hello,
Is it possible to include /e/ self-hosted email, calendar, contacts etc in the project. It integrates well with cell phones with /e/ OS to self-host all your personal data without using any Google/Apple account etc. /e/ OS also can also sync with a Nextcloud server.
https://gitlab.e.foundation/e/infra/ecloud-selfhosting

**Comment by KevinFanch** [comment]
No one interested?

**Comment by reddec** [comment]
@KevinFanch just make PR :+1:
