### ISSUE TITLE
The site for Reader Self leads to a domain purchase page

### ISSUE THREAD

**Issue by t0xic0der** [awesome-selfhosted/awesome-selfhosted#2541]
ReaderSelf is located under the Feed Readers category.

When clicking on the link, it leads here.

![image](https://user-images.githubusercontent.com/49605954/120109245-38f08f80-c186-11eb-9b04-390bb9e05acc.png)

I would suggest contacting the repository maintainer to see if they are actively maintaining their project. The very fact that the ownership on that domain has been given up might implicate the fact that they are not (also that, the last commit made to that repo's primary branch is about four years back).

**Comment by t0xic0der** [comment]
Here the owner of the project mentions the project not being maintained anymore.

Ref https://github.com/stephanediondev/readerself/issues/91#issuecomment-801944677

![image](https://user-images.githubusercontent.com/49605954/120109339-a2709e00-c186-11eb-8d94-74e9bb453b3d.png)

They are also suggesting, what seems to be a "reboot" of the said project - called "Feed". This can potentially replace "Reader Self" entry on the list, should the maintainer express approval on this idea.

**Comment by nodiscc** [comment]
@t0xic0der thanks for the heads up, can you send a pull request to remove Reader Self?

**Comment by t0xic0der** [comment]
Sure. I'll be sending one up in a while. You can assign this to me.

**Comment by t0xic0der** [comment]
@nodiscc Please review https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2557.
