### ISSUE TITLE
Phabricator is no longer maintained

### ISSUE THREAD

**Issue by t0xic0der** [awesome-selfhosted/awesome-selfhosted#2546]
As of Jun 1, 2021 - the project is no longer maintained.

Please find the below references.
1. https://admin.phacility.com/phame/post/view/11/phacility_is_winding_down_operations/
2. https://news.ycombinator.com/item?id=27328404

Would we want to still keep it as a list element (and let users know of its EOL status) or remove it entirely?

**Comment by ulgens** [comment]
I vote for keeping as EOL.
