### ISSUE TITLE
Add Apache Airflow

### ISSUE THREAD

**Issue by derekmurawsky** [awesome-selfhosted/awesome-selfhosted#2612]
[Apache Airflow](https://airflow.apache.org/) is a fantastic workflow automation tool. I was surprised it wasn't in the automation section already. Can we add it, or would you take a PR for it?

**Comment by nodiscc** [comment]
This should go to https://github.com/awesome-foss/awesome-sysadmin#automation but we are in the middle of transferring the repo, finding a maintenance workflow/adding tools, etc (https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2482). On hold until we sort it out

**Comment by Caydenz** [comment]
What is the reason of keeping 2 separate lists? Most software suggested by people can go into both lists, yet you choose just one. Makes no sense tbh.
