### ISSUE TITLE
Add seashell/drago

### ISSUE THREAD

**Issue by edufschmidt** [awesome-selfhosted/awesome-selfhosted#2624]
[Drago](https://github.com/seashell/drago) is a flexible configuration manager for WireGuard networks you can host anywhere. It would be a good addition to the "Communication" section.

**Comment by KieranRobson** [comment]
This addition last commit is 18th August 2021 and https://github.com/seashell/drago/issues/84 suggests the company is in liquidation.

This could be closed.
