### ISSUE TITLE
Add "Send" a fork of Firefox Send

### ISSUE THREAD

**Issue by TheFiZi** [awesome-selfhosted/awesome-selfhosted#2630]
Category `File Transfer - Single-click & Drag-n-drop Upload`

[Send](https://github.com/timvisee/send) - A fork of Firefox Send based on the last pre-release branch before Mozilla gave up `MPL-2.0` `Nodejs`

**Comment by kokomo123** [comment]
Already implemented, we can close this @nodiscc
