### ISSUE TITLE
Add praul/autoreply to automation - Am I doing something wrong.

### ISSUE THREAD

**Issue by praul** [awesome-selfhosted/awesome-selfhosted#2632]
Hey there, I filed this pull request a while ago and gave feedback accordingly. Now it is just sitting there. Am I doing something wrong, or do I just have to be patient? Thanks for any response :)
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2602

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2602
