### ISSUE TITLE
Add glewlwyd Single Sign On server

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#2635]
https://babelouest.github.io/glewlwyd/

>  Single Sign On server, OAuth2, Openid Connect, multiple factor authentication with, HOTP/TOTP, FIDO2, TLS Certificates, etc. extensible via plugins 

https://github.com/babelouest/glewlwyd

`GPL-3.0` `C`

**Comment by KieranRobson** [comment]
Will add this to Misc for now until https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2675 #1038 isnt a blocker

**Comment by Rabenherz112** [comment]
Should be moved to https://github.com/awesome-foss/awesome-sysadmin#identity-management

**Comment by nodiscc** [comment]
> https://github.com/babelouest/glewlwyd#disclaimer
>> I recommend not to use Glewlwyd in production

That settles it, it looks interesting and simple to set up, but given this recommendation I don't think it makes much sense to list it here. Closing
