### ISSUE TITLE
Mailu Demo link leads to an empty wiki

### ISSUE THREAD

**Issue by t0xic0der** [awesome-selfhosted/awesome-selfhosted#2645]
The demo for the Mailu application gets you to https://github.com/Mailu/Mailu/wiki/Demo-server and that page does not exist, thus allowing the users to create a new page. 

We would most likely want to remove the demo link from in front of the Mailu entry.

**Comment by nodiscc** [comment]
@t0xic0der good catch, can you send a pull request?

**Comment by t0xic0der** [comment]
Sure. I'll send a PR shortly.
