### ISSUE TITLE
replace link with my fork

### ISSUE THREAD

**Issue by binex-dsk** [awesome-selfhosted/awesome-selfhosted#2654]
my fork is available here: https://git.swurl.xyz/swirl/link

this fork adds query-string support, improved self-hosting guide + pre-provided NGINX/systemd files, and more stuff

Also, it uses a hierarchical filesystem-based storage system instead of SQLite which improves performance and makes managing it much easier

the original also appears to be mostly unmaintained

**Comment by nodiscc** [comment]
- which link?
- have you contacted the original author to try to get your changes merged there?

**Comment by binex-dsk** [comment]
idk how to contact him, other than maybe on #2547 

Also I'm working on a version written in C (https://git.swurl.xyz/swirl/clink) that literally will be a direct copy of the current one but in C and less Go hell, so it might be better to just use that if and when I finish that

**Comment by binex-dsk** [comment]
@nodiscc Yeah i finished it lol making a new issue
