### ISSUE TITLE
Request: add Automatic Backup section

### ISSUE THREAD

**Issue by TheSamDickey** [awesome-selfhosted/awesome-selfhosted#2668]
Hello!

I absolutely love this repository.  I've found so many cool projects from this list.  

Every sever, selfhosted or not, needs to have backups. I came to this list to look at the backup section and realized it doesn't exist!  

A list of tools similar to rsync would be really useful.

**Comment by virtadpt** [comment]
I can think of a few right off the top of my head:

- rdiff-backup
- Duplicity
- Restic

**Comment by nodiscc** [comment]
https://github.com/awesome-foss/awesome-sysadmin#backups

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3275
