### ISSUE TITLE
Airsonic isn't maintained anymore

### ISSUE THREAD

**Issue by caughtquick** [awesome-selfhosted/awesome-selfhosted#2672]
https://github.com/airsonic/airsonic 

The original developer recommends migrating to https://github.com/airsonic-advanced/airsonic-advanced.

**Comment by nodiscc** [comment]
@caughtquick thank you, can you send a PR to fix this? https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md

**Comment by caughtquick** [comment]
Sure, I'll get to it within the next 12 hours.
