### ISSUE TITLE
Add SheetAble

### ISSUE THREAD

**Issue by vallezw** [awesome-selfhosted/awesome-selfhosted#2674]
SheetAble is a self-hosted music sheet organizer. [SheetAble Documentations](https://sheetable.net)

**Comment by vallezw** [comment]
Hey, @nodiscc I just open-sourced this project [View Repo](https://github.com/SheetAble/server). So the non-free label is inaccurate. Sorry for not having it open-sourced right away

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2682
