### ISSUE TITLE
The Bug Genie moved to Pachno?

### ISSUE THREAD

**Issue by mzch** [awesome-selfhosted/awesome-selfhosted#2677]
[The Bug Genie](https://github.com/thebuggenie/thebuggenie)'s [offficial domain](https://www.thebuggenie.com) redirects to [Pachno](https://pach.no) - [Github Repo](https://github.com/pachno/pachno). Anyone knows if it's under development actively?

**Comment by fbartels** [comment]
On https://pach.no/releases/latest it says:

> Jun 12th, 2021: We're happy to announce the immediate availability of Pachno 1.0 - the first official release of the rebranded The Bug Genie.

**Comment by mzch** [comment]
Thanks @fbartels , I wil create PR.

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2681
