### ISSUE TITLE
add "clink" URL shortener

### ISSUE THREAD

**Issue by binex-dsk** [awesome-selfhosted/awesome-selfhosted#2680]
available here: https://short.swurl.xyz/src, demo at https://short.swurl.xyz

description: Ultra-light, simple, fast, self-hostable, filesystem-backed URL shortener.

**Comment by StephanMa** [comment]
URL raises Error 502

**Comment by binex-dsk** [comment]
fixed

**Comment by binex-dsk** [comment]
Will this be added?

I fixed the memory leaks btw lol

**Comment by KieranRobson** [comment]
No commits for 12 months:
![image](https://user-images.githubusercontent.com/32241933/191574122-ee8b7e50-a613-44f8-9121-77308f3820e4.png)

or on its mirror: https://github.com/binex-dsk/clink

**Comment by binex-dsk** [comment]
There have been no commits because it's stable and I have noticed no bugs so far. If and when I do they will be promptly fixed.

**Comment by KieranRobson** [comment]
> There have been no commits because it's stable and I have noticed no bugs so far. If and when I do they will be promptly fixed.

Ahh that makes sense, I'll look into making a PR shortly
