### ISSUE TITLE
[Propoal] Is it good to remove apps which don't seem to be self-hosted?

### ISSUE THREAD

**Issue by mzch** [awesome-selfhosted/awesome-selfhosted#2695]
I don't think the following apps are self-hosted. I hope to hear your ideas.

1. [Hexo](https://hexo.io/) in Blogging Platfomes - This is a static site generator like hugo or jekyll.
2. [CUPS](https://www.cups.org/) in Miscellaneous - Yes, this uses IPP, but generally it's seen as a local printer driver.

**Comment by nodiscc** [comment]
Hi,

> Hexo

Already listed at https://staticsitegenerators.net/, please go ahead and remove it, thanks

> CUPS

IPP/CUPS works well over a LAN. Yes the most common CUPS setup is listening on localhost or a unix socket, but it is a network server by nature. Let's keep it

**Comment by mzch** [comment]
>Already listed at https://staticsitegenerators.net/, please go ahead and remove it, thanks

I just create PR ##2698 :)

>IPP/CUPS works well over a LAN. Yes the most common CUPS setup is listening on localhost or a unix socket, but it is a network server by nature. Let's keep it

Well, surelly CUPS is expanadable to LAN transparently. Anyone else has no objection?
