### ISSUE TITLE
Could Diffuse be added to this list?

### ISSUE THREAD

**Issue by Netherquark** [awesome-selfhosted/awesome-selfhosted#2720]
[Diffuse](https://github.com/icidasset/diffuse) is a self hosted music streaming application. You can read about it [here](https://nightly.diffuse.sh/about/).

**Comment by dtat1991** [comment]
Sure

**Comment by E05847220211** [comment]
Hi

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
