### ISSUE TITLE
Misleading sentence for non-free

### ISSUE THREAD

**Issue by rodber** [awesome-selfhosted/awesome-selfhosted#2721]
Hey there,

I believe that [non-free.md](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md) is misleading. As I do both types of software, and as my softwares are listed on both lists, I believe that I've the knowledge to rebate some of the words used in the description.

Disclaimer: I'm the creator of [Chevereto](https://chevereto.com/) and [Chevereto-Free](https://github.com/chevereto/chevereto-free).

>Software listed here does not allow you to run it for any purpose, study, modify or distribute the source code.

^ That will depend on each given license. You can't make a general statement like that. Generally speaking, the most common restriction is on re-distribution of the source code. I think that it should be changed to:

`Software listed here implements their own licensing with restrictions and grants which you must check on each case. Restrictions may include but not limit to allowed use of the software, access to the source code and further distribution.`

There's also a very unfair statement here:

> (...) can therefore contain anti-features, such as but not limited to: undisclosed security vulnerabilities, backdoors, user lock-in, sending personal data to a third party.

^ Undisclosed security vulnerabilities is not exclusive to proprietary software but all. Having a software licensed as Free Software doesn't means that it won't have undisclosed security vulnerabilities. It will depend on each researcher to commit back that information. I believe that it should be changed to something like this:

`(...) can therefore contain anti user-freedom features, such as but not limited to: backdoors, user lock-in, sending personal data to a third party.`

I didn't push a commit as I would love to read other opinions on this matter before doing that.

**Comment by nodiscc** [comment]
Thanks for taking the time to write this. I think we should change the current page header as follows (just slightly modified version of your proposed change):

```diff
-# Awesome Selfhosted - Proprietary Software
+# Awesome Selfhosted - Non-Free Software

-**Software listed here does not allow you to run it for any purpose, study, modify or distribute the source code.** Some of the software here may not be audited due to its closed source nature, and can therefore contain anti-features, such as but not limited to: undisclosed security vulnerabilities, backdoors, user lock-in, sending personal data to a third party.
+**Software listed here does not meet the [Free Software](https://en.wikipedia.org/wiki/Free_software) definition**. It implements their own licensing with restrictions and grants which you must check on each case. Restrictions may include limits on allowed use of the software, access to the source code, modification and further redistribution. This software can therefore contain anti user-freedom features, such as but not limited to: backdoors, user lock-in, sending personal data to a third party.
```

@rodber do you want to send a pull request?
