### ISSUE TITLE
Add Entries: Xonotic, Red Eclipse, Unvanquished

### ISSUE THREAD

**Issue by HAMM3REXTREME** [awesome-selfhosted/awesome-selfhosted#2736]
Add entries to 'Games':

> Xonotic: Quake-like Arena Shooter. successor to Nexuiz.

> Red Eclipse: First Person Shooter with parkour mechanics and editable In-Game maps.

>  Unvanquished: First Person Sci-Fi Shooter with a twist of base building to defend against aliens.

**Comment by Blackia916** [comment]
> Add entries to 'Games':
> 
> 
> 
> > Xonotic: Quake-like Arena Shooter. successor to Nexuiz.
> 
> 
> 
> > Red Eclipse: First Person Shooter with parkour mechanics and editable In-Game maps.
> 
> 
> 
> >  Unvanquished: First Person Sci-Fi Shooter with a twist of base building to defend against aliens.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
