### ISSUE TITLE
Adding OneDev to Project management?

### ISSUE THREAD

**Issue by mzch** [awesome-selfhosted/awesome-selfhosted#2743]
[OneDev](https://onedev.io/) - ([Souce Code](https://onedev.io/projects/160), [GitHub](https://github.com/theonedev/onedev))
**All-In-One DevOps Platform**
With Git Management, Issue Tracking, and CI/CD. Simple yet Powerful.
`MIT` `Java`
Can anyone create PR?

**Comment by yo28466** [comment]
It's good
