### ISSUE TITLE
Improvements on the definition of "self-hosting"

### ISSUE THREAD

**Issue by rodber** [awesome-selfhosted/awesome-selfhosted#2762]
Hi,

I believe that the following definition from README.md is misleading:

```plain
Self-hosting is the practice of locally hosting and managing applications instead of renting from [SaaSS](https://www.gnu.org/philosophy/who-does-that-server-really-serve.html) providers.
```

For most users the term "locally hosting" means systems in the same facility as in the same local network. I believe that usage of this definition could drive in users excluding the concept of renting actual servers where they can freely install any of the software listed here. I believe that a better definition could be:

```plain
Self-hosting is the practice of hosting and managing applications in your own tenancy instead of consuming the software from [SaaS](https://www.gnu.org/philosophy/who-does-that-server-really-serve.html) providers.
```

I changed the term renting for consuming as there are many services which are "free" and some users may get confused.

The following sentence also needs some tweaking:

```plain
This is a list of (...) which can be hosted locally.
```

For something like:

```plain
This is a list of (...) which can be installed and hosted in your tenancy.
```

Let me know what you think about these and if everything looks good I will open a pull request for it.

**Comment by Vendetta26** [comment]
start

**Comment by nodiscc** [comment]
Hi,

> For most users the term "locally hosting" means systems in the same facility as in the same local network. I believe that usage of this definition could drive in users excluding the concept of renting actual servers where they can freely install any of the software listed here

I agree. Delegating hardware/operating system virtualization to a provider is commonly accepted as still being self-hosting.

> Self-hosting is the practice of hosting and managing applications [...] instead of consuming the software from [SaaS](https://www.gnu.org/philosophy/who-does-that-server-really-serve.html) providers.

Agree with this part 

> in your own tenancy

Not sure about this. English is not my native language but "tenancy" seems to imply temporary or leased ownership? That is, it does not cover services hosted _on-premises_ (I may be wrong).
- https://en.wiktionary.org/wiki/tenancy
- https://www.merriam-webster.com/dictionary/tenancy
- https://en.wiktionary.org/wiki/tenant#English

It also implies that merely being the tenant of a "resource" (for example a proprietary cloud/PaaS instance) makes it self-hosted, which in my opinion in incorrect. The [wikipedia page](https://en.wikipedia.org/wiki/Self-hosting_(web_services)) doesn't help. The [wiktionary](https://en.wiktionary.org/wiki/self-hosting) explicitely mentions _servers_. I struggled with the definition myself in the [xsrv](https://xsrv.readthedocs.io/en/latest/) documentation. The best I could come up with is _on your own server(s)_:

> Self-hosting is the practice of hosting and managing applications on your own server(s) instead of consuming the software from [SaaS](https://www.gnu.org/philosophy/who-does-that-server-really-serve.html) providers.

Let's change `locally` -> `on you own server(s)` ?

**Comment by M-F-P** [comment]
> > in your own tenancy
> 
> Not sure about this. English is not my native language but "tenancy" seems to imply temporary or leased ownership? That is, it does not cover services hosted _on-premises_ (I may be wrong).
> 
> * https://en.wiktionary.org/wiki/tenancy
> * https://www.merriam-webster.com/dictionary/tenancy
> * https://en.wiktionary.org/wiki/tenant#English
> 
> It also implies that merely being the tenant of a "resource" (for example a proprietary cloud/PaaS instance) makes it self-hosted, which in my opinion in incorrect.

The legal use of the word "tenancy" extends back at least to the medieval period and, more or less, refers to any present interest in land, which extends far beyond the context of leases. This includes multiple names for estates in land in the legal context, such as joint tenancy, which many people are familiar with since it is the default ownership interest in real property for married couples in many states, tenancy in common, and tenancy by the entirety.

With all of that said, I agree that the majority of laymen who come across a reference to a tenancy in a nonlegal context will assume it is a reference to property that is leased. Therefore, it is probably best to avoid use of the word tenancy.

I leave the decision on replacement verbiage to others as i am not a wordsmith. I suggest referencing a class of property that the host operator regularly visits and has the ability to exclude the presence of others.

**Comment by nodiscc** [comment]
Fixed in current master
