### ISSUE TITLE
Table of Contents in a menu button next to README.md is annoying.

### ISSUE THREAD

**Issue by hashborgir** [awesome-selfhosted/awesome-selfhosted#2771]
Could you change it back to where the ToC was in the actual article and not a separate menu?

We should not be required to click a tiny menu icon and scroll through the ToC in that tiny little window. Just put the ToC at the top in the article, and do a link back to ToC at the beginning of every section, anchor links.

It's seriously annoying and very hard to navigate. Thanks.

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#table-of-contents done

**Comment by hashborgir** [comment]
Thank you very much! So very nice and lovely to have the Whole ToC back on top of the article. Much appreciated. Cheers.
