### ISSUE TITLE
crtmpserver Broken Link

### ISSUE THREAD

**Issue by F0x1fy** [awesome-selfhosted/awesome-selfhosted#2772]
It appears crtmpserver has a broken link and may not longer be available on Debian? I was able to find [a clone of the SVN repository](https://github.com/j0sh/crtmpserver) but it's unofficial and seems out of date. The official crtmpserver website also seems to be under a new owner completely unrelated to crtmpserver. This project just seems overall abandoned. Possible removal?

**Comment by nodiscc** [comment]
yep, it should be removed. Can you send a pull request?

**Comment by F0x1fy** [comment]
Hey, sorry. I’ve had a lot come up in my personal life and I completely forgot about this. I’ll submit a PR either today or tomorrow
