### ISSUE TITLE
Add a category for low code tools like Appsmith

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [awesome-selfhosted/awesome-selfhosted#2780]

**Comment by Nikhil-Nandagopal** [comment]
I have a pull request linked here for this
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2781

**Comment by nodiscc** [comment]
This issue should actually be split in two:
- [x] Add Appsmith (done)
- [ ] Group low-code development platforms under a new section -> was started in https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2781/files but the pull request was abandoned.

Feel free to reopen a Pull Request with the appropriate changes.

Closing

**Comment by nodiscc** [comment]
-> https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2385
