### ISSUE TITLE
Broken links, dead projects

### ISSUE THREAD

**Issue by filerun** [awesome-selfhosted/awesome-selfhosted#2790]
"Drive Virtual" - abandoned domain
"Resilio Sync" - doesn't link downloadable software
"Dropcenter" - abandoned project, no download to be found
"Koken" - abandoned project
"Active Collab" - not self-hosted anymore

 on https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md

**Comment by BigMula11** [comment]
Hey

**Comment by kppetro** [comment]
> Looking for work

What would you like to do? I'll see if I can help

**Comment by CalebMwelwa** [comment]
Hey

**Comment by BigMula11** [comment]
Drilling offshore
