### ISSUE TITLE
Blogging platforms: Lots of CMSes listed there

### ISSUE THREAD

**Issue by mbirth** [awesome-selfhosted/awesome-selfhosted#2793]
Blogging platform usually means support for blogging things like remote publishing via XML-RPC / MetaWeblog / AtomPub, or sending and/or receiving of pingbacks and trackbacks.

Many of the entries under "Blogging platforms" lack all of the above and thus are CMSes, not blogging platforms.

**Comment by Ketherthe1st** [comment]
Java.orchid.gov.uk

**Comment by Ketherthe1st** [comment]
Meta was better in  v1

**Comment by Ketherthe1st** [comment]
- https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2793#issuecomment-1001545716

**Comment by Ketherthe1st** [comment]
Cranial create box memory se x

**Comment by Ketherthe1st** [comment]
Zx spectrum
©1982

**Comment by arfahmd** [comment]
.
