### ISSUE TITLE
add pacebin

### ISSUE THREAD

**Issue by binex-dsk** [awesome-selfhosted/awesome-selfhosted#2875]
pacebin is a dead-simple pastebin service, entirely driven and usable by CLI, with minimal CPU, disk, and memory usage. Written in C and licensed under the AGPL3 license.

https://git.swurl.xyz/swirl/pacebin

**Comment by binex-dsk** [comment]
related #2680

**Comment by binex-dsk** [comment]
Remove trance from this because it kinda sucks

**Comment by Rabenherz112** [comment]
Before creating a PR for this, can you confirm that you are still maintaining this? (Since there were no recent commits activity and the website has an expired certificate (https://paste.swurl.xyz/).

**Comment by binex-dsk** [comment]
> the website has an expired certificate (https://paste.swurl.xyz/).

Thanks for bringing this to my attention, I will fix this next week.

pacebin is still completely maintained. Trance is not maintained as the architecture required for simple uploading does not mesh with the standard pacebin/clink-style architecture. I will edit accorsingly

**Comment by Rabenherz112** [comment]
Thank you very much. Could you please notify me once you have resolved the issues related to the SSL certificate for both the Git website and paste website? I prefer not to add them until they have a valid SSL certificate in place.
Once that is done, I would create a PR for it.

**Comment by binex-dsk** [comment]
@Rabenherz112 SSL issues have been fixed--NGINX failed to reload due to a broken config which causes my certbot crontab to not run. Everything should be good to go.
