### ISSUE TITLE
New Solution and new Category "Software Development - Security" addition - Scanmycode CE (Community Edition) 

### ISSUE THREAD

**Issue by marcinguy** [awesome-selfhosted/awesome-selfhosted#2896]
Hi,

I would like to share information about my Open Source and selfhosted Code Scanning (Quality & Security) solution here. I would like to make a PR and propose a new category "Security" in "Software Development". I see this category is not there. Is it allowed to create new category? Any advice on PR? 

Here it the repository for the Community Edition of the solution (Code & Wiki) 

https://github.com/marcinguy/scanmycode-ce

For transparency, I was involved and am involved in building of it. Took several months with several people.

Thanks,

**Comment by marcinguy** [comment]
PR created: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2897

**Comment by carthomi** [comment]
Nice

**Comment by WhiteNight121** [comment]
If a PR was opened could this issue be closed
