### ISSUE TITLE
Agendav website is unrelated

### ISSUE THREAD

**Issue by velmirslac** [awesome-selfhosted/awesome-selfhosted#2919]
Under [Calendar & Contacts - CalDAV or CardDAV Web-based Clients](https://github.com/awesome-selfhosted/awesome-selfhosted#calendar--contacts---caldav-or-carddav-web-based-clients), the site linked to for AgenDAV, https://agendav.org/, is an unrelated cloud developer site. The AgenDAV CalDAV client does not appear to have a website of its own at this time.

**Comment by marcelbrueckner** [comment]
AgenDAV used to serve it's website under the mentioned domain until end of 2020. You can check it via archive.org. It's also linked in their GitHub repo which seems to be abandoned (aka maintenance mode as stated in the README).

**Comment by Leviyoun** [comment]
Nice

**Comment by nodiscc** [comment]
Related:
- https://github.com/agendav/agendav/issues/273
- https://github.com/agendav/agendav/issues/271
