### ISSUE TITLE
Add AmneziaVPN

### ISSUE THREAD

**Issue by NEK-RA** [awesome-selfhosted/awesome-selfhosted#2930]
AmneziaVPN is one more project to easily deploy own VPN server using few different protocols. Currently they are:

- OpenVPN
- OpenVPN over Shadowsocks
- OpenVPN over Cloak* + Shadowsocks over Cloak*
- Wireguard
- IPSec/IKEv2

*- Cloak is obfuscation plugin (https://github.com/cbeuw/Cloak)

Like the Outline project, AmneziaVPN configures everything inside Docker containers to be able easily setup, reconfigure protocols and avoid polluting host system.

Project's profile on Github: https://github.com/amnezia-vpn
Desktop client: https://github.com/amnezia-vpn/desktop-client
Also already released Android client: https://play.google.com/store/apps/details?id=org.amnezia.vpn

**Comment by Fe4rl3** [comment]
OpenVPN

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3409
