### ISSUE TITLE
OCTAVE Online

### ISSUE THREAD

**Issue by d1nuc0m** [awesome-selfhosted/awesome-selfhosted#2931]
The full stack of [Octave Online website](https://octave-online.net/) is [on GitHub](https://github.com/octave-online/octave-online-server), and it should be under different open licenses. Is it a good candidate for the list?

**Comment by nodiscc** [comment]
> Is it a good candidate for the list?

>> web UI for GNU Octave, the open-source alternative to MATLAB.

Yes

**Comment by d1nuc0m** [comment]
@nodiscc pull request done

**Comment by nodiscc** [comment]
Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2945
