### ISSUE TITLE
Add Easypanel

### ISSUE THREAD

**Issue by deiucanta** [awesome-selfhosted/awesome-selfhosted#2952]
I'm wondering if I should add my product [easypanel.io](https://easypanel.io) in this list. The product is not open-source but has a free version for developers.

**Comment by MyBlood** [comment]
> I'm wondering if I should add my product [easypanel.io](https://easypanel.io) in this list. The product is not open-source but has a free version for developers.

Why not? You can make an appropriate tag about it.

**Comment by deiucanta** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2967
