### ISSUE TITLE
[Question] Secure contact sync

### ISSUE THREAD

**Issue by BirdInFire** [awesome-selfhosted/awesome-selfhosted#2957]
Any alternative for secure contact sync (alternative for ete-sync) since they do not update enough their app, (i year without update) is a security problem, for now i use a cardav, but i would like to found an alternative like etesync but who have 2FA or any modern/secure connection method.

If someone have an idea.

Note : i ask because i do not trust the old protocol caldav witch do not support encryption of the data so if a brute-force attack found the password the data are leaked.

**Comment by nodiscc** [comment]
You will get better replies in a specialized [community/forum](https://github.com/awesome-selfhosted/awesome-selfhosted#external-links)

CalDAV over SSL/TLS with strong passwords is fine.
