### ISSUE TITLE
Add EmulatorJS to Games Category

### ISSUE THREAD

**Issue by TheMethodicalJosh** [awesome-selfhosted/awesome-selfhosted#2963]
Could I suggest adding EmulatorJS to the Games category of this github?

https://github.com/ethanaobrien/emulatorjs
https://github.com/linuxserver/emulatorjs

> EmulatorJS helper
> The purpose of this application is to provide a self hosted solution for people looking to run Retro games in their web browsers. It consists of a backend application for scanning roms and ingesting art assets with a static frontend application for serving those files via any basic webserver. The backend appplication is more or less a run once deal, when you have finalized the menus how you like them the resulting static files of the frontend no longer require the backend helper.
> 
> This idea was born from a single need, I wanted to run retro games on my Xbox which now includes a modern chromium based web browser with Microsoft Edge. Web based emulators are popular online but always ingesting roms from external sources is a pain not to mention prone to being taken down at any time, also their interfaces are never designed around basic controller input making navigation difficult with something like an Xbox controller.
> 
> It is important to note that the current emulator used for this frontend is obfuscated code, efforts are being made to [reverese engineer it](https://github.com/ethanaobrien/emulatorjs/) but you should know it can potentially reach out to third party services if you manually enable features like netplay (this should never happen in a stock setup). We are in the process to transitioning to libretro cores for emulators, currently 27/30 emulators have been replaced.

**Comment by Rabenherz112** [comment]
If I understand the documentation correctly, this is not self-hosted Software in the ordinary sense but instead a script which can generate a website from users' inputs. (https://emulatorjs.org/docs/Getting%20Started.html#setup)

(User enters all emulation data like system, rom, etc. and receives an HTML file that can be used to play the game)

Does this even fit into this list?

**Comment by kokomo123** [comment]
I'm closing this issue as yeah, i feel like that doesn't fit into the list because rather, you just generate a website and play games there. you don't expose it to anything else. Feel free to reopen if this was in error. trying to clean up old issues 👍🏻
