### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by ironicbadger** [awesome-selfhosted/awesome-selfhosted#2981]
@nodiscc Are you looking for maintainers? I'd be interested in helping moderation of issues and PRs.

**Comment by nodiscc** [comment]
@ironicbadger  Of course, reviewing pull requests is time consuming (mostly checking that they conform to [contribution guidelines](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/PULL_REQUEST_TEMPLATE.md), that they are indeed *server* software, and that they are not non-Free/SaaS products in disguise), help is always welcome:

- https://github.com/awesome-selfhosted/awesome-selfhosted/pulls?q=is%3Aopen+label%3A%22feedback+needed%22
- https://github.com/awesome-selfhosted/awesome-selfhosted/pulls?q=is%3Apr+is%3Aopen+label%3A%22feedback+needed%22+review%3Anone

Everyone can do it, it has always been the case :) It just so happens that there are not many reviewers (this is also why I wait for some time before merging PRs where I'm the only reviewer, more eyeballs would sometimes be appreciated).

Automatic link/syntax/last update date checking is on the way (https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/8), but currently must be done manually.

Syntax fixes or cleanup/curation pull requests are merged immediately. Triaging issues is not a problem, most of them are suggestions to add X or Y and anyone can work on them through a pull request.

Let me know if you need further guidance.
