### ISSUE TITLE
Add short descriptions to all sections

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#2984]
Each section should have a description sentence that briefly describes what the section is about. Adding an inline link to a "canonical" resource on the subject (e.g. Wikipedia page) is recommended.

Examples:
- https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#communication---irc
- https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#community-supported-agriculture-csa

In preparation of https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038, see https://github.com/awesome-selfhosted/awesome-selfhosted/milestone/2, https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/8

**Comment by FIDYOHARA777** [comment]
> Each section should have a description sentence that briefly describes what the section is about. Adding an inline link to a "canonical" resource on the subject (e.g. Wikipedia page) is recommended.
> 
> Examples:
> - https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#communication---irc
> - https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#community-supported-agriculture-csa
> 
> In preparation of https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038, see https://github.com/awesome-selfhosted/awesome-selfhosted/milestone/2, https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/8

Que porra é essa ?

**Comment by nodiscc** [comment]
After https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3215, only `Gateways and Terminal Sharing` is missing a description (but needs reordering/cleanup).

```
awesome-selfhosted-data (master *%>)$ make awesome_lint 
...
WARNING:awesome_lint.py: Gateways and Terminal Sharing: description is empty
```

**Comment by KieranRobson** [comment]
With the merge of #3221, I believe this could be closed!
