### ISSUE TITLE
Add DiscordBotPanel - DBP

### ISSUE THREAD

**Issue by jareer12** [awesome-selfhosted/awesome-selfhosted#3000]
[https://github.com/jareer12/DiscordBotPanel](https://github.com/jareer12/DiscordBotPanel)

DiscordBotPanel is a self-hosted platform to manage your Discord bots and Node.js scripts from the web.
Made with Typescript and plain ejs/html frontend(no particular framework).

**Comment by alainseys** [comment]
@jareer12  thanks for the info i have made a [pull request ](https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3023)
