### ISSUE TITLE
Feature request: Add stars and last modified date next to the name

### ISSUE THREAD

**Issue by rolocampusano** [awesome-selfhosted/awesome-selfhosted#3019]
Thats it. I dont know how to flag this. But it would be awesome to learn about the projects. 
Thanks!

**Comment by nodiscc** [comment]
Planned as part of https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038, https://github.com/nodiscc/hecat/milestone/1 (but the stars count will only be displayed in the HTML/"rich" version of the list, not in the current markdown version which is already very cluttered).

**Comment by alainseys** [comment]
@nodiscc  you can also use some simple simbolics this can also be used in markdown the only caveat is that you need to copy and paste this. 

★☆☆☆☆
★★☆☆☆
★★★☆☆
★★★★☆
★★★★★

**Comment by nodiscc** [comment]
Fixed on https://awesome-selfhosted.net.

Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.
