### ISSUE TITLE
Remove MailyHerald because it has not been updated since 2018

### ISSUE THREAD

**Issue by lcfd** [awesome-selfhosted/awesome-selfhosted#3028]
Hi 👋
MailyHerald is no longer actively maintained.

https://github.com/Sology/maily_herald

**Comment by nodiscc** [comment]
@lcfd thanks, can you send a pull request to remove it? https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md

**Comment by KieranRobson** [comment]
This issue can be closed due to the above commit
