### ISSUE TITLE
add LinkWarden - A self-hosted bookmark 

### ISSUE THREAD

**Issue by lpslp** [awesome-selfhosted/awesome-selfhosted#3055]
https://github.com/Daniel31x13/link-warden A self-hosted bookmark + archive manager to store your useful links.

**Comment by KieranRobson** [comment]
Hello @lpslp!

Please open a [pull request](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls) with this addition! 

It would go under the bookmarking and link sharing heading

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md
