### ISSUE TITLE
Please split out videoconferencing

### ISSUE THREAD

**Issue by jech** [awesome-selfhosted/awesome-selfhosted#3124]
There is no dedicated section for videoconferencing.  Most videoconferencing software is in the *Custom communication systems* section, which, IMHO, is way too long.  I also see that *BigBlueButton* is in the *Conference management systems* section, which does not make a lot of sense to me.

I suggest splitting out videoconferencing servers into their own section.

**Comment by KieranRobson** [comment]
@jech Great suggestion!

Each section needs three projects minimum for it to be valid as a section. Which three projects do you think would fit here?

---

```
Conference Management
Conference Management - Video Conferencing
```
would be a good solution if the section is valid

**Comment by nodiscc** [comment]
I think `Conference Management` is specific to https://en.wikipedia.org/wiki/Conference_management. A better section name would be `Communication - Video Conferencing`.

If someone can find 3 items that would fit this section and send a Pull Request, I would gladly merge it.

**Comment by KieranRobson** [comment]
I'll work on this over the next day or two looking through the current solutions

Bigbluebutton seems to be a good start to the section

**Comment by jech** [comment]
> Each section needs three projects minimum for it to be valid as a section. Which three projects do you think would fit here?

There's at least the following that are most definitely videoconferencing servers:
- BigBlueButton
- Jitsi Meet
- Jitsi Video Bridge
- Galene
- LiveKit

**Comment by KieranRobson** [comment]
https://github.com/forks-by-kieran/awesome-selfhosted/tree/adding_videoconference#communication---video-conferencing

I have added the video conferencing software (I moved `Spreed` over for the time being however this will probably be removed within PR #3099 due to the last commit date of 2017. Once this has been merged, we can look at adding the other ones you listed in separate PRs.
