### ISSUE TITLE
Move Status/Uptime Pages section back from awesome-sysadmin

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#3166]
https://github.com/awesome-selfhosted/awesome-selfhosted#status--uptime-pages currently says **Please visit https://github.com/awesome-foss/awesome-sysadmin#status-pages**, but there are items under this section, some of which are duplicates with awesome-sysadmin.

Since awesome-sysadmin maintenance is on hold (https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2482) I suggest moving this section back to awesome-selfhosted completely.

All entries must be reviewed, source code links and license/language tags added.

```
* [Cachet](https://cachethq.io) - Status page system written in PHP.
* [Stashboard](http://www.stashboard.org) - Status page for cloud services and APIs.
* [Statusfy](https://statusfy.co/) - A modern status page for presenting critical service updates.
* [System Status Dashboard (SSD)](http://www.system-status-dashboard.com/) - Overview about an organization's infrastructure health status.
* [Staytus](http://staytus.co/) - Staytus is a complete solution for publishing the latest information about any issues with your web applications, networks or services.
* [vigil](https://github.com/valeriansaliou/vigil) -  Microservices Status Page. Monitors a distributed infrastructure and sends alerts to Slack. Written in Rust.
* [Statping](https://github.com/hunterlong/statping) - Status page system written in Go.
* [Uptime Kuma](https://github.com/louislam/uptime-kuma) - Self-hosted status page similar to "Uptime Robot".
* [netcheck](https://demo.ncheck.eu/#/info) – Simple ping status system written in Java, similar to Pingdom and StatusCake.
```

Then section contents on awesome-sysadmin can be removed/replaced with

```
Please visit [awesome-selfhosted/Status/Uptime Pages](https://github.com/awesome-selfhosted/awesome-selfhosted#status--uptime-pages)
```

<details>

Problem found with https://github.com/nodiscc/hecat

```
ERROR:awesome_lint.py: cState: the first tag Status / Uptime pages points to a tag delegated to another list.
ERROR:awesome_lint.py: s.Status: the first tag Status / Uptime pages points to a tag delegated to another list.
ERROR:awesome_lint.py: Uptime Kuma: the first tag Status / Uptime pages points to a tag delegated to another list.
```

**Comment by KieranRobson** [comment]
Feel free to assign this to me and I should have this done in a couple of hours 👍🏻

**Comment by KieranRobson** [comment]
No commits since 2021 - 
* [Cachet](https://github.com/CachetHQ/Cachet) 
* [Staytus]( https://github.com/statping/staytus)
* [Statping](https://github.com/hunterlong/statping

**Comment by kokomo123** [comment]
Statping-NG should be added instead, Kieran. I think it'd do best as a replacement for statping. https://github.com/statping-ng/statping-ng. But as for all the other ones, it seems they have been no longer maintained in quite some time which is unfortunate.

**Comment by KieranRobson** [comment]
> Statping-NG should be added instead, Kieran. I think it'd do best as a replacement for statping. https://github.com/statping-ng/statping-ng. But as for all the other ones, as you have stated, they have been no longer maintained in quite some time which is unfortunate.

Will get that added!

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3269 closes this.

https://github.com/awesome-foss/awesome-sysadmin/blob/master/README.md#status-pages now redirects to awesome-selfhosted.
