### ISSUE TITLE
Request to add All-In-One Email server

### ISSUE THREAD

**Issue by Mrs-Feathers** [awesome-selfhosted/awesome-selfhosted#3250]
Hello! I love your comprehensive list and seem to have found something our company uses that you don't have on the list yet! We love Citadel at https://citadel.org/ because its a VERY simple to install all-in-one email server with built in chatrooms and even an XMPP server... you can use LDAP/AD if you want... it has message boards for posting to as well as mailing lists and group mailboxes for like "support@company.com" type emails. The owner has his own message board linked to the website and is VERY helpful to help you set up your own instance. :)

**Comment by mzch** [comment]
Citadel has already sit on [this list](https://github.com/awesome-selfhosted/awesome-selfhosted#groupware).

**Comment by Mrs-Feathers** [comment]
oh whoops!
