### ISSUE TITLE
[Want comments] Recomendation to remove apps.

### ISSUE THREAD

**Issue by mzch** [awesome-selfhosted/awesome-selfhosted#3260]
1. [Taskfreak](https://www.taskfreak.com/original) - This project seems not to be active. The last change was 8 years ago. The community forum is closed.
1. [Taskord](https://gitlab.com/yo/taskord) - This project has been archived.

**Comment by Taurolyon** [comment]
1. The ["original" taskfreak github](https://github.com/taskfreak/original) links to a [fork](https://github.com/HardMagic/TaskFreak), which also has not been updated in 5~6 years.

**Comment by KieranRobson** [comment]
Definitely remove `taskord` due to archival status, id also remove `taskfreak`

**Comment by KieranRobson** [comment]
@mzch The repos mentioned above have been removed in the above PR

I just thought itd be easier to do them in an already exsisting readme cleanup!

**Comment by mzch** [comment]
Thanks @KieranRobson !

**Comment by KieranRobson** [comment]
The PR isnt merged yet haha
