### ISSUE TITLE
Remove Standard Notes

### ISSUE THREAD

**Issue by TemporalAgent7** [awesome-selfhosted/awesome-selfhosted#3279]
It doesn't look like Standard Notes is an open source **selfhostable** application. You can only use their official cloud for storing and syncing notes. They appear to have an open source web viewer [application ](https://github.com/standardnotes/app) (for the notes stored on their cloud), but that's likely not enough to include them in the awesome-selfhosted list.

**Comment by davidosomething** [comment]
https://github.com/standardnotes/self-hosted ??

**Comment by nodiscc** [comment]
It's true that the homepage linked here does not give any hints about self-hosting a Standard Notes server. Maybe we should point to https://docs.standardnotes.com/self-hosting/getting-started instead.

Or make a link to installation documentation mandatory, as suggested in https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3217
