### ISSUE TITLE
Removed Lutim, Why?

### ISSUE THREAD

**Issue by mzch** [awesome-selfhosted/awesome-selfhosted#3285]
Lutim, https://framagit.org/fiat-tux/hat-softwares/lutim, has been removed. Why?

**Comment by KieranRobson** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/commit/1c422ef095b63adbe0a51f87a93d126f0e5f5fc1

As stated in this commit, the GitHub that was associated has the last commit of 2020, will reupload in my next set of clean ups
