### ISSUE TITLE
Add Fullstacco

### ISSUE THREAD

**Issue by ivanlori** [awesome-selfhosted/awesome-selfhosted#3290]
Hello,
I have created Fullstacco, a MERN boilerplate that has basic functionalities like auth, user permissions and user management.

The repo => https://github.com/ivanlori/Fullstacco
The article where I explain more => https://dev.to/ivanlori/i-have-created-fullstacco-now-what-118

Of course, this project can be self-hosted on node servers.

**Comment by CrimsonTome** [comment]
I'll get to work on a PR for this

**Comment by nodiscc** [comment]
As I understand it, it is a boilerplate meant to facilitate development of final/end-user applications. Applications based on this could be added, but not the boilerplate itself. We only list end-user applications/services.

**Comment by CrimsonTome** [comment]
Right, should I close the PR then? 
@ivanlori if you find any projects that use your framework feel free to add them :)

**Comment by ivanlori** [comment]
Ok, I understand :)
