### ISSUE TITLE
Selfhosted - Briefkastenhq Demo seems to be compromised

### ISSUE THREAD

**Issue by T0minat0r** [awesome-selfhosted/awesome-selfhosted#3309]
https://briefkastenhq.com/

logged in with Google. It resulted in instant change of ownership of my Steamaccount etc... Google flagged it as insecure.

**Comment by KieranRobson** [comment]
Id recommend you make an issue on their GitHub, there hasn't been any other reports of it and the software is maintained, we can remove the software in #3302 until this is confirmed though!

**Comment by nodiscc** [comment]
https://github.com/ndom91/briefkasten/issues/17

>  Google flagged it as harmful, it Got my Steam account hacked.
> Has to originate from this since it started right after.

No credible proof that these 2 events are linked... are you sure it's not rather linked to [this](https://www.theguardian.com/world/2022/sep/17/india-reintroduces-cheetahs-to-wild-after-big-cats-airlifted-from-namibia)? It happened on the same day...

Please reopen if you have further information.
