### ISSUE TITLE
Add Software Development - Code Hosting

### ISSUE THREAD

**Issue by AMTitan** [awesome-selfhosted/awesome-selfhosted#3311]
you could add these
- [git.sr.ht](https://man.sr.ht/git.sr.ht/installation.md) `GO` `GLP-3`
- [cgit](https://git.zx2c4.com/cgit/) `C` `GLP-2`
- [gitea](https://github.com/go-gitea/gitea) `GO` `MIT`

**Comment by mzch** [comment]
Gitea has already been listed. I also agree to add cgit and sourcehat. Please create PR.

**Comment by AMTitan** [comment]
ah I did not cgit in the list, so I though there was no section for code hosting, I will make the pr
