### ISSUE TITLE
 Please add SelfPrivacy

### ISSUE THREAD

**Issue by de2tla2f** [awesome-selfhosted/awesome-selfhosted#3322]
SelfPrivacy - https://selfprivacy.org/

Platform on user's hosting provider for deploying private services, managed via mobile application. FOSS

Can set-up this services to you own server:
    - E-Mail
    - DeltaChat
    - Bitwarden
    - Nextcloud
    - Jitsi-meet
    - Gitea
    - VPN (OpenConnect)

**Comment by nodiscc** [comment]
Only works on a single VPS provider, not self-hosted.
