### ISSUE TITLE
barrier KVM solution

### ISSUE THREAD

**Issue by G2G2G2G** [awesome-selfhosted/awesome-selfhosted#3327]
https://github.com/debauchee/barrier

for using a single keyboard/mouse with as many computers as you want. Main machine hosts other machines connect can move mouse across the different machines as if they were just multi monitors

**Comment by nodiscc** [comment]
It is still a client/server application and can the server can run headless: https://manpages.debian.org/bullseye-backports/barrier/barriers.1.en.html. I think it can be added.

**Comment by kokomo123** [comment]
Should i put it in remote access then? I didn't really think that barrier could be considered remote access software

**Comment by G2G2G2G** [comment]
yea I wouldn't say it is, it does have drag/drop copy/paste and some other stuff but you have to be looking at the other computer cuz it doesn't send any screen details over so it's "remote" but it isn't the "desktop" part lol

**Comment by kokomo123** [comment]
I think you are right, tbh I've used it and it's just for keyboard / mouse. Nothing else.

**Comment by nodiscc** [comment]
See https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3338 for the current situation, barrier is unmaintained, there is a maintained fork at https://github.com/input-leap/input-leap but it has not been released yet and installation instructions don't work. On hold until this is fixed.

**Comment by G2G2G2G** [comment]
your "see" should be to here: https://github.com/input-leap/input-leap/issues/1414 to see that barrier is in fact being phased out
