### ISSUE TITLE
Most projects are dead or outdated, maybe adding a last update time will be helpful?

### ISSUE THREAD

**Issue by redreamality** [awesome-selfhosted/awesome-selfhosted#3363]

**Comment by jdh313** [comment]
I second this!

**Comment by nodiscc** [comment]
> Most projects are dead or outdated

Source for this claim? See https://github.com/awesome-selfhosted/awesome-selfhosted-data, I just ran automatic last update checks (only works for github.com repositories so far), and those are the only two that are older than 186 days:

```bash
$  make import update_metadata awesome_lint
...
INFO:awesome_lint.py: checking software last update dates against info (186 days)/warning (365 days) thresholds
INFO:awesome_lint.py: Cubiks-2048: last updated -203 days, 7:45:36.415977 ago, older than 186 days
INFO:awesome_lint.py: dyu comments: last updated -292 days, 7:45:36.415487 ago, older than 186 days
```

If you have a specific project you would like to report as unmaintained, please open an issue about it.

> adding a last update time

already planned in https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038 and related issues.
