### ISSUE TITLE
Tiny Tiny RSS now supports only `Docker`

### ISSUE THREAD

**Issue by mzch** [awesome-selfhosted/awesome-selfhosted#3372]
Tiny Tiny BBS now supports only `Docker`. Could anyone create PR?

**Comment by Tezzichapp** [comment]
Two left

**Comment by nodiscc** [comment]
You mean Tinty Tiny RSS? I run it with a simple php-fpm/postgres/apache setup [[1]](https://github.com/nodiscc/xsrv/tree/master/roles/tt_rss), but yes, Docker is now the recommended method, we could change it to `Docker/PHP`

**Comment by mzch** [comment]
Oh, sorry, thanks. Yes, Tiny Tiny RSS. ;-P
