### ISSUE TITLE
Add aesthetic-startpage under personal dashboards

### ISSUE THREAD

**Issue by t3dium** [awesome-selfhosted/awesome-selfhosted#3386]
https://github.com/Nainish-Rai/aesthetic-startpage

**Comment by dylan8838** [comment]
。

**Comment by Tester1234537** [comment]
#~Que necesitas

**Comment by Rabenherz112** [comment]
It appears that this is more of an HTML template designed for a small StartPage rather than a self-hosted application. I believe it is not well-suited for inclusion in this list.

**Comment by nodiscc** [comment]
I agree we should not start adding static HTML startpages, otherwise we would end up adding the 1000s of startpages listed for example here https://old.reddit.com/r/startpages (currently closed).

Closing
