### ISSUE TITLE
Changed to MIT license 

### ISSUE THREAD

**Issue by openspeedtest** [awesome-selfhosted/awesome-selfhosted#3417]
https://github.com/openspeedtest/Speed-Test was listed on [Non-Free Page](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md#miscellaneous) . Three months ago I changed the license to MIT. How to move it from Non-Free Page to Main Page? and to which section?

**Comment by nodiscc** [comment]
> How to move it from Non-Free Page to Main Page?

Remove it from non-free.md, add it to README.md, send a Pull Request.

> to which section?

[Miscellaneaous](https://github.com/awesome-selfhosted/awesome-selfhosted#miscellaneous)
