### ISSUE TITLE
Plume not actively maintained.

### ISSUE THREAD

**Issue by UnisTorvalds** [awesome-selfhosted/awesome-selfhosted#3426]
According to [project homepage](https://joinplu.me), Plume is no longer actively maintained, and author directs visitors to other projects.

However, there were code commits as recently as May 2022.

Regardless, I raise the question whether this project should be removed from the list.

**Comment by nodiscc** [comment]
The guidelines state

> Any software project you are adding to the list is actively maintained.

Hence it should be removed.
