### ISSUE TITLE
[request] add voiceping self-hosted PTT service and android SDK

### ISSUE THREAD

**Issue by inovramadani** [awesome-selfhosted/awesome-selfhosted#3428]
Hi, could you please add this project: https://opensource.voiceping.info
https://opensource.voiceping.info/docs/server
Thank you.

**Comment by nodiscc** [comment]
> Walkie Talkie/Push-To-Talk SDK for your Chat Apps
> You need to use it from Android SDK

We only list end-user applications. Libraries and SDKs are out of scope.

**Comment by inovramadani** [comment]
@nodiscc have you checked that the demo apk listed there can actually be used directly as well by end users?
https://github.com/SmartWalkieOrg/VoicePingAndroidSDK/releases
