### ISSUE TITLE
Add ILLA Cloud to Software Development - Low Code

### ISSUE THREAD

**Issue by JerryMaoMao** [awesome-selfhosted/awesome-selfhosted#3436]
[ILLA Cloud](https://github.com/illacloud/illa-builder) is a good alternative to retool, appsmith, and toojet. 
ILLA Cloud is a robust open source low-code platform for developers to build internal tools. By using ILLA's library of Components and Actions, developers can save massive amounts of time on building tools.

Repo: https://github.com/illacloud/illa-builder

**Comment by Blackberry233** [comment]
What type of tools ILLAs have..and on which software they are working for??

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
