### ISSUE TITLE
Add Chell 

### ISSUE THREAD

**Issue by joszz** [awesome-selfhosted/awesome-selfhosted#3469]
Chell is an opensource dashboard for your homeserver with multiple widgets to see statistics of the server
https://github.com/joszz/Chell-PHP-Portal
https://hub.docker.com/r/gotgeeks/chell

**Comment by AmazingXam** [comment]
How do I decide what software to start with as a beginner?

**Comment by joszz** [comment]
@AmazingXam are you asking about Chell in particular, as in what widgets to setup, or are you asking a general question?
If it's general try googling selfhosted best apps or something. Googles your friend when it comes to generic questions like that

**Comment by Rabenherz112** [comment]
Hi there! I've taken a look at the project, and I noticed that there isn't any installation or configuration documentation available.

It is required to have some installation and configuration instructions for the software. This helps users understand how to set it up correctly and utilize its features effectively.
