### ISSUE TITLE
Add home assistant

### ISSUE THREAD

**Issue by sinistersnare** [awesome-selfhosted/awesome-selfhosted#3473]
Home-assistant is a home automation platform. They are located [here](https://www.home-assistant.io), with install instructions [here](https://www.home-assistant.io/installation/)

**Comment by fbartels** [comment]
The project is already included at https://github.com/awesome-selfhosted/awesome-selfhosted/blob/b7c0d992ba2edcfe7c016057a55a5b1c57e623b1/README.md?plain=1#L1088

**Comment by sinistersnare** [comment]
Not sure how I missed that, I might have ctrl-f'd for `home-assistant`. Sorry!
