### ISSUE TITLE
Couple additions to #bookmarks-and-link-sharing

### ISSUE THREAD

**Issue by tiritibambix** [awesome-selfhosted/awesome-selfhosted#3482]
https://github.com/beromir/Servas

https://github.com/haishanh/cherry

**Comment by Rabenherz112** [comment]
> https://github.com/beromir/Servas
It seems not to be actively maintained and lacks some good documentation.

> https://github.com/beromir/Servas
Looks, however, really good. If you want, feel free to create a Pull Request for that

**Comment by tiritibambix** [comment]
You've mentioned servas twice. So I'm not sure which one you're talking about :p

**Comment by Rabenherz112** [comment]
Upppps, fixed :D

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
