### ISSUE TITLE
Add Logo for Awesome-selfhosted

### ISSUE THREAD

**Issue by WebSnke** [awesome-selfhosted/awesome-selfhosted#3488]
Awesome-selfhosted doesn't seem to have a logo yet.
I suggest we could ask the creator of the logo for r/selfhosted if we could use it or create our own.

Thanks
WebSnke

**Comment by Waltvinny** [comment]
> Awesome-selfhosted doesn't seem to have a logo yet.
> 
> I suggest we could ask the creator of the logo for r/selfhosted if we could use it or create our own.
> 
> 
> 
> Thanks
> 
>
