### ISSUE TITLE
Add note about unmaintained projects

### ISSUE THREAD

**Issue by sarmong** [awesome-selfhosted/awesome-selfhosted#3499]
I've noticed that a lot project in the list have not been maintained for some time. 
I believe, it would be good improvement to add a symbol (like `⚠` now for anti-features ) to project that have not been committed to for more than 6 months.

**Comment by KieranRobson** [comment]
Any project that hasn't been committed too for 6-12 months, should just be removed

Feel free to list your findings or create a PR to remove them

**Comment by sarmong** [comment]
Yeah, I thought about removing them completely, but (1) the app may still be totally usable (especially if it's a smaller program) and (2) it may encourage some people to fork the abandoned project or just take inspiration from it to create there own. Otherwise, they will be just forgotten and never to be found.

For example, projects like kanboard or miniflux are said to be in a 'maintenance mode', so I wouldn't be surprised if they don't get a commit for a 6 months at some point.

Or, if you think, there is still no place for abandoned projects in this list, perhaps, there can be a date at which a user notice is added and a second date at which it is totatlly removed from the list.

**Comment by nodiscc** [comment]
> a lot project in the list have not been maintained for some time.

**Which ones?** This is not the first time it's mentioned, but people never give actual examples.

> add a symbol to project that have not been committed to for more than 6 months.

These projects should be removed completely unless:

> the app may still be totally usable (especially if it's a smaller program)

There can be exceptions on a case-by-case basis. Sure, very simple programs with no dependencies can be left unmaintained for a long time. But the vast majority of programs here need basic maintenance, such as updating dependencies, responding to security-related issues, triaging bugs... It may still be "usable" but this list is supposed to list only good quality projects, and projects with zero maintenance do not fit here (actually we have very few "quality" requirements, this is basically the only one).

> it may encourage some people to fork the abandoned project or just take inspiration from it to create there own.

This is out of scope for this list (it's not awesome-abandoned-software after all :) ). If you want to maintain a list of projects looking for maintainers we will gladly link to it in [External Links](https://github.com/awesome-selfhosted/awesome-selfhosted#external-links), but even that requires some maintenance/periodic checks. You can parse the commit log for [remove](https://github.com/awesome-selfhosted/awesome-selfhosted/search?q=remove&type=commits) if you want to keep an eye on projects being removed.

> projects like kanboard or miniflux are said to be in a 'maintenance mode', so I wouldn't be surprised if they don't get a commit for a 6 months at some point.

Those projects still get regular updates by their maintainers, so until a 6 months period without any update happens, this is not a valid concern. These projects use Go and PHP package managers so at the very least, maintainers need to keep their dependencies updated (which they currently do).

> perhaps, there can be a date at which a user notice is added and a second date at which it is totatlly removed from the list.

This is too much manual maintenance for the current markdown-based list, note that these checks are partially automated through https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions (there are bugs though https://github.com/nodiscc/hecat/issues/53), and once I finish it and we get an automatically generated list, projects not updated for > 6 months will be displayed with a warning, and projects not updated for > 12 months will not pass at all.

**Comment by sarmong** [comment]
>Which ones? This is not the first time it's mentioned, but people never give actual examples.

Here are the ones just from a few categories I had to recently look into.

https://github.com/schollz/cowyo
https://github.com/claudioc/jingo
https://github.com/moinwiki/moin-1.9
https://github.com/ryanlelek/Raneto
https://git.mills.io/prologic/wiki
https://wikiss.tuxfamily.org/ (https://svnweb.tuxfamily.org/listing.php?repname=wikiss/svn&path=%2F&sc=0) - 2009!!

https://github.com/m1k1o/blog
https://github.com/danpros/htmly

https://git.mills.io/prologic/golinks

https://github.com/manusa/isotope-mail
https://github.com/mailcare/mailcare
https://github.com/mailpile/Mailpile

https://github.com/drichard/mindmaps

https://github.com/m0ngr31/DailyNotes
https://github.com/dnote/dnote
https://github.com/georgeOsdDev/markdown-edit/
https://github.com/pereorga/minimalist-web-notepad
https://github.com/larspontoppidan/notesntodos
https://github.com/kensanata/oddmuse
https://github.com/FoxUSA/OpenNote
https://github.com/alextselegidis/plainpad
https://github.com/mixmark-io/turndown

https://github.com/phntxx/dashboard
https://github.com/pawelmalak/flame
https://github.com/tomershvueli/homepage
https://github.com/jmztaylor/homelab_proxy

https://github.com/jaesivsm/JARR
https://github.com/tontof/kriss_feed
https://github.com/toxinu/leselys
https://github.com/moonmoon/moonmoon
https://github.com/Kombustor/rss-fulltext-proxy
https://git.herrbischoff.com/screaming-liquid-tiger/
https://github.com/sismics/reader

**Comment by nodiscc** [comment]
Thank you, we should definitely look into these. At least some of them have gone undetected by the automated linter/maintenance tool because of the unreliability of the `updated_at/pushed_at` Github API value I mentioned above. Example:

- https://github.com/schollz/cowyo: Last commit 14 May 2020, Github API [`updated_at: '2022-12-28'`](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/cowyo.yml#L13)

In the mean time feel free to send pull requests to remove them from the list.

**Comment by sarmong** [comment]
I think `updated_at` will be updated on each activity, e.g. someone opening an issue.

I haven't looked deeply into the github api, but perhaps [commit endpoint](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28) would be more useful?

**Comment by nodiscc** [comment]
> I think updated_at will be updated on each activity, e.g. someone opening an issue.

This is why I switched to `pushed_at` (even if the key in https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/cowyo.yml#L13 is still named `updated_at`, it's actually the value from `pushed_at`). But even that is not reliable.

> perhaps [commit endpoint](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28) would be more useful?

I think I will end up using that, if it's possible to get the date of the latest commit to the default branch without too many requests/hitting the API rate limit which is [5000 requests/hour](https://docs.github.com/en/rest/rate-limit?apiVersion=2022-11-28)

-> https://github.com/nodiscc/hecat/issues/53

**Comment by nodiscc** [comment]
Related https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3019

**Comment by nodiscc** [comment]
After switching to the latest commit date as indicator of the latest update date (https://github.com/nodiscc/hecat/pull/71), I am now getting these results for projects that have not been updated for > a year (I will keep improving the output and working towards automating the process even more, as part of https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038 / https://github.com/awesome-selfhosted/awesome-selfhosted-data):

```
0bin: last updated -661 days, 7:25:25.101132 ago, older than 365 days
411: last updated -1321 days, 7:25:25.100900 ago, older than 365 days
Abilian SBE: last updated -527 days, 7:25:25.100817 ago, older than 365 days
Babelfish: last updated -426 days, 7:25:25.100424 ago, older than 365 days
Beehive: last updated -401 days, 7:25:25.100300 ago, older than 365 days
cartulary: last updated -979 days, 7:25:25.099910 ago, older than 365 days
Cowyo: last updated -979 days, 7:25:25.099764 ago, older than 365 days
Croodle: last updated -721 days, 7:25:25.099682 ago, older than 365 days
Cubiks-2048: last updated -3147 days, 7:25:25.099616 ago, older than 365 days
Digital-Currency: last updated -658 days, 7:25:25.099326 ago, older than 365 days
Dispatch: last updated -369 days, 7:25:25.099245 ago, older than 365 days
dogbin: last updated -978 days, 7:25:25.099143 ago, older than 365 days
dyu comments: last updated -1459 days, 7:25:25.099071 ago, older than 365 days
EasyQuickImport: last updated -619 days, 7:25:25.099002 ago, older than 365 days
Enigma Reloaded: last updated -499 days, 7:25:25.098863 ago, older than 365 days
Episodes: last updated -1235 days, 7:25:25.098815 ago, older than 365 days
EpochTalk: last updated -617 days, 7:25:25.098767 ago, older than 365 days
fiche: last updated -1490 days, 7:25:25.098473 ago, older than 365 days
Flox: last updated -964 days, 7:25:25.098251 ago, older than 365 days
FriendsRadio: last updated -1927 days, 7:25:25.098161 ago, older than 365 days
Glosa: last updated -695 days, 7:25:25.097952 ago, older than 365 days
goBrowser: last updated -1820 days, 7:25:25.097881 ago, older than 365 days
graph-vl: last updated -693 days, 7:25:25.097674 ago, older than 365 days
Groove Basin: last updated -684 days, 7:25:25.097599 ago, older than 365 days
Hapttic: last updated -1421 days, 7:25:25.097500 ago, older than 365 days
Hauk: last updated -659 days, 7:25:25.097407 ago, older than 365 days
homebank-converter: last updated -804 days, 7:25:25.097219 ago, older than 365 days
Homepage by tomershvueli: last updated -619 days, 7:25:25.097116 ago, older than 365 days
IronFunctions: last updated -1612 days, 7:25:25.096756 ago, older than 365 days
Jmz HomeProxy: last updated -590 days, 7:25:25.096667 ago, older than 365 days
Leselys: last updated -777 days, 7:25:25.096362 ago, older than 365 days
MailForm: last updated -571 days, 7:25:25.096112 ago, older than 365 days
MapBBCodeShare: last updated -804 days, 7:25:25.095991 ago, older than 365 days
Microgit: last updated -897 days, 7:25:25.095738 ago, older than 365 days
microproxy: last updated -382 days, 7:25:25.095689 ago, older than 365 days
Mindmaps: last updated -624 days, 7:25:25.095638 ago, older than 365 days
mkaczanowski pastebin: last updated -532 days, 7:25:25.095477 ago, older than 365 days
ML Workspace: last updated -422 days, 7:25:25.095427 ago, older than 365 days
Mopidy MusicBox: last updated -939 days, 7:25:25.095354 ago, older than 365 days
myDrive: last updated -623 days, 7:25:25.095283 ago, older than 365 days
Notes'n'Todos: last updated -586 days, 7:25:25.095082 ago, older than 365 days
oTranscribe: last updated -1352 days, 7:25:25.094786 ago, older than 365 days
pb: last updated -1030 days, 7:25:25.094470 ago, older than 365 days
Posio: last updated -461 days, 7:25:25.094243 ago, older than 365 days
Re:Backlogs: last updated -925 days, 7:25:25.093849 ago, older than 365 days
Redbird: last updated -838 days, 7:25:25.093745 ago, older than 365 days
RSS Fulltext Proxy: last updated -1260 days, 7:25:25.093472 ago, older than 365 days
s3server: last updated -853 days, 7:25:25.093198 ago, older than 365 days
Shaark: last updated -749 days, 7:25:25.092540 ago, older than 365 days
SharpPaste: last updated -1356 days, 7:25:25.092379 ago, older than 365 days
Simple-URL-Shortener: last updated -743 days, 7:25:25.092204 ago, older than 365 days
Snapcast: last updated -392 days, 7:25:25.092093 ago, older than 365 days
Snippet Box: last updated -461 days, 7:25:25.092038 ago, older than 365 days
snipt: last updated -628 days, 7:25:25.091985 ago, older than 365 days
socks5-proxy-server: last updated -592 days, 7:25:25.091932 ago, older than 365 days
SOCKS5Engine: last updated -1346 days, 7:25:25.091860 ago, older than 365 days
sovereign: last updated -664 days, 7:25:25.091748 ago, older than 365 days
Stikked: last updated -1151 days, 7:25:25.091657 ago, older than 365 days
Tabby: last updated -368 days, 7:25:25.091485 ago, older than 365 days
tasks.php: last updated -2444 days, 7:25:25.091388 ago, older than 365 days
Tasks: last updated -1331 days, 7:25:25.091337 ago, older than 365 days
untrusted: last updated -369 days, 7:25:25.091046 ago, older than 365 days
updog: last updated -1064 days, 7:25:25.090982 ago, older than 365 days
WebUI-aria2: last updated -504 days, 7:25:25.090664 ago, older than 365 days
ytdl-webserver: last updated -1194 days, 7:25:25.090334 ago, older than 365 days
```

As for projects that have not been updated in > 6 months:

```
Airsonic Advanced: last updated -207 days, 7:25:25.100689 ago, older than 186 days
asciinema: last updated -264 days, 7:25:25.100568 ago, older than 186 days
Bicimon: last updated -278 days, 7:25:25.100214 ago, older than 186 days
DailyNotes: last updated -343 days, 7:25:25.099534 ago, older than 186 days
Dashboard: last updated -207 days, 7:25:25.099453 ago, older than 186 days
EdPaste: last updated -288 days, 7:25:25.098936 ago, older than 186 days
Excision Mail: last updated -220 days, 7:25:25.098631 ago, older than 186 days
filite: last updated -334 days, 7:25:25.098391 ago, older than 186 days
Flame: last updated -299 days, 7:25:25.098340 ago, older than 186 days
Hextris: last updated -344 days, 7:25:25.097279 ago, older than 186 days
HRCloud2: last updated -271 days, 7:25:25.097000 ago, older than 186 days
ImageStore: last updated -278 days, 7:25:25.096871 ago, older than 186 days
KChat: last updated -328 days, 7:25:25.096496 ago, older than 186 days
Marauder: last updated -236 days, 7:25:25.095940 ago, older than 186 days
Mejiro: last updated -240 days, 7:25:25.095855 ago, older than 186 days
minimalist-web-notepad: last updated -261 days, 7:25:25.095565 ago, older than 186 days
MyPaas: last updated -356 days, 7:25:25.095233 ago, older than 186 days
OpenNote: last updated -290 days, 7:25:25.094864 ago, older than 186 days
Party Poker: last updated -211 days, 7:25:25.094665 ago, older than 186 days
pasty: last updated -353 days, 7:25:25.094593 ago, older than 186 days
Patrowl: last updated -344 days, 7:25:25.094523 ago, older than 186 days
PurritoBin: last updated -282 days, 7:25:25.094168 ago, older than 186 days
pyShelf: last updated -303 days, 7:25:25.094084 ago, older than 186 days
Radium: last updated -278 days, 7:25:25.093938 ago, older than 186 days
reduc.io: last updated -327 days, 7:25:25.093659 ago, older than 186 days
ReducePy: last updated -290 days, 7:25:25.093605 ago, older than 186 days
schnack: last updated -204 days, 7:25:25.092787 ago, older than 186 days
schort: last updated -280 days, 7:25:25.092726 ago, older than 186 days
Screensy: last updated -253 days, 7:25:25.092668 ago, older than 186 days
Share: last updated -252 days, 7:25:25.092447 ago, older than 186 days
SocksBin: last updated -316 days, 7:25:25.091806 ago, older than 186 days
vaults: last updated -221 days, 7:25:25.090874 ago, older than 186 days
Word Mastermind: last updated -340 days, 7:25:25.090546 ago, older than 186 days
YoutubeDL-Material: last updated -192 days, 7:25:25.090398 ago, older than 186 days
```

> There can be exceptions on a case-by-case basis. Sure, very simple programs with no dependencies can be left unmaintained for a long time. 

Example at https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3505. I will find a manageable way to add exceptions.

I will now move this to https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2266 which used to be the dedicated issue to track unmaintained projects.

When the switch to YAML-backed data is complete (I don't want to rush this), an enhanced HTML version will be made available, including additional data such as last update dates, number of stars, etc. (https://github.com/nodiscc/hecat/issues/28, https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3019).

Thanks @sarmong for the heads up and for providing examples.
