### ISSUE TITLE
Self Hosted alternative to "submit.as" ? 

### ISSUE THREAD

**Issue by komali2** [awesome-selfhosted/awesome-selfhosted#3508]
I've looked through all the CMS projects available and didn't find out that fulfills a requirement I'm looking for for a local nonprofit: anonymous content submission. They're considering https://submit.as/ but the pricing is relatively restrictive and so I'm trying to find something we can just host on our own. The only alternative so far I've found is allowing anonymous submissions on a wordpress site, which could be a path we go down. 

Are they any other alternatives people are aware of? If it's something already in the repository, perhaps "guest submission" or "collect submissions" or "no-signin submission" could be a feature added to the description to said software.

**Comment by nodiscc** [comment]
You are unlikely to get any answers here, the issue tracker is only used for issues directly related to the awesome-selfhosted project. I suggest posting your question to https://www.reddit.com/r/selfhosted/ instead.
