### ISSUE TITLE
Add Floccus bookmarks synchronization

### ISSUE THREAD

**Issue by neerro** [awesome-selfhosted/awesome-selfhosted#3543]
The project link on GitHub:
https://github.com/floccusaddon/floccus

**Comment by nodiscc** [comment]
> https://floccus.org/guides/
> Sync via Nextcloud Bookmarks, Google Drive or any WebDAV-compatible service

It's a browser add-on which relies on separate server software to take care of the actual synchronization. There is already good precedent that we don't list those here ([example](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/973)), else we would need to add every software whose data can be synchronized by moving around files.

> This is a list of Free Software network services and web applications which can be hosted on your own server(s).

**Comment by justingoldberg** [comment]
But isn't this repo called self-_hosted_? Or are these generally not included because there's nothing novel other than "putting a file up on webdav"?
