### ISSUE TITLE
Move back items from awesome-analytics, remove delegation

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#3575]
https://github.com/newTendermint/awesome-analytics is no longer actively maintained, even simple cleanup/formatting PRs sit without reviews for months (e.g. https://github.com/newTendermint/awesome-analytics/pull/147).

So we should undo the changes from https://github.com/awesome-selfhosted/awesome-selfhosted/commit/41f6cbc0f7a75656ae2b9f128115b64f559a201a https://github.com/awesome-selfhosted/awesome-selfhosted/commit/59f77b35c99275b57774b3977180d1e3f7a5595f https://github.com/awesome-selfhosted/awesome-selfhosted/commit/176190ce2b5b67cd9de8e7f4771405b3bd81e4f2 https://github.com/awesome-selfhosted/awesome-selfhosted/commit/811d9337e83776a7ff1778b7e985c23173a84f61 https://github.com/awesome-selfhosted/awesome-selfhosted/commit/74ee775fccfe45cf659909eb0af5f1dbc1bbb029 https://github.com/awesome-selfhosted/awesome-selfhosted/commit/0eeb15c9d6e5008354a9a01a3904dd50e64fab79 and replace the **Please visit** delegation link with `See also`.

To revert the change `git revert` could be used or (probably simpler) we could just grep for `Self-Hosted` in https://raw.githubusercontent.com/newTendermint/awesome-analytics/c61fa76e3748f837cbe40cb6d1134386f1192fa1/README.md

**Comment by luckydonald** [comment]
That's great.
Especially since searching for selfhosted there was annoying, as commercial products mixed with them.
