### ISSUE TITLE
Allowing "plugins" that compare well with standalone alternatives

### ISSUE THREAD

**Issue by pulsejet** [awesome-selfhosted/awesome-selfhosted#3589]
Following from the discussion in #3587 

### Premise

This list doesn't currently allow "plugins", for example Nextcloud apps or Wordpress plugins. The reason is that this would duplicate other lists such as the Nextcloud [app store](https://apps.nextcloud.com).

### Discussion

Some of these "plugins" are fully featured software suites that compare well against others on this list. For instance, [Memories](https://github.com/pulsejet/memories) compares very well against all other photo management suites.

I want to propose allowing such "plugins" here, considering the following:

1. The purpose of this list is to help self-hosters find the software suite best suited for them. Having all comparable alternatives together makes it easier to pick and choose one. For instance, someone wanting to store photos is not going to automatically consider Nextcloud and hence look for relevant apps on the store. 
1. I am assuming another purpose of this list is providing visibility to open source projects to interested users, so just because it is listed elsewhere should not be a criteria for rejection.
1. It is arguably hard to decide on the basis of quality. At the same time, it won't exactly be appropriate if a poorly built weekend project ends up here (it's just noise), so there is some _implicit_ quality filter. A good measure of whether a plugin could be here is to see whether it roughly compares well to other alternatives in the same category.

Note: some criteria are obvious.
1. Plugins that are minor functionality extensions don't belong here. For example, a plugin that makes Wordpress faster or changes the background in Nextcloud.
2. Plugins for integrations also don't belong here. If something can be run outside Wordpress/Nextcloud, it's plugin is irrelevant.
3. Any others?

A few other examples of Nextcloud "apps" that are very standalone-comparable:
1. [Cookbook](https://apps.nextcloud.com/apps/cookbook), a recipe book. This is a good example -- it has nothing to do with data storage so someone looking for this isn't going to consider Nextcloud and look for it there.
2. [PhoneTrack](https://apps.nextcloud.com/apps/phonetrack), a phone tracker.
3. [Cospend](https://apps.nextcloud.com/apps/cospend), a budget tracker.

**Comment by tstdin** [comment]
I would be in favour of allowing at least *some* extensions/plugins/companion apps on the list. Memories is a great example why this change would be beneficial.

I was looking for a self-hosted alternative to Google Photos for a long time, trying various popular options in the category like Photoprism (recently Immich also gained some traction). During my research I came across this list, but Memories was not there and it would save me some time searching. That's why I tried adding it (#3584) to help others. (I am not affiliated with the project or its author).

 If I would try to be as objective as possible, I would say it is in the top 3 in its category (with no specific order, everyone has different expectations and needs). Since I am already using Nextcloud, it is a great fit for me, others might end up using something different. But I believe they should at least get to know all available options.

**Comment by pulsejet** [comment]
@nodiscc any more thoughts on this?

**Comment by nodiscc** [comment]
Sorry for the delay, I wanted to address this with a proper reply, but didn't have time yet. I agree with some points and disagree with some others.

> there is some implicit quality filter

That's the main point I disagree with. There is none, you will definitely find weekend-project-quality projects in the list. I'm afraid broadening the scope of the list will make this problem worse (and I have no good solution currently, as too strict quality requirements would also affect usefulness of the list, and are hard to define and enforce. See https://github.com/awesome-foss/awesome-sysadmin/issues/460 for a related experiment). This is a topic for another issue.

The examples you give are good, and in my opinion worth listing here.

We should give it a try. I'll reopen https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3587 and leave this issue open for a while, we can come back to it later and update it with the results of this experiment.

Additional advice is welcome.

**Comment by pulsejet** [comment]
Sounds good.

> That's the main point I disagree with. There is none, you will definitely find weekend-project-quality projects in the list.

I see. In that case many of these might get filtered out by virtue of being unmaintained?

**Comment by nodiscc** [comment]
No major problems since this decision was made 5 months ago. Closing.
