### ISSUE TITLE
What does the ⚠ mean?

### ISSUE THREAD

**Issue by b-** [awesome-selfhosted/awesome-selfhosted#3667]
Perhaps I'm a little obtuse, but I have no idea what this symbol means on this site. (Caution, obviously, but what does that mean? Should I assume entries in the list marked with a caution sign are insecure/have known security vulnerabilities?)

Could I please ask what it means, and if you could put that more clearly on the main .md file?

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted#anti-features

>  `⚠` - Depends on a proprietary service outside the user's control

**Comment by b-** [comment]
Thanks!
