### ISSUE TITLE
Add DashMachine to Personal Dashbords

### ISSUE THREAD

**Issue by BCschwifty** [awesome-selfhosted/awesome-selfhosted#3672]
https://github.com/rmountjoy92/DashMachine

I spent a long time looking nice dashboards and i use this along with awesome sysadmin a lot and i feel like a lot of people would really enjoy this repo.

Points to include:
easy set up with docker.
Entire page is editable with yaml and the build offers pre-built solutions for most of the common self hosted web apps.
also offer custom cards for the more advanced yaml users.

not taking any credit for the repo all credit is to @rmountjoy92

**Comment by BadCo-NZ** [comment]
I used DashMachine back in 2020, it is basically dead now though.

![IMG_20230327_132846](https://user-images.githubusercontent.com/50016048/227815079-88bab4fa-32b4-4e32-8392-4c55a9e37aa0.jpg)

**Comment by nodiscc** [comment]
Unmaintained since 2020 https://github.com/rmountjoy92/DashMachine

**Comment by BCschwifty** [comment]
thats unfortunate. i just discovered it and i am using it for my self as Yml comes naturally as I'm a huge Home Assistant user.

**Comment by BadCo-NZ** [comment]
> thats unfortunate. i just discovered it and i am using it for my self as Yml comes naturally as I'm a huge Home Assistant user.

I agree with your statements, however Homepage is the best I have found. Great community support, built in icons, yaml based.

https://github.com/benphelps/homepage
