### ISSUE TITLE
add https://github.com/easy-wi/developer/ to Utilities for managing game servers.

### ISSUE THREAD

**Issue by Pr0mises** [awesome-selfhosted/awesome-selfhosted#3692]
EasyWI is a PHP7.4 based web server panel which uses symlinks to mitigate storage space for multiple servers and provides clan as well as server lent functionality.

PHP8.0 implementation is not yet stable due to missing testers...

I'm using it for years, the base and its functionalities are awesome and with more popularity it can even get better with more contributors.

**Comment by LancealotSeven** [comment]
GitHub Is Not A Game Does Not Work That Way Either,'Got to real life Just Get An Emaculator,'Focus,'Focus''
