### ISSUE TITLE
Add Jauth to Proxy

### ISSUE THREAD

**Issue by Jipok** [awesome-selfhosted/awesome-selfhosted#3694]
https://github.com/Jipok/Jauth
Lightweight SSL/TLS reverse proxy with authorization(via Telegram and SSH) for self-hosted apps.

I am an author. Although I myself have been using this for almost two years, I published it on github only today. Is it acceptable to add this?

**Comment by CeyHun118** [comment]
Prınt

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
