### ISSUE TITLE
Add Silverwind to Proxy.

### ISSUE THREAD

**Issue by lsk569937453** [awesome-selfhosted/awesome-selfhosted#3734]
https://github.com/lsk569937453/silverwind
High-performance and Lightweight Http/Https/Websocket/Websocket+Tls/Grpc/Grpc+Tls reverse proxy with authorization/ipAllowDenyList/rate-limiting/health check for self-hosted apps.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
