### ISSUE TITLE
Simplify licenses

### ISSUE THREAD

**Issue by stokito** [awesome-selfhosted/awesome-selfhosted#3753]
The list has a license for each item which is great. The problem is that there is to many of them and this makes choise more difficult (at least for me):
* BSD 2,3,4 clauses are really the same. And ISC and MIT too. Mozilla MPL has some additions as far I remember but it should be essencially the same.
* Beerware, WTFPL are not even a real licenses. They are replacable with 0BSD.
* some project specific Sendmail, zlib are probably can be replaced with identical well known.
* CC familiy of licenses that has dozen of variations and not clear what's they mean.
* EU public license is something that sounds really questionable.
* "GPL2 or latter" is really a mess and projects should clearly say that they are ether 2 or 3 version.  Since terms of v3 changed significantly this makes it complitely different license than v2.

I'm not an expert in licensing qnd really even don't want to spend my time on this. But regular users are know even less than me. Likelly they won't need to know this because they won't change anything.
But still they should know which rights and restrictions they have.

Just a hour ago I had to explain in some chat that the new Umbrel.com selfhosting solution is not really an open source/free/libre. And once a guy understood what I mean and how it's important he decided to take a look on the awesome list.
To make a choise easier the licenses should be clear as possible.

**Comment by nodiscc** [comment]
> BSD 2,3,4 clauses are really the same. And ISC and MIT too [...]

They are not, read the actual license text. All Free Software licenses are "identical" in the way that they grant the essential freedoms defined in the DFSG. They may grant additional rights or obligations, which are defined in each license text.

> Beerware, WTFPL are not even a real licenses.

They are. https://spdx.org/licenses/Beerware.html, https://spdx.org/licenses/WTFPL.html.

> some project specific Sendmail, zlib are probably can be replaced with identical well known.

These license's terms are specific and, as such, "replacing" them with other licenses in this list would be incorrect.

> CC familiy of licenses that has dozen of variations and not clear what's they mean.

https://en.wikipedia.org/wiki/Creative_Commons_license#Four_rights

> EU public license is something that sounds really questionable.

EUPL is well-known, has its own Wikipedia page, why would it be "questionable"?

> "GPL2 or latter" is really a mess and projects should clearly say that they are ether 2 or 3 version. 

The `*-or-later` suffix should only be used when the project's license contains "or any later version". In opposition the `-only` suffix must be used when this sentence is not present. But I agree this is tedious to maintain, and in some occasions the license tag here is probably incorrect. AGPL-3.0 had the same problem, which is why in https://github.com/awesome-selfhosted/awesome-selfhosted/commit/71b8b22fd519613de4691f410576a22f26a7a5b8 I removed all `-only/-or-later` suffixes and we now simply use `AGPL-3.0`. Feel free to send a Pull Request that does the same for `GPL-*` licenses.

> I'm not an expert in licensing qnd really even don't want to spend my time on this. But regular users are know even less than me. Likelly they won't need to know this because they won't change anything.

They need to know that software listed here is actually Free/Libre, and that we have actually checked that it is the case. Having license tags is a good way to do that. Some licenses are very similar, while some others are very specific and different (the most widely used license "families" are probably BSD/MIT and GPL-like licenses, but there are others. AGPL-like licenses, or CC0-like for example). Labeling the software with the actual license is cleaner and easier to maintain that establishing some sort of "equivalence table" which will inevitably be incorrect/misleading.

>  To make a choise easier the licenses should be clear as possible.

Aside from removing the `-only/-or-later` suffixes as I suggested, there is not much we can do. Licensing is a complex subject, as is copyright/intellectual property law in most countries. We could add a link to these websites, which are good starting points to understand Free Software licences:
- https://www.tldrlegal.com/
- https://choosealicense.com/licenses/
- https://blog.codinghorror.com/pick-a-license-any-license/

**Comment by stokito** [comment]
Thank you @nodiscc for the detailed response, you made a lot clear for me. So the last evening I spent to learn about licenses.


I think that it would be better to make a strict requirement by licenses:

0. Only Libre/Free/Open Source e.g. no to Creative Commons and/or Public Domain
1. Clear and explicitly approved by OSI (or FSF?) e.g no to WTFPL, Unlicense, Beerware.
3. [Not related but...] Recommend to authors to use a well known license e.g. Change Artistic to GPL like I [did here](https://github.com/yuki-kimoto/gitprep/issues/150#issuecomment-1522879514). I'll try to continue with this in a spare time.

My motivation is this: imagine that you are a vegan and visited a vegan shop. And you expect that everything will be non GMO and natural etc. But here on the shelf some product with some animal fat and you bought it. By default you weren't expected this. Or you are in pharmacy and bought a snake oil by mistake. This is kind of fraud.

Here is the same. Most people who care about self hosting have the same motivation as open source movements care about.



The Beerware, WTFPL and Unlicense do have some problems and is not approved explicitly or recommended by OSI.
* https://en.wikipedia.org/wiki/Beerware
* https://habr.com/ru/articles/243091/#WTFPL (in Russian but detailed)
* https://habr.com/ru/articles/402695/#comment_18126373

Likely there is no any project in the list with the Beerware but few projects with the WTFPL and Unlicense. 
When you creating a project on Github the following list of licenses is suggested:
- Apache License 2.0
- GNU General Public License v3.0
- MIT License
- BSD 2-Clause "Simplified" License
- BSD 3-Clause "New" or "Revised" License
- Boost Software License 1.0
- Creative Commons Zero v1.0 Universal
- Eclipse Public License 2.0
- GNU Affero General Public License v3.0
- GNU General Public License v2.0
- GNU Lesser General Public License v2.1
- Mozilla Public License 2.0
- The Unlicense

I think this is a fair list of "well known" licenses. But The Unlicense here should be removed and this it was malicious to add it the list.

The EUPL or any other public domain licenses like CC0 or 0BSD aren't recommended too and may not work in some countries.

The entire family of CC is not open source except of CC0 which considered bad for software. I'll ask the CC projects listed here to switch to some other license.

Basically from what I understand there is few categories of licenses:
1. Public Domain: 0BSD (it works for USA but may not for other countries
2. Permissive: BSD style, ISC, MIT, Apache
3. Copyleft but permissive for use: GPLv2, LGPL, MPL
4. "Libre" e.g. restrictive copyleft: GPLv3, AGPL
5. "Some Rights Reserved": Creative Commons
6. Free for noncommercial usage: https://polyformproject.org/licenses/ , [SSPL](https://en.wikipedia.org/wiki/Server_Side_Public_License) 
7. Something when sources just opened but you have no rights (I remember Delphi VCL was like that)
8. Closed sources but free to use, Proprietary etc.


This is categories that I noted for myself. I don't know how this is correct. But my main idea is that as a regular user I need to know to which group it belongs too. That's why I asked if we can reduce license names. This is probably something that is better to discuss with OSI to ask them to declare some categories to help users.

**Comment by nodiscc** [comment]
> Only Libre/Free/Open Source

That is already the case, unless you can demonstrate that one of licenses here is actually non-Free. To my knowledge, all the licenses presented on the list grant all freedoms required by widely accepted definitions of Free and Open-Source Software [[1]](https://opensource.org/osd) [[2]](https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines)

> no to Creative Commons and/or Public Domain [...] no to WTFPL, Unlicense, Beerware.
> But The Unlicense here should be removed and thus it was malicious to add it to the list.

It would be unfair to exclude these licenses based on some made up criteria, even though I prefer strong [Copyleft](https://en.wikipedia.org/wiki/Copyleft) licenses myself, these licenses **are** Free/Libre. Regarding [Unlicense](https://en.wikipedia.org/wiki/Unlicense) for example:

>> The Free Software Foundation states that "Both public domain works and the lax license provided by the Unlicense are compatible with the GNU GPL." However, for dedicating software to the public domain it recommends CC0 over the Unlicense, stating that CC0 "is more thorough and mature than the Unlicense".[[1]](https://en.wikipedia.org/wiki/Unlicense#cite_note-fsf_unlicense-1)

> Clear and explicitly approved by OSI (or FSF?)

OSI/FSF approval is not required for a license to be Free, all that is required is that the license grants essential freedoms described in the links above. The [SPDX license table](https://spdx.org/licenses/) further confirms that the licenses you mentioned are Free, even if not OSI-approved.

If OSI publishes a statement that contests the validity of a license as FOSS, with strong arguments, we will remove it (it already happened [[1]](https://blog.opensource.org/the-sspl-is-not-an-open-source-license/) [[2]](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2689)) .

> The public domain, EUPL or licenses like CC0 or 0BSD aren't recommended too and may not work in some countries.

True, but again, this is not our problem, all that is required is that the essential freedoms are granted. To know if a license has legal validity in a specific country, you should consult a specialized lawyer.

> Public Domain, Permissive, Copyleft, Strong Copyleft [...]  my main idea is that as a regular user I need to know which group it belongs to.

Then you need to read about Free Software licensing (the very first link in the header), get familiar with each license "family", and learn for yourself, there is no shortcut. Classifying licenses is out of scope for this project. At most we could include links to the "TL;DR" pages I mentioned. I agree that knowing the differences between licenses "families" has its importance, but it is out of scope for this project. All that matters is that the licenses are Free.

> Recommend to authors to use a well known license e.g. Change Artistic to GPL like I did here. I'll try to continue with this in my spare time.

:+1: 

So, the only actionable items that remain here (PR welcome) are
- [ ] add https://www.tldrlegal.com/, https://choosealicense.com/licenses/  to https://github.com/awesome-selfhosted/awesome-selfhosted#external-links
- [ ] Open a separate issue if you'd like to contest the validity of a specific license (backed by strong evidence)
- [ ] Remove remaining `-only` and `or-later` suffixes

**Comment by stokito** [comment]
thank you, you convinced me. I don't feel like the action items are so important so I'll close the ticket.

**Comment by stokito** [comment]
JFYI: I sent the letter to FSF:


Hello dear Licensing Team,

On the Licenses List there are a lot of licenses with a short comment and clear indication if the license is approved by FSF
https://www.gnu.org/licenses/license-list.en.html
And I do check all licenses against the list and many other people do too.

Could you please add the 0BSD license to the list? This would make developers and users more confident to use it.
I found the license in fact the only good "Public Domain equivalent": it doesn't use swear words as WTFPL and is not misled by a name as The Unlicense which is in fact a license regardless of its name.
It's approved by Google and used in Android while they don't accept The Unlicense and "non serious" licenses like Beerware.

I'm a proponent of copyleft but still I have to use it.
I have some micro libraries from one file or writing a sample projects that may be just copied and turned into real projects.
And I need a license that does not insist on copying its text because with a high chance it will be simply violated without even knowing.


But the main problem for me is license fragmentation.
As a developer and a user I wish to not spend a lot of time learning licenses and check if they are safe to use.

The Unlicense is very controversial for many and causes discussions and additional questions.
https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

The 0BSD instead is just smaller, doesn't have any mention of the Public Domain and its text is similar to a classical BSD.
So could you please recommend the 0BSD instead of Unlicense? It was even created earlier in 2006 than the Unlicense in 2010.

Similarly could you please mention the WTFPL and recommend to use the 0BSD instead?
The word Fuck may sound more ot less acceptable in English but it's extreemely offensive in many other languages and can't be used in a court.
But there are also other reasons https://cubicspot.blogspot.com/2017/04/wtfpl-is-harmful-to-software-developers.html
The license become extremely popular and even was suggested by one of the StackOverflow founders https://blog.codinghorror.com/pick-a-license-any-license/

GitHub repos stats:
* 0BSD: 56k repos https://github.com/search?q=license%3A0bsd&type=repositories
* Unlicense: 280k repos https://github.com/search?q=license%3Aunlicense&type=repositories
* WTFPL: 27k repos https://github.com/search?q=license%3Awtfpl&type=repositories
The Beerware repos are hard to find because the license is not recognized correctly by GitHub. But I believe there are a lot of them.

In 2015, GitHub reported that approximately 102,000 of their 5.1 million licensed projects (2% of licensed projects on GitHub.com) used the Unlicense.
https://github.blog/2015-03-09-open-source-license-usage-on-github-com/

This happened because The Unlicense was added to a GitHub choiser of license on creation of a new project.
The situation is very bad and may be considered as an attack on the open source movement: to make a bigger fragmentation and poison projects with a questionable license.
Millions of people spent their time learning about yet another license because they simply didn't hear of the 0BSD. Many developers aren't not sure if they can mix it with their projects etc.
And many users who know even less about licenses are being confused. They may have few licenses and if they see "BSD" then they may think "ok, it's familiar for me".

So could you please add the 0BSD to list of licenses https://www.gnu.org/licenses/license-list.en.html
Also add a clear guide to the page https://www.gnu.org/licenses/license-recommendations.html

I also going to ask The Unlicense and WTFPL authors to deprecate it in favor of 0BSD.

Additional materials:
* https://en.wikipedia.org/wiki/0BSD
* https://www.youtube.com/watch?v=MkJkyMuBm3g&t=1528s
* https://github.com/github/choosealicense.com/issues/805#issuecomment-1120979826
* https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3753#issuecomment-1523014745
* People stuck on the WTFPL simply because they never heard of 0BSD https://github.com/dimitri/el-get/issues/474

Regards,
Sergey Ponomarev
