### ISSUE TITLE
Add Cosmos to Proxy

### ISSUE THREAD

**Issue by azukaar** [awesome-selfhosted/awesome-selfhosted#3779]
Reverse proxy with a modern UI and included SSO / Auth

https://github.com/azukaar/cosmos-Server

**Comment by RoFamily** [comment]
Boss

**Comment by kokomo123** [comment]
I would say this can be added to awesome-selfhosted, but there's no license properly set, and in the description it mentions alpha quality, I think we should keep this issue up until there's an appropriate license and it's ready for production use. I'm open to other suggestions on this

**Comment by azukaar** [comment]
Just so I understand, are open sources licences required for this list?

**Comment by kokomo123** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted#license, Well the PR template does require you to have a license and ticking it on the checklist for it to be put on the list, It's up to you to define a license, at least's thats my understanding. nodiscc might have more insight.

**Comment by azukaar** [comment]
But there is a licence in the repo, it's just not fully open source

**Comment by kokomo123** [comment]
Ah, thank you for clarification. My apologies as I didn't get the whole picture, so i'm not sure, whether it would be classified under non-free, or proprietary, etc. @nodiscc any insight on this kind of project where there's no license but it's not fully open source either?

**Comment by nodiscc** [comment]
> there is a licence in the repo, it's just not fully open source

It must be added to https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md

**Comment by kokomo123** [comment]
Thank you, i will add it accordingly to non-free then.

**Comment by Shua55** [comment]
Hi

**Comment by dominatorw** [comment]
Makeing

**Comment by dominatorw** [comment]
Leaves
