### ISSUE TITLE
Add ruptime to status--uptime-pages

### ISSUE THREAD

**Issue by alexmyczko** [awesome-selfhosted/awesome-selfhosted#3800]
https://github.com/alexmyczko/ruptime

**Comment by Lilduvy85** [comment]
> https://github.com/alexmyczko/ruptime

**Comment by alexmyczko** [comment]
@Lilduvy85 Thank you for the detailed in-depth review in the style of https://github.com/kelseyhightower/nocode

@nodiscc is one review enough or do you need more?

**Comment by nodiscc** [comment]
@alexmyczko I think you're responding to a spambot...

It's not very clear to me what this software does/how it works/if there is a central server for metrics collection (maybe the documentation could be improved...).

**Comment by alexmyczko** [comment]
as this is awesome selfhosted, no you run ruptimed and query your own server

**Comment by nodiscc** [comment]
My question was:

> Get an overview of your operating systems and releases  
> Find hosts that have 90%+ usage of either CPU/MEM/GPU/GPUMEM  

How does it know about the list of hosts?

Anyway, this would be a better fit for https://github.com/awesome-foss/awesome-sysadmin#monitoring, please resubmit there, thanks.

**Comment by alexmyczko** [comment]
The clients report to the server, so the server know the hosts.
