### ISSUE TITLE
Add Dify to Software Development - Low Code

### ISSUE THREAD

**Issue by KimSunDolf** [awesome-selfhosted/awesome-selfhosted#3824]
I want to share an AI application platform called [Dify](https://dify.ai/) that can help train text data for you.I hope this tool can be included in this warehouse, because it can also help people with the same needs.

The goal of Dify is to allow developers (even non-developers) to quickly build something useful based on a large language model, and ensure that it is visualized, operable, and improveable.

In other words, you can upload papers in PDF, Markdown, TXT and other text formats and let AI learn the content. After the application is published, it can interact with people based on the uploaded data.

## Practice process

I trained a dedicated chatbot and threw the product documentation of Tencent Cloud CODING DevOps into it, and the effect was good. That is to say, GPT can answer all questions related to its own company's products.

Robot experience address: https://udify.app/chat/F2Y4bKEWbuCb1FTC
Source document address: https://coding.net/help
Training platform: https://dify.ai/
My practice document (official account): https://mp.weixin.qq.com/s/WuFZ3FFcEwPNOcIKQQZsIA
Personal WeChat account: AdolfJobs
Git pull request: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3823

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
