### ISSUE TITLE
Fix / remove broken hyperlinks

### ISSUE THREAD

**Issue by ndsvw** [awesome-selfhosted/awesome-selfhosted#3832]
Hello, I found some broken hyperlinks:
- [ ] https://count.ly (file: README.md, error: ECONNREFUSED)
- [ ] https://demo.alf.io/authentication (file: README.md, error: ECONNRESET)
- [ ] https://git.tt-rss.org/fox/tt-irc (file: README.md, status code: 404)
- [ ] https://join-lemmy.org/ (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://www.papermerge.com (file: README.md, error: DEPTH_ZERO_SELF_SIGNED_CERT)
- [ ] https://transfer.sh (file: README.md, error: ECONNRESET)
- [ ] https://vocascan.com/ (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://memories-demo.radialapps.com/ (file: README.md, status code: 526)
- [ ] http://demo.redmine.org/ (file: README.md, error: ECONNRESET)
- [ ] https://short.swurl.xyz/ (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://git.swurl.xyz/swirl/clink (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://wikiindex.org/Category:Wiki_Engine (file: README.md, status code: 404)

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3558
