### ISSUE TITLE
add ytdl-sub to list

### ISSUE THREAD

**Issue by Code-Slave** [awesome-selfhosted/awesome-selfhosted#3838]
ytdl-sub automates primarily youtube and soundcloud downloads. It has an extensive configuration setup that makes it easy to dl channels as tv shows for plex,kodi,jellyfin.

https://github.com/jmbannon/ytdl-sub

Ive been using it extensively for 6months and it works very well

**Comment by catduckgnaf** [comment]
Absolutely need to add this!

**Comment by nodiscc** [comment]
It's a purely command-line automation tool, we don't list those here. 

> This is a list of [Free](https://en.wikipedia.org/wiki/Free_software) Software [network services](https://en.wikipedia.org/wiki/Network_service) and [web applications](https://en.wikipedia.org/wiki/Web_application)


It looks interesting, but the best course of action is to contact Kodi/Jellyfin maintainers and ask them to add ytdl-sub to the list of community/3rd-party software in their documentations.
