### ISSUE TITLE
Add ShareX php uploader to File Transfer

### ISSUE THREAD

**Issue by RealFascinated** [awesome-selfhosted/awesome-selfhosted#3906]
https://git.fascinated.cc/Fascinated/sharex-php-uploader

A simple PHP script that allows users to upload files and images using ShareX.
I am the project creator and maintainer. I personally use this project running at https://cdn.fascinated.cc/upload.php

**Comment by Rainnny7** [comment]
👍 very nice

**Comment by okNick36** [comment]
I use RealFascinated’s ShareX uploader as my personal custom uploader for ShareX. It works as intended, and it’s very nice.

**Comment by RealFascinated** [comment]
I have updated the repo to be more clear on how to use it and I have added a docker image for ease of use.

**Comment by KieranRobson** [comment]
@RealFascinated See https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3991#issuecomment-1640954623

Could you do the suggested comment so that this PR can move along, if no response is heard, I will close the PR.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
