### ISSUE TITLE
Add SplittyPie

### ISSUE THREAD

**Issue by TheFax** [awesome-selfhosted/awesome-selfhosted#3930]
Please add this free PWA:

https://github.com/tsubik/splittypie/

**Comment by Rabenherz112** [comment]
Hey there, as far as I can see it looks like the project is no longer maintained anymore, with the last update being already 2 years ago. Therefore I don't think it meets the following requirement:
> Any software project you are adding to the list is actively maintained.

But let me know if you think otherwise.
