### ISSUE TITLE
Does an open-source generative ai training framework belong here?

### ISSUE THREAD

**Issue by killian31** [awesome-selfhosted/awesome-selfhosted#3966]
Hi, great work! 
We've developped and are maintaining [joliGEN](https://github.com/jolibrain/joliGEN) at @jolibrain, a generative AI image toolset with GANs and Diffusion for real-world applications, which is self-hosted and open-source (thus free). 

Is it relevant to add it to your great list of self-hosted softwares? 

Thanks.

**Comment by nodiscc** [comment]
> This is a list of [Free](https://en.wikipedia.org/wiki/Free_software) Software [network services](https://en.wikipedia.org/wiki/Network_service) and [web applications](https://en.wikipedia.org/wiki/Web_application)
