### ISSUE TITLE
Add Simple Links - Not sure what category it would fit under.

### ISSUE THREAD

**Issue by RealFascinated** [awesome-selfhosted/awesome-selfhosted#3997]
https://git.fascinated.cc/Fascinated/simple-links

Preview:
![Preview](https://git.fascinated.cc/Fascinated/simple-links/media/branch/master/media/preview.png)

A simple Linktree (and similar) alternative. It is simple to use and lightweight.
If you have any questions, please reply and I will try my best to answer them :)

**Comment by kokomo123** [comment]
I'm assuming it "could" in quotation marks fit under Personal Dashboards due to a link tree alternative already being there, LinkStack.. Or we could shove it into Misc for now?

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
