### ISSUE TITLE
Add ESPHome to Internet of Things

### ISSUE THREAD

**Issue by norahqueen** [awesome-selfhosted/awesome-selfhosted#4008]
ESPHome is a system for controlling ESP32/8266 IoT devices. There are tools for converting some proprietary smart devices to run it.

**Comment by nodiscc** [comment]
> This is a list of [Free](https://en.wikipedia.org/wiki/Free_software) Software [network services](https://en.wikipedia.org/wiki/Network_service) and [web applications](https://en.wikipedia.org/wiki/Web_application)
