### ISSUE TITLE
Should the link to /r/selfhosted be changed from reddit to point to the lemmy community?

### ISSUE THREAD

**Issue by dmfarcas** [awesome-selfhosted/awesome-selfhosted#4009]
Just a shower thought, since a lemmy instance can be hosted by individuals, I feel that it's more appropriate to point it to the [lemmy selfhost community](https://lemmy.world/c/selfhosted). This particular community is becoming quite healthy but any other would be great. Suggestions are more than welcome. 

I, for one, feel a bit dirty when finding useful info on google that is linked to Reddit. Until a few days ago, I used libreddit in order to avoid going to that nasty place. 

I'm just curious on what the community thinks about this. What do you think?

**Comment by nodiscc** [comment]
A this point, the URL in the sidebar points to the selfhosted subreddit for historical reasons. We never had a proper website, but that is about to change with https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038 and https://nodiscc.github.io/awesome-selfhosted-html-preview/. When it is complete, the website's URL will replace the current one that points to reddit.

[This PR](https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3914) added various other communities/links related to self-hosting to the `External links` section. I'm in favor of making `/c/selfhosted` on lemmy.world the first one in this list.

**Comment by nodiscc** [comment]
> I'm in favor of making /c/selfhosted on lemmy.world the first one in this list.

PR at https://github.com/awesome-selfhosted/awesome-selfhosted/pull/4024

Once this gets merged, I will also change the link in the sidebar to point to https://lemmy.world/c/selfhosted until the awesome-selfhosted website is made live (remaining work at https://github.com/nodiscc/hecat/milestone/1 and https://github.com/awesome-selfhosted/awesome-selfhosted-data/milestone/1)
