### ISSUE TITLE
Add ProjectAlice - personal assistant

### ISSUE THREAD

**Issue by HyperCriSiS** [awesome-selfhosted/awesome-selfhosted#4057]
https://github.com/project-alice-assistant/ProjectAlice

Last release was 2021, but development has not stopped.

**Comment by KieranRobson** [comment]
> https://docs.projectalice.io/setup/#which-way
> WARNING This is a beta release! It is subject to change, and the target audience is people with some knowledge of their devices, installing python modules and basic stuff!

Seems to still be in Beta
