### ISSUE TITLE
GLPI ITSM

### ISSUE THREAD

**Issue by DonutsNL** [awesome-selfhosted/awesome-selfhosted#4058]
Please Add GLPI to ticketing/It Service Management. I think it is a well hidden OSS gem.

It supports all major itsm functions and on top offers agent based automated inventory.

https://glpi-project.org

**Comment by nodiscc** [comment]
Already listed at https://github.com/awesome-foss/awesome-sysadmin#it-asset-management, which is linked from https://github.com/awesome-selfhosted/awesome-selfhosted#inventory-management
