### ISSUE TITLE
Add Flame and miniboard to Dashboards

### ISSUE THREAD

**Issue by essys** [awesome-selfhosted/awesome-selfhosted#4073]
In the dashboard category I miss the following projects:

- Flame: [https://github.com/pawelmalak/flame](https://github.com/pawelmalak/flame)
- miniboard: [https://github.com/aceberg/miniboard](https://github.com/aceberg/miniboard)

It would be nice to see these here too, as they are very easy to use and quite lean.

**Comment by essys** [comment]
I just noticed Flame was removed with #3839 as there is barely any development.

**Comment by KieranRobson** [comment]
> MiniBoard was suggested by the developer aceberg with https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3982, but still I don't know why it was not accepted.

The creator of the PR closed this, it did not have the chance to be reviewed. however looking into Miniboard, it would not be accepted due to not meeting the 4 months old requirement.
