### ISSUE TITLE
Add bashupload.com to File Transfer - Single-click & Drag-n-drop Upload

### ISSUE THREAD

**Issue by afzl-wtu** [awesome-selfhosted/awesome-selfhosted#4074]
The great thing about it is it can send and recieve upto 50 GB of files from both terminal and browser.
Here is its github [location](https://github.com/IO-Technologies/bashupload/tree/main)

**Comment by KieranRobson** [comment]
No development activity for 2 years and issues suggesting that it is down

> https://github.com/IO-Technologies/bashupload/issues/14
> https://bashupload.com/
