### ISSUE TITLE
Does my platform Actifisys qualify for awesome-selfhosted?

### ISSUE THREAD

**Issue by danielbrendel** [awesome-selfhosted/awesome-selfhosted#4076]
https://github.com/danielbrendel/dnyActifisys

It is a self-hosted community event platform and social network. It is similar to meetup and the old german Spontacts version. Users and organizations can create upcoming activities where users can participate and discuss them, upload photos, etc. There is also a forum, gallery and basic market place implemented, among many other things. The software can be configured to match any theme, e.g. a gaming (LFG) platform, music platform, spare time platform, etc.

I am the developer and maintainer of the project and I am also using it live for my medieval community platform: https://www.mittelalter-events.com/

Currently there are no detailed install instructions and no release yet, but I just wanted to generally ask if that software qualifies for that list here, because it is not really popular (only a few stars and 1 fork). Also the GUI might not really be that beautiful and I didn't find anything in the contribution guidelines describing requirements of popularity, design, code quality etc.

**Comment by kokomo123** [comment]
Hi there, thanks for your input before creating a PR. There's no popularity, design, code quality guidelines. We just ask to be included in the list, it's mature, it has working, detailed installation instructions, and has a license.

**Comment by danielbrendel** [comment]
Thank you. I'll create a PR when I updated the mentioned things.
