### ISSUE TITLE
Add [Cicada] to [Media Streaming - Audio Streaming]

### ISSUE THREAD

**Issue by mebtte** [awesome-selfhosted/awesome-selfhosted#4084]
[Cicada](https://github.com/mebtte/cicada) is a multi-user music service for self-hosting, It's open source and free. Here is the [repository](https://github.com/mebtte/cicada).

**Comment by KieranRobson** [comment]
>  Any software project you are adding was first released more than 4 months ago.
> https://github.com/mebtte/cicada/graphs/contributors?from=2022-04-05&to=2022-04-28&type=c

Release 1.0.0 was created in June. With Commits picking up in April, I'd say this needs to mature first.
