### ISSUE TITLE
Misc and FaaS & Serverless similars

### ISSUE THREAD

**Issue by vensauro** [awesome-selfhosted/awesome-selfhosted#4085]
on the Miscellaneous have the Caprover and MyPass that are similar to Coolify, Dokku and Kubero on the FaaS & Serverless section.

My suggestion is to make all of them on the same section, maybe another section for PaaS

**Comment by nodiscc** [comment]
Agreed, this section could be cleaned up/split into PaaS ans FaaS sections.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this issue worked on, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.
