### ISSUE TITLE
Awesome Self-Hosted NEEDS an IMAGE!

### ISSUE THREAD

**Issue by ethereal-engineer** [awesome-selfhosted/awesome-selfhosted#4097]
I have been a fan of this collection for many years. It has its own button on my dashboard homepage. I think it's time that it had a logo or image or icon or branding. Something that encompasses the independence, privacy, fun, DIY.... the sheer AWESOME of what this collection is and what it helps others make for themselves.

Also, I'm autistic and really want a good icon to associate with this first rate page on my dashboard. 🤣

**Comment by nodiscc** [comment]
Check out https://github.com/awesome-selfhosted/awesome-selfhosted-data, https://nodiscc.github.io/awesome-selfhosted-html-preview/ and (coming soon) https://awesome-selfhosted.net/
