### ISSUE TITLE
Self-hosted alternative to SplitWise / Tricount?

### ISSUE THREAD

**Issue by david-alvarez-rosa** [awesome-selfhosted/awesome-selfhosted#4126]
Kindly asking for a recommendation for a self-hosted alternative to SplitWise / Tricount?

Any help appreciated :)

**Comment by nodiscc** [comment]
Hi,
please direct your questions to one of the communities listed in https://github.com/awesome-selfhosted/awesome-selfhosted#external-links instead (I recommend https://lemmy.world/c/selfhosted).

I advise giving *way* more details about what the projects you mentioned actually do, what features you expect, your use case, etc.

**Comment by david-alvarez-rosa** [comment]
I see, @nodiscc, acknowledged. Thanks!
