### ISSUE TITLE
Add Minimalist-Online-Markdown-Editor

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted#932]
https://github.com/pioul/Minimalist-Online-Markdown-Editor
This is the simplest and slickest online Markdown editor. http://markdown.pioul.fr
HTML5 / MIT
(Node.js is required to build the application, but not to run it (static HTML/JS)

**Comment by worldworm** [comment]
I like this project, but the last commit ist from 20 Jun 2016

**Comment by petrk94** [comment]
@worldworm 
I dont would count this as a problem, what one time work perfectly for its purpose, what you want to improve?

**Comment by KieranRobson** [comment]
Im looking through old issues for stale ones that could be closed, this project although has an old commit date, I believe its still worth adding as the original site is still up and it works as intended for editing markdown. Will add and create a PR now.
