### ISSUE TITLE
Add Cuttlefish email tracker

### ISSUE THREAD

**Issue by SangramChavan** [awesome-selfhosted/awesome-selfhosted#941]
https://cuttlefish.io/

Make sure your emails arrive at their destinations. Keeps your email reputation high by automatically holding back emails to destinations that have previously bounced.

Real time analytics

**Comment by nodiscc** [comment]
https://github.com/mlandauer/cuttlefish
AGPLv3 / Ruby

I'd rather add it to https://github.com/Kickball/awesome-selfhosted#mailing-lists-and-newsletters

**Comment by mightyfree** [comment]
@nodiscc  The SSL on the developer's site expired since April. Per GitHub, this project is not being maintained - a ton of unanswered issues at github.com/mlandauer/cuttlefish/issues.

I recommend skipping the addition and closing this issue.

**Comment by aadrian** [comment]
@mightyfree even in this state, cuttlefish is still more useful than the alternatives :) .

Also note that last commit of @mlandauer was in June :) https://github.com/mlandauer/cuttlefish/commits/master

**Comment by mightyfree** [comment]
@aadrian Postal for transactional e-mails: https://github.com/atech/postal - excellent platform. Mautic & Mailtrain are solid choices for marketing e-mails.

I'm all for adding Cuttlefish, but geez, no replies to that many issues? Drives me nuts! X)

**Comment by Kickball** [comment]
June 6th doesn't seem that old, but the issues are concerning.

**Comment by nodiscc** [comment]
There are no significant issues on their bug tracker anymore and the website now works properly with HTTPS.

**Comment by nodiscc** [comment]
Unmaintained since June 2022.
